### ISSUE TITLE
helm chart with at least two subcharts brings down the cluster

### ISSUE THREAD

**Issue by janwillies** [kubernetes/helm#1003]
This chart brings down a kubernetes cluster because of repeated creation/termination of pods: https://kubernetes.slack.com/files/jcw/F1W7N7L31/test-0.1.0.tgz

It consists of two postgres subcharts (deployments, services) and one top-level chart (job):

```
---
# Source: test/charts/dmc-db/templates/service.yaml
# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: dmc-db
  labels:
    heritage: "Tiller"
    release: "cranky-condor"
    chart: "dmc-db-9.5.3"
spec:
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: dmc-db

---
# Source: test/templates/initializer-job.yaml
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: initializer
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # This makes it easy to search for all components of a release using kubectl.
    release: "cranky-condor"
    # This makes it easy to audit chart usage.
    chart: "test-0.1.0"
spec:
  template:
    metadata:
      name: initializer
      labels:
        release: "cranky-condor"
    spec:
      containers:
      - name: initializer
        image: "test.foo.bartools/initializer:latest"
      restartPolicy: Never

---
# Source: test/charts/abo-db/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: abo-db
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # This makes it easy to search for all components of a release using kubectl.
    release: "cranky-condor"
    # This makes it easy to audit chart usage.
    chart: "abo-db-9.5.3"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abo-db
        release: "cranky-condor"
    spec:
      containers:
      - name: abo-db
        image: "postgres:9.5.3"
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: "test"
          - name: POSTGRES_PASSWORD
            value: "test"
        ports:
          - name: postgres
            containerPort: 5432

---
# Source: test/charts/abo-db/templates/service.yaml
# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: abo-db
  labels:
    heritage: "Tiller"
    release: "cranky-condor"
    chart: "abo-db-9.5.3"
spec:
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: abo-db

---
# Source: test/charts/dmc-db/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dmc-db
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # This makes it easy to search for all components of a release using kubectl.
    release: "cranky-condor"
    # This makes it easy to audit chart usage.
    chart: "dmc-db-9.5.3"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dmc-db
        release: "cranky-condor"
    spec:
      containers:
      - name: dmc-db
        image: "postgres:9.5.3"
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: "test"
          - name: POSTGRES_PASSWORD
            value: "test"
        ports:
          - name: postgres
            containerPort: 5432
```

Leaving out the top-level job seems to not trigger the bug.
