### ISSUE TITLE
Relax linter "quotes" requirement 

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1037]
Currently the linter is too strict in terms of quoting, we should revisit in which cases this is a valid warning and in which other cases this is an inconvenience or even a problem.

```
[WARNING] templates/odoo-svc.yaml: wrap substitution functions in quotes or use the sprig "quote" function: : {{ .Release.Name }} -> : {{ .Release.Name  | quote }}
```

https://github.com/kubernetes/helm/issues/689#issuecomment-225097389

**Comment by sameersbn** [comment]
I was testing the use of using unquoted values for labels and selectors fields and noticed the same issues that we originally mentioned in https://github.com/kubernetes/helm/issues/689#issuecomment-225097389. 

For example the following will cause a deployment to fail with the msg `Error: release sweet-dachshund failed: unable to decode "": [pos 375]: json: expect char '"' but got char '2'`

```
  labels:
    build: 201608
```

The linter rules can be enforced using the `--strict` arg. At the moment the linter only warns the user about these with issues without causing the linter to fail. I think its good that chart developers are warned about this to avoid user issues.

**Comment by waisbrot** [comment]
Here's an example where linter should not complain about quotes:

```
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: my-deployment
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{default 1 .Values.replicas}}
...
```

kubectl will check the type of `replicas` and it _must_ be an integer. But the linter sees that I've got an unquoted integer and warns. The above code gets a linter warning but works. Changing the line to 

```
replicas: {{default 1 .Values.replicas | quote}}
```

satisfies the linter but kubectl will fail.

(I believe this is what @migmartri is also describing)
