### ISSUE TITLE
Pass parameters to includes

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1054]
It'd be useful to pass in params when rendering includes / partials.

Related to #1006.

**Comment by technosophos** [comment]
That's what the second parameter to `include` is for. You can use `tuple` or `dict` to send _ad hoc_ values into `include`.

IIRC, it would look something like:

```
{{$data := dict "Values" .Values "Extra" "foo"}}
{{include "foo.tpl" $data}}
```

Then from inside of `foo.tpl` you would be able to access `{{.Values}}` and `{{.Extra}}`.

**Comment by devth** [comment]
Yep, that's what I need. Is there a way to do it inline instead of having to define a named data structure?

**Comment by technosophos** [comment]
Still testing some things on this one.

**Comment by technosophos** [comment]
We seem to have basically hit the limits of Go's template system on this one. I'm marking as "closed, won't fix" simply because we don't know what else to here.

**Comment by jcheroske** [comment]
Go template syntax is one of the ugliest syntaxes I've ever seen. I can't believe this is what we are having to learn in 2018. No wonder humans can't solve any real problems.

**Comment by bacongobbler** [comment]
@jcheroske indeed, text/template certainly has its fair share of quirks. Have you had a chance to look at the proposed Lua DSL for Helm 3?

https://www.youtube.com/watch?v=V8VCdlpWWr8&t=24m30s&list=PLj6h78yzYM2PZf9eA7bhWnIh_mK1vyOfU&index=288

**Comment by AndresPineros** [comment]
Ahhh classic, reaching a Golang Template limit.

- Me: Hmmm, that's a great idea to reuse some templates here and there, can I do this Go Templates?
- Go Templates: NOPE

- Oh, alright, so maybe I can try this approach then, right?
- NOPE

- Well, I know it is ugly but maybe if I...
- NOPE NOPE, stop trying, NOOOOOPE.

**Comment by bacongobbler** [comment]
I hate to be a bum but in the interest of preventing needless notifications to community members watching this issue, kindly keep the conversation on-topic. Unless there's constructive criticism that contributes to the discussion, please keep that conversation offline. Thanks!

**Comment by edrandall** [comment]
Is there any update on the proposed LUA templates?
I'm hitting similar issues - the Go template framework places needless restrictions making it completely inadequate for solving the problem.

**Comment by toabi** [comment]
If somebody stumbles upon this (or somebody here can give improvement suggestions), this issue was helpful and I solved this problem finally like that. (But I'm also a helm/gotpl-beginner.)

I wrote a template for basic cronjobs where usually only the schedule and args are different. That's in some `templates/_cronjob-django-admin.tpl` like that:

```
{{- define "myApp.cronjob-django-admin" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "myApp.fullname" . }}-{{ .Args.Name }}
  labels:
    {{- include "myApp.labels" . | nindent 4 }}
spec:
  schedule: '{{ .Args.Schedule | default "0 0 * * *"}}'
  concurrencyPolicy: Forbid
  jobTemplate: [redacted, but .Values/.Chart/… are all available as usually in here because of the merge]
{{- end }}
```

So if I need to define a cronjob I can create a `templates/cronjob-do-some-stuff.yaml` in which I just have to write this:

```
{{$data := dict
  "Name" "do-some-stuff"
  "Schedule" .Values.schedules.doSomeStuff
  "Args" (list "do_some_stuff")
}}
{{- include "myApp.cronjob-django-admin" (merge (dict "Args" $data) . ) -}}
```

So if my app has like 4 differently sheduled django-admin commands I have 4 different cronjobs but not a giant amount of duplicate code in my helm chart.
