### ISSUE TITLE
Loop over a range from N to {{.Values.someCount}}

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1055]
I have a use case where I'd like to create `N` resources where `N` == some value from values.yaml, e.g. `.Values.replicaCount` and have access to an `index`. For example, where `???` is the structure I'm missing, given a `replicaCount` int:

```yaml
{{range $index, $element := ???}}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-{{$index}}
  namespace: {{.Values.global.namespace}}
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
    - name: client
      port: 2181
    - name: secure-client
      port: 2281
    - name: followers
      port: 2888
    - name: election
      port: 3888
  selector:
    app: zookeeper
    server-id: "{{$index}}"
{{end}}
```

From my research it looks like this currently isn't possible with Go templates.

**Comment by mumoshu** [comment]
I've encountered the exact same issue while porting the `memcached` helmc chart to helm v2.
I believe it will be necessary for us to create helm packages for named, stateful, pet-like apps.
+1 for adding this!

For me, something like https://godoc.org/github.com/bradfitz/iter would be enough.

**Comment by technosophos** [comment]
Just so I'm clear, you want to be able to do this?

```
{{range $i, $e := until 5}}
  {{$i}}
{{end}}
```

And have that produce

```
0
1
2
3
4
```

What should `$e` be?

**Comment by technosophos** [comment]
Incidentally, you can fake this bash-style with a tuple:

```
{{range $i, $e := tuple 1 2 3 4 5}}
{{end}
```

Or, for a really weird one:

```
{{range $i, $junk := randAscii 5 | split ""}}
{{end}}
```

**Comment by devth** [comment]
Right,

```
{{range $i, $e := until .Values.replicas}}
  {{$i}}
{{end}}
```

Is what I'm after. The tuple hack wouldn't work for me since I need a range up to some variable.

I'm not sure what `$e` should be.

**Comment by technosophos** [comment]
Okay. I'm working on it, and will hopefully get a PR in today.

**Comment by technosophos** [comment]
So I added `until` and `untilStep` to Sprig, and then updated the deps.

This gives you `until $end` (as discussed above), and also a Pythonesque `untilStep $start $end $step` (like the Python `range` function).

Both can take negative integers to decrement.

**Comment by devth** [comment]
Awesome! Looking forward to trying it out.

**Comment by killix** [comment]
trying to do the same think with:
```yaml
{{- range $k, $v := until (atoi (quote .Values.Replicas) | default 5) }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-{{$v}}
  namespace: {{ .Values.Namespace }}
  labels:
    node: "zookeeper-{{$v}}"
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: {{.Values.PeerPort}}
    name: peer
  - port: {{.Values.LeaderElectionPort}}
    name: leader-election
  - port: {{.Values.ClientPort}}
    name: client
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
    zookeepernode: "zookeeper-{{$v}}"
{{- end -}}
```

But i get this error:

```console
Error: render error in "zookeeper/templates/deployment.yaml": template: zookeeper/templates/deployment.yaml:6:22: executing "zookeeper/templates/deployment.yaml" at <.Values.global.names...>: can't evaluate field Values in type int
```

May be i forget something, any idea?

**Comment by bansalrajat** [comment]
how do i change the starting point of the range  so to start from a custom index . 
like i want to run the loop from 50 -100 rather than 0-100.

**Comment by moolbits** [comment]
> how do i change the starting point of the range so to start from a custom index .
> like i want to run the loop from 50 -100 rather than 0-100.

@bansalrajat You can use `untilStep` to get the desired result:

```yaml
{{- range untilStep 50 101 1 }}
- name: http
  containerPort: {{ . }}
  protocol: TCP
{{- end }}
```
