### ISSUE TITLE
Kubernetes resources not updated after upgrading a Helm release

### ISSUE THREAD

**Issue by macat** [kubernetes/helm#1058]
Helm version: `v2.0.0-alpha.3`

`helm upgrade` command does not update Kubernetes resource.

Steps to reproduce:
1. Create a release
2. Update a variable with `helm upgrade -f value`
3. Compare generated manifest file (`helm get`) with `kubectl get`

Example:

`templates/pod.yml`:

```yaml
...
  containers:
  - name: "waiter-{{ .Values.team }}"
...
```

Initially created the release with `helm install --set team=great teest`.

Then updated with helm  `upgrade listening-snake teest -f vv.yml`. Which updated the release to:

```yaml
VERSION: 3
RELEASED: Mon Aug 15 16:36:59 2016
CHART: teest-0.1.0
USER-SUPPLIED VALUES:
team: abc

COMPUTED VALUES:
Name: my-alpine
team: abc

HOOKS:
MANIFEST:

---
# Source: teest/templates/pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: "listening-snake-my-alpine"
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: "listening-snake"
    # This makes it easy to audit chart usage.
    chart: "teest-0.1.0"
  annotations:
    "helm.sh/created": "1471293419"
spec:
  # This shows how to use a simple value. This will look for a passed-in value
  # called restartPolicy. If it is not found, it will use the default value.
  # Never is a slightly optimized version of the
  # more conventional syntax: Never
  restartPolicy: Never
  containers:
  - name: "waiter-abc"
```

The Kubernetes pod resource was never modified by Tiller as it still shows `waiter-great` as container name.

**Comment by macat** [comment]
Actually I found the relevant Tiller log line. 

```2016-08-15 20:36:59.794342 I | error updating the resource listening-snake-my-alpine:
       	 Pod "listening-snake-my-alpine" is invalid: spec.containers: Forbidden: pod updates may not add or remove containers```

**Comment by michelleN** [comment]
Thanks @macat. The error here should be returned to the client, the upgrade should fail, and we should be able to rollback to the previous release. 
I'm thinking we should address this issue as part of the`kubectl rollback` story #1004

**Comment by michelleN** [comment]
@macat the errors now get propogated to the helm client. hope that helps!

**Comment by macat** [comment]
@michelleN Awesome, thank you!

**Comment by xmik** [comment]
This happened to me using:
```
$ helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
```
I had a Chart with 1 Container and had its resources (cpu, memory) set. I always install and upgrade using the same command:
```
helm upgrade gitit-production ./k8s-chart/gitit --install --wait --timeout 600 -f ./k8s-chart/gitit/values_production.yaml --namespace production --debug
```
When I changed the resources from:
```
resources:
      requests:
        cpu: "200m"
        memory: "700Mi"
      limits:
        cpu: "800m"
        memory: "2Gi"
```
to
```
resources:
      requests:
        cpu: "100m"
        memory: "300Mi"
      limits:
        cpu: "350m"
        memory: "600Mi"
```
(and didn't make any other change to the Chart) helm succeeded, container was recreated, but its resources were unchanged.

I tested with:
```
kubectl -n production get pods --selector=fullname=gitit-production  -o jsonpath='{.items[*].spec.containers[].resources.requests}'
kubectl -n production get pods --selector=fullname=gitit-production  -o jsonpath='{.items[*].spec.containers[].resources.limits}'
```
