### ISSUE TITLE
flatten chart representation in "repo chart parser"

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes/helm#1153]
There's currently a notion of a "chartfile" as a sub-property of a chart's representation in the repo index. Here's some relevant code:

https://github.com/kubernetes/helm/blob/master/pkg/repo/repo.go#L155

And from an example on the docs page of how we're representing a chart in a repo's `index.yaml` file:

```
alpine-0.1.0:
  name: alpine
  url: https://storage.googleapis.com/kubernetes-charts/alpine-0.1.0.tgz
  created: 2016-05-26 11:23:44.086354411 +0000 UTC
  checksum: a61575c2d3160e5e39abf2a5ec984d6119404b18
  chartfile:
    name: alpine
    description: Deploy a basic Alpine Linux pod
    version: 0.1.0
    home: https://github.com/example-charts/alpine
```

It's not clear what the semantic or organizational value of the `chartfile` object is, and there's some data redundancy in the `name` property. How about we do something like this instead:

```
alpine-0.1.0:
  name: alpine
  url: https://storage.googleapis.com/kubernetes-charts/alpine-0.1.0.tgz
  created: 2016-05-26 11:23:44.086354411 +0000 UTC
  checksum: a61575c2d3160e5e39abf2a5ec984d6119404b18
  description: Deploy a basic Alpine Linux pod
  version: 0.1.0
  home: https://github.com/example-charts/alpine
```
