### ISSUE TITLE
Alter schema of 'index.yaml'

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1197]
The current index.yaml file looks like this:

```yaml
mariner-4.3.2:
  name: mariner-4.3.2
  url: localhost:8879/charts/mariner-4.3.2.tgz
  chartfile:
    name: mariner
    version: "4.3.2"
    description: Some description
    icon: https://example.com/path/to/icon.png
mariner-4.1.1:
  name: mariner-4.1.1
  url: localhost:8879/charts/mariner-4.1.1.tgz
  chartfile:
    name: mariner
    version: "4.3.2"
    description: Some description
    icon: https://example.com/path/to/icon.png
alpine-0.1.0:
  name: alpine-0.1.0
  url: localhost:8879/charts/alpine-0.1.0.tgz
  chartfile: ...
```

There have been ongoing discussions to alter this format before Alpha.5 releases. The goals for altering are:

- Fewer repeated fields
- Flatter chart metadata
- Easier structure for clients to process, where clients may be `helm` or something much simpler like `jq`.

Here's the proposed new version:

```yaml
mariner:
  - version: "4.3.2"
     url: localhost:8879/charts/mariner-4.3.2.tgz
     digest: "sha256:..."
     name: mariner
     description: Some description
     icon: https://example.com/path/to/icon.png
     # rest of Chart.yaml fields
  - version: "4.1.1"
    url: localhost:8879/charts/mariner-4.1.1.tgz
    digest: "sha256:..."
    name: mariner
    description: Some description
    icon: https://example.com/path/to/icon.png
    # rest of Chart.yaml fields
alpine:
  - version: 0.1.0
     url: localhost:8879/charts/alpine-0.1.0.tgz
     # ...
```

This presents the data in a more tree-like way:

```
CHART:
    VERSIONS[]
CHART:
    VERSIONS[]
```

Note that it does collapse the `chartfile` fields into the versions object.

When it comes to ordering the VERSIONS[] list, it should be ordered by version, descending. So the newest release is in VERSIONS[0]. Assessing the stability of a version is done by SemVer 2 rules.
