### ISSUE TITLE
helm install should create objects in an order

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1228]
It will be nice to have services install before rc/deployments something like https://github.com/helm/helm-classic/blob/master/action/install.go#L18  so that the pods will have the ip of the service in its environment.

**Comment by elementalvoid** [comment]
I've been setting my services, secrets, and configmaps as pre-install and pre-upgrade hooks to achieve this behavior. 

Example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
```
