### ISSUE TITLE
upgrade: modifying pod template labels in deployment makes upgrade not work

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1390]
Not necessarily a Helm issue, but whilst playing with upgrades, I noticed an issue in the way we currently construct charts. If you apply a deployment that changes the pod template's labels, the deployment cannot bring the old pods down (and new pods may not start due to not being able to mount persistent volumes).

For example, the MariaDB chart has the following pod template:

```
...
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
...
```

When trying to upgrade from mariadb 0.5.0 to mariadb 0.5.1, the `chart` label above will get a new value, reflecting the new version. The deployment creates a new ReplicaSet, as expected, but is unable to bring down the old one since the label selectors have changed. 

```
$ helm upgrade eating-mink ./mariadb-0.5.1
eating-mink has been upgraded. Happy Helming!

$ kubectl get rs
eating-mink-mariadb-4210982379   1         1         9m
eating-mink-mariadb-3263201545   1         1         7m

$ kubectl get pods
NAME                                   READY     STATUS     RESTARTS   AGE
eating-mink-mariadb-3263201545-9oobv   0/1       Init:0/1   0          7m
eating-mink-mariadb-4210982379-mhbtk   1/1       Running    0          10m
```

In this particular case, the new pod stays in the init state because the PVC volume cannot be attached, it's in use by the old pod.

The solution is to ensure that the labels used for pod template don't change between upgrades (removing the `chart` label here makes upgrades work).

Since Helm is just doing something similar to `kubectl apply` under the hood, I tried to upgrade my deployment using `kubectl`, which complained with:

```
The Deployment "eating-mink-mariadb" is invalid.
spec.template.metadata.labels: Invalid value: {"app":"eating-mink-mariadb","chart":"mariadb-0.5.1","heritage":"Tiller","release":"eating-mink"}: `selector` does not match template `labels
```

Should `helm upgrade` spot this and complain with a similar message?

/cc @michelleN @viglesiasce
