### ISSUE TITLE
Release failed [resourceX already exists]

### ISSUE THREAD

**Issue by UnderGreen** [kubernetes/helm#1479]
I tried to write some charts with dependencies. Chart heapster depends on chart influxdb. I created influxdb chart, hosted it locally with helm repo. Created heapster chart, did `helm dependency update`:
```bash
├── heapster
│   ├── charts
│   │   └── influxdb-0.1.0.tgz
│   ├── Chart.yaml
│   ├── Dockerfile
│   ├── Makefile
│   ├── requirements.lock
│   ├── requirements.yaml
│   ├── templates
│   │   ├── _helpers.tpl
│   │   ├── rc.yaml
│   │   └── svc.yaml
│   └── values.yaml
```
But, when I am trying to install heapster chart I am getting error:
```
Error: release wandering-rode failed: [services "wandering-rode-influxdb" already exists, replicationcontrollers "wandering-rode-influxdb" already exists]
```
And it all on after deleting all resources(I checked with `helm list --all`).

helm version:
```
Client: &version.Version{SemVer:"v2.0.0-beta.2", GitCommit:"8a5550d0c6785eaa94eac80e0c1d11a92c355a02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.2", GitCommit:"8a5550d0c6785eaa94eac80e0c1d11a92c355a02", GitTreeState:"clean"}
```

**Comment by UnderGreen** [comment]
[My repo](https://github.com/UnderGreen/helm-charts) with these charts.

**Comment by technosophos** [comment]
If you do a `helm install --dry-run --debug $CHARTNAME`, are you seeing multiple services getting defined with the same name?

**Comment by UnderGreen** [comment]
yes, I think problem in `{{ template "fullname" . }}`. For influxdb and heapster I am using _helpers.tpl with the same content. 
```yaml
# Source: heapster/charts/influxdb/templates/rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: looping-unicor-heapster
    heritage: "Tiller"
    release: "looping-unicor"
    chart: "influxdb-0.1.0"
  name: looping-unicor-heapster


----
# Source: heapster/templates/rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: looping-unicor-heapster
    name: looping-unicor-heapster
    heritage: "Tiller"
    release: "looping-unicor"
    chart: "heapster-0.1.0"
  name: looping-unicor-heapster
```
How I can fix this problem? I need for heapster fullname with `heapster` suffix and for influxdb - `influxdb` suffix.
