### ISSUE TITLE
Upgrade failed when upgrading a TPR resource

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#1531]
Using the chart in this PR https://github.com/kubernetes/charts/pull/214

Trying to simulate an etcd upgrade by deloying a TRP resource with etcd version v3.0.14 then upgrading using the default cluster.version from values.yaml to perform an upgrade.  Not sure if this is related to https://github.com/kubernetes/kubernetes/issues/29542

```
helm install . --name etcd-operator --set cluster.version=v3.0.14
helm upgrade etcd-operator .
Error: UPGRADE FAILED: unable to find api field in struct Unknown for the json field "metadata"
```

```
helm version
Client: &version.Version{SemVer:"v2.0.0-rc.2", GitCommit:"f8037c83c647b56d9ef42d0d5254e5fc563e3048", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-rc.2", GitCommit:"f8037c83c647b56d9ef42d0d5254e5fc563e3048", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
Out of curiosity, can you dump the upgrade YAML, and then run it manually with `kubectl apply`? We've been trying to trace down some issues with the apply logic.

**Comment by lachie83** [comment]
```
lachlanevenson@faux$ helm install . --dry-run --debug --name etcd-operator --set cluster.version=v3.0.14
Created tunnel using local port: '50430'
SERVER: ":50430"
NAME:   etcd-operator
TARGET NAMESPACE:   default
CHART:  etcd-operator 0.1.0
MANIFEST: 
---
# Source: etcd-operator/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator-etcd-opera
  labels:
    chart: "etcd-operator-0.1.0"
    app: etcd-operator-etcd-opera
    heritage: "Tiller"
    release: "etcd-operator"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        chart: "etcd-operator-0.1.0"
        app: etcd-operator-etcd-opera
        heritage: "Tiller"
        release: "etcd-operator"
    spec:
      containers:
      - name: etcd-operator
        image: "quay.io/coreos/etcd-operator:latest"
        imagePullPolicy: IfNotPresent
        command: 
        - "/bin/sh"
        - "-c"
        - "/usr/local/bin/etcd-operator --pv-provisioner=kubernetes.io/gce-pd"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
            
---
# Source: etcd-operator/templates/etcd-cluster.yaml
apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  labels:
    chart: "etcd-operator-0.1.0"
    app: etcd-operator-etcd-opera
    heritage: "Tiller"
    release: "etcd-operator"
  name: "etcd-cluster"
spec:
  size: 3
  version: "v3.0.14"
  backup:
    maxSnapshot: 5
    snapshotIntervalInSecond: 30
    storageType: PersistentVolume
    volumeSizeInMB: 512
```

**Comment by lachie83** [comment]
Manual `kubectl apply` worked. FYI the manifest was rendered by hand

```
lachlanevenson@faux$ cat etcd-cluster-upgrade.yaml 
apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  labels:
    chart: "etcd-operator-0.1.0"
    app: "etcd-operator-etcd-opera"
    heritage: "Tiller"
    release: "etcd-operator"
  name: "etcd-cluster"
spec:
  size: 3
  version: "v3.1.0-rc.0"
  backup:
    maxSnapshot: 5
    snapshotIntervalInSecond: 30
    storageType: PersistentVolume
    volumeSizeInMB: 512
lachlanevenson@faux$ kubectl apply -f etcd-cluster-upgrade.yaml 
etcdcluster "etcd-cluster" configured
```
