### ISSUE TITLE
Install Command: Unable to Escape Periods in Keys

### ISSUE THREAD

**Issue by icereval** [kubernetes/helm#1540]
The install command splits keys on every period, preventing assignment of a key containing the period character. A [RegEx Split](https://golang.org/pkg/regexp/#Regexp.Split) might be a good option to allow for these escaped characters.

- https://github.com/kubernetes/helm/blob/6b222cdc0fc7d94ce22a265d3a3580cc7afd3cab/cmd/helm/install.go#L271

e.g. yaml
```
...
    annotations:
{{ toYaml .Values.annotations | indent 6 }}
```

e.g. command
`--set annotations.iam\.amazonaws\.com/role=k8s-logger`

Result:
```
annotations:
    iam:
        amazonaws:
            com/role: k8s-logger
```

Expected:
```
annotations:
    iam.amazonaws.com/role: k8s-logger
```
