### ISSUE TITLE
Repository URLs with and without trailing slash are treated as different

### ISSUE THREAD

**Issue by jayme-github** [kubernetes/helm#1588]
Maybe this is the intended behavior but it leads to user errors when they type private repositories "wrong" (like with `helm repo add foo  https://host.com` instead of `helm repo add foo  https://host.com/` or within the `requirements.yaml`).

Example:
-----------
~/.helm/repository/repositories.yaml 
```yaml
apiVersion: v1
generated: 2016-11-21T14:16:06.747386772+01:00
repositories:
- cache: stable-index.yaml
  name: stable
  url: https://kubernetes-charts.storage.googleapis.com/
```

requirements.yaml
```yaml
dependencies:
  - name: redis
    version: 0.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
```

```bash
$ helm dependency build  .
Error: no repository definition for https://kubernetes-charts.storage.googleapis.com. Try 'helm repo add'
```

This could be fixed by always removing the trailing slash when comparing URLs but I'm unsure if this is always the correct solution

```patch
diff --git a/cmd/helm/downloader/manager.go b/cmd/helm/downloader/manager.go
index db3d3c4..c35264d 100644
--- a/cmd/helm/downloader/manager.go
+++ b/cmd/helm/downloader/manager.go
@@ -320,6 +320,14 @@ func urlsAreEqual(a, b string) bool {
        if err != nil {
                return false
        }
+       // Make sure URLs with or without trailing slash are threated equal
+       if au.Path == "/" {
+               au.Path = ""
+       }
+       if bu.Path == "/" {
+               bu.Path = ""
+       }
+
        return au.String() == bu.String()
 }
```
