### ISSUE TITLE
"true" as a value in values.yaml breaks upgrade

### ISSUE THREAD

**Issue by ged15** [kubernetes/helm#1651]
Hello!

First of all thanks for the great work on Helm. It solves so many problems!
I am trying to install Deis Workflow 2.9 using Helm. I customise some values using `values.yaml`:

```yaml
# ...
router:
  deployment_annotations:
    router.deis.io/nginx.platformDomain: "foo.com"
    router.deis.io/nginx.ssl.enforce: "true"
# ...
```

When running `helm upgrade <release name> -f values.yaml` I get the following error:

```
Error: UPGRADE FAILED: unable to decode "": [pos 288]: json: expect char '"' but got char 't'
```

I believe the `"true"` messes up the parsing somewhere. This, however, works:

```yaml
# ...
router:
  deployment_annotations:
    router.deis.io/nginx.ssl.enforce: "\"true\"" # note the escaped quotes
# ...
```
