### ISSUE TITLE
Feature Request: Support Kubernetes' valueFrom in values file

### ISSUE THREAD

**Issue by alon-argus** [kubernetes/helm#1662]
Suppose I want to use an already existing chart. I'd want to have the ability to override its values from ConfigMap or Secret that I already have in place. Currently I can only provide plain text. My wish is that I'd be able to provide something like Kubernetes' valueFrom. 

Example:

instead of:

```
mongodbPassword: some-password
```

I'd want to do something like:

```
mongodbPassword:
  valueFrom:
    secretKeyRef:
      name: mongo-secret
      key: password
```

This way I'll be able to store my secrets in a more secured place, and not necessarily together with the charts.

Thanks guys! <3 Helm
