### ISSUE TITLE
outdated named_templates.md? - scoped template names

### ISSUE THREAD

**Issue by so0k** [kubernetes/helm#1688]
[named_templates.md](https://github.com/kubernetes/helm/blob/release-2.1/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template) - last paragraph of `declaring and using templates` section says:

>There is one really important detail to keep in mind when naming templates: **template names are global**. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.
>
>One popular naming convention is to prefix each defined template with the name of the chart: `{{ define "mychart.labels" }}`

However, looking at the stable [Wordpress chart - deployment](https://github.com/kubernetes/charts/blob/2dd1d225fd6c3dad4752b24061047deda7cc4d67/stable/wordpress/templates/deployment.yaml#L22-L30) (which depends on the Mariadb chart) we see:

```
        - name: MARIADB_HOST
          value: {{ template "mariadb.fullname" . }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-root-password
```

here `template` is called to execute the `mariadb.fullname` template, note that its [definition](https://github.com/kubernetes/charts/blob/2dd1d225fd6c3dad4752b24061047deda7cc4d67/stable/mariadb/templates/_helpers.tpl#L13-L16)) -  is *not* prefixed:

```
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}
{{- end -}}
```
  
It's very confusing, the dependency section (and https://github.com/kubernetes/helm/issues/630) do talk about the scoping of sub charts.. so perhaps the `named_templates.md` document is outdated?

If so, I can do a PR with some changes to clarify it..
