### ISSUE TITLE
Communication with private repository

### ISSUE THREAD

**Issue by agalitsyn** [kubernetes/helm#1700]
Hi!

I'm trying to use helm with custom-made chart repository, basically it's a static files server with TLS. I want to add TLS support to helm for `repo add` kind of commands in a way:
* add `--cert-file` `--key-file` `--ca-file` flags to CLI commands
* pass certs info to `~/.helm/repository/repositories.yaml` by repo name
* refactor `repo` lib for several purposes
  * constructing `http.Client` for interaction with repository (with TLS config if it presents in config)
  * transform `Entry` to kind of config representation for `ChartRepository`
  * attach some methods like `repo.DownloadIndexFile` to `ChartRepository` struct

Generally, what do you think? Scratch is here https://github.com/gravitational/helm/pull/4/files
Actually I stuck with several things
* common place for building http.Client for ChartRepository
* not very clear serialization of ChartRepository to yaml config and back to struct
* download manager, it's kind of separate package, but anyway it works with repository, so I think  `ChartRepository` should have some dependency in struct on download manager instance

**Comment by technosophos** [comment]
I'm having a little bit of a hard time reading the output of that PR. What is it generated against?

In general, I think I understand what you are doing, and I think that is a solid approach. I didn't see any changes to the underlying YAML file format -- just the structure of the code that worked with them. Is that right?

If we related chart repo to the download manager, we'd need to move `cmd/helm/download` to `pkg/downloader`. But I think that would be okay.

**Comment by agalitsyn** [comment]
> I'm having a little bit of a hard time reading the output of that PR. What is it generated against?

true, fork's master consists of 1 merged PR, which will be anyway overwritten. Repushed clean latest master to forr

> I didn't see any changes to the underlying YAML file format -- just the structure of the code that worked with them. Is that right?

I proposed this structure
```
apiVersion: v1
generated: 2016-11-09T20:44:53.035380575+07:00
repositories:
- caFile: ""
  cache: stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  url: http://storage.googleapis.com/kubernetes-charts
- caFile: ""
  cache: local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  url: http://127.0.0.1:8879/charts
- caFile: /home/agalitsyn/ca.pem
  cache: tube-index.yaml
  certFile: /home/agalitsyn/client.pem
  keyFile: /home/agalitsyn/client-key.pem
  name: tube
  url: https://127.0.0.1:5000/charts
```

Thanks for helping!
