### ISSUE TITLE
helm cli - `--set` should support escaping

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#1726]
to support `--set nodeSelector.'failure-domain.beta.kubernetes.io/zone: us-west-1b'` 
an example chart used for that https://github.com/clearbit/charts/blob/master/stable/cluster-autoscaler/templates/deployment.yaml#L48-L52

**Comment by technosophos** [comment]
This was fixed in 2.1.3. Assuming we have a template like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- range $value := .Values.extraLabels}}
    {{ $value }}
    {{ end -}}
```

We can pass in multiple labels like this:

```
$ helm install --dry-run --debug --set "extraLabels={failure-domain.beta.kubernetes.io/zone: us-west-1b,foo: bar}" . 
```

And the output will be:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: errant-greyhound-i1726
  labels:
    chart: "i1726-0.1.0"
    failure-domain.beta.kubernetes.io/zone: us-west-1b
    foo: bar
```

You can quote strings, too. The easiest way is to use single quotes:

```
helm install --dry-run --debug --set "extraLabels={'failure-domain.beta.kubernetes.io/zone': us-west-1b,foo: bar}" .
```

For double quotes, use backslash escapes:

```
helm install --dry-run --debug --set "extraLabels={\"failure-domain.beta.kubernetes.io/zone\": us-west-1b,foo: bar}"
```
