### ISSUE TITLE
Add repo alias support to requirements.yaml

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/helm#1733]
A pain point with `requirements.yaml` files in charts is that `repository` is a required field in each dependency. 

For example, say I have a chart called `webapp-1.0.0` with a required chart `base-chart-0.1.0`.  In order to have a simple CI process around dependent charts, I _must_ already have the `base-chart`‘s tarball built, served, and fetched _from the correct repository_ in `webapp`‘s `/charts/` directory.

`webapp`'s `requirements.yaml`
```yaml
dependencies:
- name: base-chart
  version: 0.1.0
  repository: http://my-production-chart-repo.com
```

I'm not sure that there is a great workaround, other than making sure that the example `base-chart` updates and CI builds are separate from any other chart that requires it.

**Comment by brandoncole** [comment]
There's two concerns for me related to this:

1. The canonical URL for our helm repository is under flux, it could be `http://helm.company.com` or `http://product.company.com/charts`.  To further complicate things, we have Alpha and Beta environments so it could also be `http://helm.alpha.company.com` or `http://helm.beta.company.com`.  So we'd prefer not to hardcode a URL for the `repository` field in all our charts, if the repository is the local repository it'd be nice if it were something like:

```yaml
dependencies:
  - name: postgres
    version: 0.2.0
    repository: local
  - name: provisioner
    version: 0.2.0
    repository: local
```

2. Alternatively, and perhaps even better, it'd be nice if we could refer to the repo alias instead.  For example:

```bash
$ helm repo list
NAME     	URL
stable   	http://storage.googleapis.com/kubernetes-charts
local    	http://localhost:8879/charts
stablerepo	http://some.environment.specific.url.io/charts
```

```yaml
dependencies:
  - name: postgres
    version: 0.2.0
    repository: stablerepo
  - name: provisioner
    version: 0.2.0
    repository: stablerepo
```
