### ISSUE TITLE
Upgrading deis fails specifying valid values yaml

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/helm#1742]
Example yaml:
```

---
global:
  storage: s3
  database_location: "on-cluster"
  logger_redis_location: "on-cluster"
  influxdb_location: "on-cluster"
  grafana_location: "on-cluster"
  registry_location: ecr
  host_port: 5555
  secret_prefix: "private-registry"
s3:
  accesskey: XXXXXXXX
  secretkey: XXXXXXXX
  region: "us-east-1"
  registry_bucket: "aaaa-aaaa"
  database_bucket: "aaaa-aaaa"
  builder_bucket: "aaaa-aaaa"
controller:
  app_pull_policy: "IfNotPresent"
  registration_mode: "admin_only"
database:
  postgres:
    username: klasjdflkjasdlkf
    password: jfksldjfklsdf
monitor:
  grafana:
    user: admin
    password: admin
registry-token-refresher:
  ecr:
    accesskey: AAAAAAAAW3XAAAAAAA
    secretkey: AakdljlsafjdlkjflKSJFLKjalsjdflkasjdf
    region: "us-east-1"
    registryid: ""
    hostname: 234324324324.dkr.ecr.us-east-1.amazonaws.com
router:
  deployment_annotations:
    router.deis.io/nginx.serverNameHashBucketSize: 128
    router.deis.io/nginx.proxyRealIpCidrs: "0.0.0.0/0"
    router.deis.io/nginx.useProxyProtocol: true
  service_annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

issuing `helm upgrade -f values.yaml deis deis/workflow --version=v2.9.0 --kube-context=stag`

returns the following

Error: UPGRADE FAILED: YAML parse error on workflow/charts/router/templates/router-service.yaml: error converting YAML to JSON: yaml: line 5: did not find expected alphabetic or numeric character

I assume it is caused by the line:

    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'

If I remove this line, I get another error:

$ helm upgrade -f values.yaml deis deis/workflow --version=v2.9.0 --kube-context=stag

Error: UPGRADE FAILED: failed decoding reader into objects: unable to decode "": [pos 220]: json: expect char '"' but got char '1'
