### ISSUE TITLE
b64enc function should accept integers (and maybe floats)

### ISSUE THREAD

**Issue by dzavalkinolx** [kubernetes/helm#1771]
I'm creating secret with some values passed in `values.yaml` file. One of the values I want to add to secret is integer (id of zendesk view). Because `b64enc` function doesn't support integers and there is no cast to string function in templates I have to put my integer id as a string in `values.yaml` which is ugly and misleading in a long run (new team member can assume from values file that id can be non-integer, etc.).  Not sure if it is need but this is how I create secrets in my chart:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-hermes-secrets"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := .Values.hermesEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
```
