### ISSUE TITLE
error validating data: [found invalid field initialDelaySeconds for v1.HTTPGetAction, found invalid field timeoutSeconds for v1.HTTPGetAction]

### ISSUE THREAD

**Issue by SuperNami** [kubernetes/helm#1775]
After upgrading Tiller and the CLI to the latest version (v2.1.3) I got the following error while running my chart:

`Error: release unrealized-rattlesnake failed: error validating "": error validating data: [found invalid field initialDelaySeconds for v1.HTTPGetAction, found invalid field timeoutSeconds for v1.HTTPGetAction, found invalid field initialDelaySeconds for v1.HTTPGetAction, found invalid field timeoutSeconds for v1.HTTPGetAction, found invalid field limits for v1.Probe, found invalid field requests for v1.Probe, found invalid field resources for v1.Probe]`

It's pointing to the health check features:

```
        livenessProbe:
          httpGet:
            path: /
            port: http
            initialDelaySeconds: 120
            timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
```

These settings are exactly the same as official helm charts, so it shouldn't be failing.

Chart is located here: https://github.com/SuperNami/helm-charts
