### ISSUE TITLE
Consider changing primitive types to <version>.<kind>

### ISSUE THREAD

**Issue by bmelville** [kubernetes/helm#18]
Resource definitions all have things like:

- name: rc
  type: ReplicationController
  properties:
    kind: ReplicationController

This should really be filled in from the type.

**Comment by bmelville** [comment]
Really, every kubernetes primitive needs to provide an apiVersion and kind. These should be auto filled in from the type.

```
resources:
- name: rc
  type: v1.ReplicationController
  properties:
    ...
```
