### ISSUE TITLE
Deployments not always updated correctly

### ISSUE THREAD

**Issue by jayme-github** [kubernetes/helm#1844]
Kubernetes 1.4.7, Helm/Tiller v2.1.3

I have a strange behavior  from `helm upgrade` (v2.1.3) here. I've changed environment variables of a charts template (deployment) but those env's don't get updated by `helm upgrade`.
`helm get` shows the correctly updated manifest but in `kubectl get deployment -o yaml` the variables are missing. I'm able to `kubectl apply` the manifest I get from `helm get` without errors.

Installing a new release uses the correct env variables though.

Sadly I don't know how to this can be reproduced. Installing a new release and changing variables there works okay but the already broken releases stay broken.

I'm happy to dig deeper into this - unfortunately I don't know much about how to debug tiller.

 Users on slack report similar problems.

/cc @thomastaylor312

**Comment by jayme-github** [comment]
Reverting 525df8f0d1caf1372b1001bf91f28395ebb79e24 fixes this issue for me.
But please take this with care as I'm not very familiar with go and I not do extensive testing yet.

**Comment by jayme-github** [comment]
Still don't know in which situation my deployment got screwed but it is never "repaired" because helm creates the strategic merge patch based on the "last helm revision manifest" and the "target helm revision manifest" not on "currently running in cluster manifest" and "target helm revision manifest" - which might be correct from helms perspective.

**Comment by technosophos** [comment]
Can anyone reproduce the deployment issue on Kubernetes >= 1.5? Or, conversely, with Helm 2.0.x and Kubernetes 1.4?

The patching situation will be fixed in 2.2.0. @adamreese has been changing the merge logic. That may actually fix the deployment issue too, but when Adam and I tried to reproduce the issue yesterday (on k8s 1.5 and Helm master), we couldn't.

Thanks for the work you all have done tracking this down. I've seen quite a bit of traffic on the channel as you all work on it.

**Comment by mikejk8s** [comment]
@technosophos I've had the issue with 1.5.1 and helm 2.1.2 and possibly 2.1.1. I really don't recall the issue being very frequent prior to 1.5.1 but that may also be due to the fact that we're doing a lot more helm deployments now as 1.5.1 is our actual production cluster. If I get some time today I'll try to see if it's easily reproducible on my cluster. It seems pretty hit and miss, I had it happen yesterday with a deployment updating env vars but I've done it plenty of times and not had the issue as well.

**Comment by tback** [comment]
Colleague of jayme-github here.

We found two ways to reproduce a "broken" state:

1. Edit a resource manually outside of helm then perform an upgrade. The manual change will still be present after the upgrade.

2. Perform an upgrade on a failed release.
Helm will look into the failed release to figure out what to do which leads to undesired behavior.

Both are in line with what @jayme-github said in https://github.com/kubernetes/helm/issues/1844#issuecomment-274042885 . 

Maybe there are other ways to make helm "forget" to update resources but we couldn't reproduce those yet.

For now I think it would be best to fail in case a user tries to upgrade a broken release, but what is the desired behavior of helm regarding the presence of manual changes?

**Comment by thomastaylor312** [comment]
@technosophos I have heard similar grumblings from people about this. The problems I have seen are possibly related to Helm not updating a deployment correctly because I have old ReplicaSets that stick around. I am on 2.1.3 and k8s 1.5.1. Some discussion on the slack channel points to Helm using a [2 way merge patch](https://github.com/kubernetes/helm/blob/master/pkg/kube/client.go#L324) and `kubectl apply` doing a [3 way merge patch](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L553)

**Comment by technosophos** [comment]
Okay. I think this will be fixed in 2.2.0, where we are currently working on a rewrite of the update logic. @adamreese can you update this ticket when the update fixes get opened as a PR?

**Comment by jayme-github** [comment]
Sounds good. Could anyone answer the question of @tback regarding manual changes in manifests deployed via helm (´kubectl edit ...`)? Should those changes be overwritten by upgrading a release or should helm keep them/merge them into the upgrade manifest?

**Comment by technosophos** [comment]
Okay, we've divided this bug up into a few chunks to track down internally. I'll try to address @tback's points while @adamreese is looking into some of the other deployment problems.

> 1. Edit a resource manually outside of helm then perform an upgrade. The manual change will still be present after the upgrade.

Currently, the upgrade will compare the last Tiller release to the just-submitted chart. Only the differences are sent on to Kubernetes. So in your example above, are any differences sent?

>Perform an upgrade on a failed release.
> Helm will look into the failed release to figure out what to do which leads to undesired behavior.

Yes, this is intentional. If a release failed because its values were bad or the manifest could not be installed, you cannot "upgrade" it. The reason for this is because we can't make a knowledgable set of assumptions about the "desired end state" of the release based on a failed install. So instead, we've recommended that people use `helm delete` and then `helm install --replace`. Basically, that will cause your fixed installation to begin from a known-good state.

At some point, we might be able to automate this into the upgrade logic once we work through some of the edge cases.

**Comment by thomastaylor312** [comment]
Ok, here is what is going on with deployments on our end. Here is a manifest that we are using:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kubectl
spec:
  replicas: {{ default 1 .Values.replicas.kubectl }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-kubectl
        proxy_type: k8s
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
        revision: {{ .Release.Revision | quote }}
        fullname: {{ template "fullname" . }}
    spec:
      containers:
      - name: jenkins-swarm-kubectl
        image: gcr.io/{{ .Values.global.project }}/jenkins-swarm-kubectl:1.1
        volumeMounts:
        - mountPath: /var/jenkins_swarm
          name: snapbot-token
        imagePullPolicy: Always
        env:
          - name: DESCRIPTION
            value: "Proxy agent for kubernetes with kubectl installed"
          - name: LABELS
            value: k8s
          - name: SWARM_USERNAME
            value: {{ .Values.swarmUser }}
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      volumes:
      - name: token
        secret:
          secretName: token
```

After creation there is one pod and one replica set:
```console
# Pods
NAME                                                              READY     STATUS             RESTARTS   AGE
jenkins-dev-private-taylor-jenkins-42612270-60lp5                 1/1       Running            0          8m
jenkins-dev-private-taylor-jenkins-agents-kubectl-17472329m9fwq   1/1       Running            0          8m

# Replica Set
NAME                                                           DESIRED   CURRENT   READY     AGE
jenkins-dev-private-taylor-jenkins-42612270                    1         1         1         9m
jenkins-dev-private-taylor-jenkins-agents-kubectl-174723296    1         1         1         9m
```

After adding an env variable to the template and upgrading, there are duplicate pods and replica sets, even though I have `type: Recreate` set:
```console
# Pods
NAME                                                              READY     STATUS             RESTARTS   AGE
jenkins-dev-private-taylor-jenkins-393623087-xp05g                1/1       Running            0          4m
jenkins-dev-private-taylor-jenkins-agents-kubectl-17472329m9fwq   1/1       Running            0          16m
jenkins-dev-private-taylor-jenkins-agents-kubectl-33092511s8csr   1/1       Running            0          4m

# Replica Sets
jenkins-dev-private-taylor-jenkins-393623087                   1         1         1         5m
jenkins-dev-private-taylor-jenkins-agents-kubectl-174723296    1         1         1         17m
jenkins-dev-private-taylor-jenkins-agents-kubectl-3309251138   1         1         1         5m
```

Also, when I look at the definition of the deployment, replica set, and pod, they all show the changes reflected in my template, while the old replica sets and pods have the previous template.

**Comment by thomastaylor312** [comment]
@adamreese To clarify, are you saying to add the exact same set of labels as a selector or something else?

**Comment by thomastaylor312** [comment]
After some troubleshooting with @adamreese, we found that if your pod template spec labels change between releases, it can orphan the old replica sets. That addressed my issues with Deployments

**Comment by technosophos** [comment]
This is on the 2.2.0 roadmap to be fixed, but it's starting to look like the fix is really a matter of chart authorship, not a code change. Am I right in that assessment?

If that's the case, I think we should turn this into a documentation fix, and add it to the chart FAQ or something, since we've seen this issue come up in several forms.

**Comment by thomastaylor312** [comment]
@technosophos I am not sure if this will also address the problem @jayme-github initially opened this issue with

**Comment by technosophos** [comment]
@tback and @jayme-github : If you have time to check in on this issue, here's where we are:

- We've determined that deployments that don't have a `selector` defined will often (silently) abandon replica sets
- We've found that deployments are particularly sensitive to label changes, and (if I understand it correctly) will on occasion silently ignore updates if labels are changed. This can be a problem if the labels include things like timestamps, release version or chart version
- And there is no way to upgrade a failed release into a regular release without first deleting the failed release (then using `helm install --reuse`)

What we are not sure about is if there are lingering conditions with Deployments that also may be impacting your original problem. IIRC, @adamreese has been able to successfully modify environment variables on Deployment objects, and I'm not sure what the differences are between his approach and your approach.

Sorry for the long message. We're really interested in getting this all sorted out in time for the 2.2.0 release.

**Comment by technosophos** [comment]
We seem to be stalled out on verifying whether the fix above solves this problem. I'll leave the issue open for a bit longer, but I'm planning on closing it when I release 2.2.0.

**Comment by technosophos** [comment]
Quick update: After updating the internals for TPR support, we tested Deployment scenarios for the 2.2.0 candidate code. We tested adding, modify, and removing env vars on the template spec. All seems to work now _provided_ you use a selector as described above.

To test:

- Install the latest Helm canary client: https://github.com/kubernetes/helm/blob/master/docs/install.md#from-canary-builds
- Run `helm init --canary-image` to install the canary version of Tiller
- Use `helm` to install and upgrade your chart.

Given our testing, I am going to mark this closed with #1468. Please re-open if you can reproduce this on master or canary. Thanks for being patient as we've gone through this issue.

**Comment by wjkohnen** [comment]
Yet another fellow of @tback and @jayme-github checking in. Sorry the long delay. I've tried to reproduce and clarify our problems. 

- [x] We did not specify `.spec.selector.matchLabels` in our deployments, as that seemed to be redundant and volatile. This resulted in all kinds of weird behavior, because we use helm template variables in `.spec.template.metadata.labels`. As recommended I've tested with explicit selectors and as expected this solved any problem related to selectors. 

- [x] With release 2.1.3 we could try to upgrade with a poisoned deployment file, e.g. with `.spec.template.spec.foo: bar`. Although such deployments fail, the poisoned manifest would still be committed into a new release history config map, which in turn makes it impossible to upgrade to a valid state. Rollback to a valid state and then upgrade forth does work.  Release 2.2.0 (actually tested with master f4b7eb5b0148d9a1eb80877652496e725f369643) seems to solve this, as no failed upgrade is commited into a history config map. In our view this is/was a straight bug, and we'd appreciate a confirmation that this is solved for good. 

- [ ] We still can reproduce stale environment variables as mentioned in 1. of https://github.com/kubernetes/helm/issues/1844#issuecomment-274112471. When we manually add, change, delete (`kubectl edit deployment`) environment variables, we had expected a chart upgrade to revert any of these changes so as to reflect the state that is expressed in the chart. Any deviance from the expressed state of a chart in our view degrades the idempotency of helm releases and thus the idea of k8s clusters to be "self-healing". After spending some time tackling these issues I have some intuition that this desired behavior is (currently) not feasible. We'd appreciate some clarification.

**Comment by skevy** [comment]
Just wanted to add to this issue, specifically around the last bullet point from @wjkohnen.

What just happened to me was:

- I made a bad deployment, with bad environment variables (passed as values) in one of the containers in my pod
- Manually rolled back using `kubectl rollout undo`
- Fixed the issue, committed the code, and sent it back through our CI/CD
- Deployment failed, as it was still using old values. However, when I look at the release (by running helm get [release name]) I can confirm that the deployment manifest is correct. But that manifest does not match the manifest that exists when I do `kubectl get -o yaml deployment [deployment name]`

**Comment by atombender** [comment]
I haven't read all the comments, but it sounds like something we are seeing this with 2.3.0.

The deployment itself doesn't need to fail; we get this if some pods fail with `ImagePullBackoff` and we then try to do another deployment right away. In our case, the problem is that a _single annotation_ isn't applied during the upgrade. So here's what start with:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deploy.t11e.com/deploy-timestamp: 2017-05-04T16:14:03-04:00
    deploy.t11e.com/git-branch: ""
    deploy.t11e.com/git-revision: 6aef1ae79cb3c6b73fa7155190edee95a45b2f48
```

Then we try to do another deploy with new annotations:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deploy.t11e.com/deploy-timestamp: 2017-05-04T16:14:50-04:00
    deploy.t11e.com/git-branch: something
    deploy.t11e.com/git-revision: c5543256cd346f72e672b960828c760ef10cdfa9
```

But what we actually get is:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deploy.t11e.com/deploy-timestamp: 2017-05-04T16:14:50-04:00
    deploy.t11e.com/git-branch: ""
    deploy.t11e.com/git-revision: c5543256cd346f72e672b960828c760ef10cdfa9
```

Notice the annotation `deploy.t11e.com/git-branch` still has the old value. All the other values have been correctly updated, but weirdly enough it's always the one annotation that is not updated.

Could it be about the merge patch that Helm creates? Unfortunately it's not logging what it's patching, or we could debug it that way.
