### ISSUE TITLE
Dependency update command does not delete previous versions

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1864]
Hi,

I have run into an usability issue in which Helm was instantiating a dependent chart that I thought I had already updated.

Let's say I have a chart with two dependencies:

```yaml
$ cat requirements.yaml 

dependencies:
  - name: mariadb
    version: 0.5.x
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 0.4.x
    repository: https://kubernetes-charts.storage.googleapis.com/
```

Resolving:

```yaml
$ cat requirements.lock 
dependencies:
- name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.5.5
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.4.2
digest: sha256:a568b70bc50c9d83d39d8414ded20943124988afa6faf5e591b581858d002335
generated: 2017-01-24T16:57:02.467414576-08:00
```

Then I update my dependencies by doing `helm dependency update` and getting a new version of the MariaDB chart.

```bash
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   requirements.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        charts/mariadb-0.5.6.tgz
```

The issue is that the updater has not removed my previous version of the MariaDB chart and so it gets instantiated. 

```bash
ls charts/
mariadb-0.5.5.tgz  mariadb-0.5.6.tgz  redis-0.4.2.tgz
```

I am wondering if we should make the `helm dependency update` command delete previous/outdated charts in the same way `bundler` does in a vendorized directory.

I know that this is not a problem if I do not "vendor/cache" the charts under the `charts` directory but I am doing it this way so I reduce networking dependencies in our CI/CD pipelines.  

Regards,
Miguel
