### ISSUE TITLE
Release.Revision is empty :(

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes/helm#1944]
Utilizing the built-in `Release.Revision` for a label causes an empty label ;(

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}
  labels:
    helm_release_name: "{{.Release.Name}}"
    chart_name: "{{.Chart.Name}}"
    chart_version: "{{.Chart.Version}}"
    k8s_namespace: "{{.Release.Namespace}}"
    helm_revision: "{{.Release.Revision}}"
..snip..
```

Yields:

```
  labels:
    chart_name: herpderpcakesaredelicious
    chart_version: '0.1'
    helm_release_name: wise-wolverine
    helm_revision: ''
    k8s_namespace: thederpherps
```
