### ISSUE TITLE
helm test: add lint rule for incorrect helm test hook types

### ISSUE THREAD

**Issue by vdice** [kubernetes/helm#1960]
When I purposely supply an incorrect/unsupported test hook, I'd expect to see a subsequent `helm test` invocation supply an error specific to this situation.

Changing the `docs/examples/nginx/templates/service-test.yaml` to the following:
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-service-test"
  annotations:
    "helm.sh/hook": test-pass
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: ['curl']
      args:  [ '{{ template "fullname" .}}:{{default 80 .Values.httpPort}}' ]
  restartPolicy: Never
```

(Only test hooks supported as of this writing are `test-success` and `test-failure`, as seen [here](https://github.com/kubernetes/helm/blob/5d909d8c30f0ef22814d893863537634caee75f4/pkg/hooks/hooks.go#L38-L39))

After example chart install:
```
$ bin/helm test needled-starfish
Error: no tests found
```
