### ISSUE TITLE
Add deprecated field to chart metadata (Chart.yaml)

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1963]
We want to be able to add metadata in the chart that can be used to determine whether a particular chart is deprecated or not. This metadata should live in the Chart.yaml file, such as:

```
name: my-chart
version: 0.1.0
description: My deprecated chart
deprecated: true
```

The field should be optional, and default value `false` so that non-deprecated charts can simply omit the field.

One issue with this approach is that the Chart.yaml is tied to a specific version of the chart, and so there may be some confusion over whether just a particular version of the chart is deprecated, or all versions are. In my opinion, we need to make it clear that this field indicates that all versions of the chart are deprecated. For greater flexibility, we could say that if the latest version of a chart is marked as deprecated, then the whole chart is deprecated (the index is ordered, so you just need to look at the first entry for a particular chart). This would give us the ability to later un-deprecate a chart, by simply publishing a new version without the field.

With this field, the approach we will follow in the kubernetes/charts repositories to deprecate a chart will be to submit a PR that:
- updates the Chart.yaml to add the deprecated field
- add a notice at the top of the README
- add a notice in NOTES.txt

The human-readable notices will allow us to briefly explain why a chart was deprecated, and possibly point to a replacement.

After merging, we should follow up with a PR that removes the directory from the git repository.

cc @migmartri @viglesiasce @mgoodness @lachie83 @technosophos

**Comment by technosophos** [comment]
Should `helm install/upgrade` issue a warning if a user installs a deprecated chart?

**Comment by prydonius** [comment]
I think that would be great, and may even drop the need for adding a notice in NOTES.txt.

**Comment by technosophos** [comment]
@prydonius I was starting to work on this today, and had one other quick idea for you:

Would it be easier for you if we implemented it like this: What if we made it possible to specify whether the deprecation was for this version _only_, or if it marked the deprecation of the chart in its entirety?

### Mark one version deprecated:

```yaml
deprecated: version # This _particular version_ is deprecated.
```

This implies that this one particular version should not be used (e.g. for security reasons). ONLY chart versions that were considered "broken" would use this flag.

### Mark the entire chart deprecated:

```yaml
deprecated: chart # The chart is now marked deprecated.
```

/cc @migmartri @jackfrancis

**Comment by jackfrancis** [comment]
My thoughts:

- I think there is real value in being able to express version-specific deprecation (your general security example is on point).
- The current implementation for expressing common attributes of a chart (common across all versions, that is), e.g., `name`, is an implicit contract between chart repo consumer and provider that those property values will be the same for all chart versions. Is that correct?

An example of point 2 above is the `name` value in these two chart version entries:

```
  - apiVersion: v1
    created: 2017-03-02T19:33:28.166146825Z
    description: Scales worker nodes within autoscaling groups.
    digest: 291eaabbf54913e71cda39d42a6e9c4c493a3672a5b0b5183ea1991a76d6c317
    engine: gotpl
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    maintainers:
    - email: mgoodness@gmail.com
      name: Michael Goodness
    name: aws-cluster-autoscaler
    sources:
    - https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws
    urls:
    - https://kubernetes-charts.storage.googleapis.com/aws-cluster-autoscaler-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    created: 2017-03-02T18:48:30.418071154Z
    description: Scales worker nodes within autoscaling groups.
    digest: 52ee58b51619f641d0f6df4c778bcd068242379a1a040a269f0fc93867b79b13
    engine: gotpl
    maintainers:
    - email: mgoodness@gmail.com
      name: Michael Goodness
    name: aws-cluster-autoscaler
    sources:
    - https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws
    urls:
    - https://kubernetes-charts.storage.googleapis.com/aws-cluster-autoscaler-0.2.0.tgz
    version: 0.2.0
```

If my thinking is correct, then I think we can continue this implicit representation thusly:

- we mark deprecated chart versions with a boolean `deprecated: true` property representation
- a chart repo consumer marks an entire chart as being deprecated (implementation TBD) when it detects that all versions of a chart are marked as `deprecated: true`
