### ISSUE TITLE
Can't remove keys defined in values.yml

### ISSUE THREAD

**Issue by jagregory** [kubernetes/helm#1966]
Since the introduction of deep merging (#1620), it's now not possible to remove keys from `values.yml` entirely.

For example, the [telegraf values](https://github.com/kubernetes/charts/blob/master/stable/telegraf/values.yaml) has a default entry for `single.config.inputs.influxdb` (see: [L340](https://github.com/kubernetes/charts/blob/master/stable/telegraf/values.yaml#L340)). There's no way to completely remove this key through `--set` or a override file.

**Telegraf values.yml**

```yml
single:
  config:
    inputs:
      influxdb:
        urls:
          - "http://influxdb-influxdb.tick:8086/debug/vars"
        timeout: "5s"
```

**My telegraf-overrides.yml**

```yaml
single:
  config:
    inputs:
      influxdb: null # or something?
```
