### ISSUE TITLE
--recreate-pods tag and statefulsets upgrade

### ISSUE THREAD

**Issue by eduardobaitello** [kubernetes/helm#1971]
The `--recreate-pods` tag is supposed to recreate the pods of statefulsets?

I'm trying to update a statefulset with a NEWCHART, which describes a new image for my statefulset. The only difference with the deployed release is the new image and the chart version.
I run `helm upgrade RELEASE NEWCHART --recreate-pods`, which upgrades my statefulset, but their pod still uses the old image.
If I manually delete the pod, it's recreated with the new image, but I want this done automatically in `helm upgrade` command. It's possible?

_helm version: 2.2.0
kubernetes version: 1.5.1_

**Comment by technosophos** [comment]
Yeah, we need to cover this in the docs

**Comment by nmakhotkin** [comment]
@eduardobaitello By kubernetes convention, pods need to be created with specific labels and selectors. Later they should be referenced by those selectors. See more at https://kubernetes.io/docs/user-guide/labels/

**Comment by nmakhotkin** [comment]
@eduardobaitello may be it should be done more accurate than how it is done now. I mean the selecting right pods for restart/recreate.

**Comment by eduardobaitello** [comment]
@nmakhotkin, thanks for reply.

I'm using a chart with a .yaml file that describes a _nginx-slim:0.7_ image for my statefulset (created with `helm install`)
Then I run a `helm upgrade --recreate-pods`  with another chart version that have a .yaml file with _nginx-slim:0.8_ image defined.

The defined selector is like this, but the pod is not deleted in the upgrade process:
```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.7
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: "storage-nginx"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
```

Am I missing something?
