### ISSUE TITLE
[Feature Request] Local global variable support

### ISSUE THREAD

**Issue by nstires** [kubernetes/helm#1983]
Perhaps this solution already exists, and I've been unable to bring it to light. My attempts have thus far been in vain. What I have is a custom application that I'm deploying to k8s via Helm. This application is primarily deployed to a custom namespace, and hosts a number of dependencies. Both the application and the dependencies have variables that should support local overrides. I've been unable to pass these local variables to the depdency charts. Here's my current setup...

someproj/templates/proj.yaml:  
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    version: {{default "master-latest" .Values.proj_version}}
    tier: proj-frontend
  name: proj-lb
  namespace: {{default "default" .Values.global.namespace}}
spec:
  type: LoadBalancer
  selector:
    tier: proj-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proj-deployment
  namespace: {{default "default" .Values.global.namespace}}
spec:
  replicas: 2
  template:
    metadata:
      namespace: {{default "default" .Values.global.namespace}}
      labels:
        tier: proj-backend
    spec:
      restartPolicy: Always
      imagePullSecrets:
          - name: myprojkey
      containers:
        - name: some-proj
          env:
            - name: profile
              value: redis-sentinel
            - name: sentinelHost
              value: redis-sentinel.{{default "default" .Values.global.namespace}}.svc.cluster.local
            - name: sentinelPort
              value: '26379'
            - name: consul
              value: consul.{{default "default" .Values.global.namespace}}.svc.cluster.local
            - name: logstashHost
              value: logstash-service.{{default "default" .Values.global.namespace}}.svc.cluster.local:4560
          image: index.docker.io/localorg/some-proj:{{default "master-latest" .Values.proj_version}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8443
          securityContext:
            privileged: false
          readinessProbe:
            httpGet:
              path: /some/manage/health
              port: 8080
            initialDelaySprojonds: 10
            timeoutSprojonds: 1
```

someproj/charts/redis-master/templates/redis-master.yaml:  
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: {{default "default" .Values.global.namespace}}
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: kubernetes/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: {{default "0.1" .Values.global.redis_master_cpu}}
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: kubernetes/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}
```

myvals.yaml:  
```yaml
global:
  namespace: "nick"
  redis_master_cpu: "0.5"
```

helm lint someproj:  
```
==> Linting someproj
[ERROR] templates/: render error in "someproj/templates/proj.yaml": template: someproj/templates/proj.yaml:8:40: executing "someproj/templates/proj.yaml" at <.Values.global.names...>: can't evaluate field namespace in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed
```

someproj/values.yaml:  
(empty)

Execution ala:  
```bash
helm install --values=myvals.yaml someproj
```

It seems this is the result of the inability of the local global variables to be passed. As far as I can tell, only top-level charts can support local variables. Assuming this is correct, what interest is there in a new feature for this?

**Comment by technosophos** [comment]
- Local variables can only be passed downward from a parent chart to a subchart.
- Global variables are available to all charts (always at `.Values.global.NAME`), and the precedence order is top-down (in the order --set, -f, parent values.yaml, subchart values.yaml)

By design, there is no way for a child chart to override values in a parent chart, as this would open up some frustrating edge cases. For example, it would make it dangerous to rely on any subchart that you yourself didn't maintain.

There are a few issues in the issue queue about ways to allow a parent chart to explicitly declare that it wants to get some of the values from a subchart. This one looks most promising right now:

https://github.com/kubernetes/helm/issues/1883

Does that help at all?

**Comment by nstires** [comment]
Yes, I am passing them down. The local variables file (myvals.yaml) is attempting to provide the global variables, which are called in the `--values=myvals.yaml`.

The issue seems to be that you can't identify global variables, at any level, without having them embedded in the chart's (or parent chart's) variable definition file. The local global variables aren't being called.

**Comment by technosophos** [comment]
If you run `helm install --dry-run --debug` on your chart (above), what do you see in the Values section? It should show you the result of the merged values.

**Comment by technosophos** [comment]
Example:
```
⇒  helm install --dry-run --debug --set global.foo=bar ./docs/examples/alpine
SERVER: "localhost:44134"
CHART PATH: /Users/mattbutcher/Code/Go/src/k8s.io/helm/docs/examples/alpine
NAME:   honking-wolf
REVISION: 1
RELEASED: Thu Feb 16 16:41:15 2017
CHART: alpine-0.1.0
USER-SUPPLIED VALUES:
global:
  foo: bar

COMPUTED VALUES:
Name: my-alpine
global:
  foo: bar

HOOKS:
MANIFEST:

---
# Source: alpine/templates/alpine-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "honking-wolf-my-alpine"
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: "honking-wolf"
    # This makes it easy to audit chart usage.
    chart: "alpine-0.1.0"
  annotations:
    "helm.sh/created": "1487288475"
spec:
  # This shows how to use a simple value. This will look for a passed-in value
  # called restartPolicy. If it is not found, it will use the default value.
  # Never is a slightly optimized version of the
  # more conventional syntax: Never
  restartPolicy: Never
  containers:
  - name: waiter
    image: "alpine:3.3"
    command: ["/bin/sleep","9000"]
```

The Computed Values section should show you what your top-level chart has access to.
