### ISSUE TITLE
[Proposal]support aliases of repo names in requirements.yaml

### ISSUE THREAD

**Issue by qwangrepos** [kubernetes/helm#1985]
## Use case
If a repository has been added to the repository index with its repo name and URL, and the following command "helm repo list" outputs the mapping from the repo name to the repo URL, the full repository URL given in requirements.yaml should be able to be replaced with its repo name as an alias. The use of repo name as an alias will be a more effective and perceptive way to represent the full URL.

## Specification
If the command "helm repo list" has outputs include the following mapping:
```
NAME  	URL                                              
stable	https://kubernetes-charts.storage.googleapis.com/
```
The syntax of using a repo alias in requirments.yaml will be like this.
```
dependencies:
- name: mariadb
  version: 0.5.x
  repository: alias:stable
```
or like this.
```
dependencies:
- name: mariadb
  version: 0.5.x
  repository: @stable
```

Both "alias:" and "\@" will be recognized as an alias representation of a repository. 
When helm client loads the requirement.yaml, it will firstly examine the existence of the repo name and repo URL in the index file. If the repo name does not exist, an error will be raised to report unrecognized alias.
