### ISSUE TITLE
install and lint chokes on escaped double quotes

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#1994]
# Summary

YAML officially supports `\"` within double-quoted string values, but Helm actually chokes when presented with one.

# Steps to reproduce error

In a `deployment.yaml`, present a string value that contains escaped double quotes.

```yaml
someKey: "This string has some \"double-quoted\" text."
```

Then `helm install --debug --dry-run`... This reports no warnings or errors, and produces valid YAML output according to the YAML spec.

http://yaml.org/spec/1.2/spec.html#id2776092

However, both `helm lint` and `helm install` (no --dry-run) complain:

```console
[ERROR] deployment.yaml: unable to parse YAML
        error converting YAML to JSON: yaml: line XY: did not find expected key
```

# System

```console
$ helm version
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
```

Could there be a glitch in the YAML parser used by Helm here?

I can't reproduce the error using just the github.com/ghodss/yaml parser, so I'm not sure which part of the system is failing on escape codes.

**Comment by technosophos** [comment]
Can you upgrade your client to 2.2.0 and retry?

**Comment by technosophos** [comment]
I can definitely reproduce the case where I pass in a quoted string in `values.yaml` and it gets decoded and loses its escaping.

values.yaml
```yaml
example: "The sign said \"No Tresppassing\""
```

templates/deployments.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    foo: {{.Values.example}}
# ...
```

And when I run `--dry-run --debug` I see this:

```yaml
# Source: i1994/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lopsided-giraffe-i1994
  labels:
    chart: "i1994-0.1.0"
  annotations:
    foo: The sign said "No Trespassing"
```

But the above is not valid YAML. You would need to fix the template to either quote/escape the value or use YAML heredoc syntax:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    foo: |
      {{.Values.example}}
```

**Comment by jascott1** [comment]
@mcandre Closing due to inactivity but please re-open if necessary.

**Comment by mcandre** [comment]
Please don't close a critical YAML parsing bug due to inactivity. If you can demonstrate a unit or integration test file for this, or point out a commit that fixes this, then let us know.

**Comment by bacongobbler** [comment]
You should be able to use the `quote` function to escape strings in templates. The syntax is `{{ quote .Values.example }}` in @technosophos's example to properly escape the string. This has been in helm for a few months now. Sorry for not coming back to this ticket!

**Comment by bacongobbler** [comment]
related docs: https://docs.helm.sh/chart_template_guide/#template-functions-and-pipelines

**Comment by OndraZizka** [comment]
So how should I use `quote` here:

    command: ["sh", "-c", "mvn -B gatling:test -pl csa-testing -DCSA_SERVER={{ template \"project.fullname\" . }} -DCSA_PORT={{ .Values.service.appPort }}"]

That produces

    [ERROR] templates/: parse error in "collab-services-api/templates/tests/test.yaml": template: collab-services-api/templates/tests/test.yaml:11: unexpected "\\" in template clause

**Comment by rbuck** [comment]
I agree and observe this still as a bug, and the quote function in helm does not address it at all. The ticket should not have been closed. If there is a workaround, please indicate the solutions.

**Comment by franpog859** [comment]
I read [the docs](https://helm.sh/docs/chart_template_guide/#template-functions-and-pipelines) and I still don't know how to fix this example:

```yaml
spec:
  rules:
    - services: ["{{ template \"fullname\" . }}.namespace.svc.cluster.local"]
      paths: ["*"]
      methods: ["*"]
```

I get this error:

```
Error: parse error in "some.yaml": template: some.yaml:123: unexpected "\\" in template clause
```

Could you please help me?

**Comment by bd05** [comment]
@franpog859 
I had that error at work the other day. Managed to get around it by using single quotes as the outer quotes - that way, you can use the double quotes around "fullname" without having to escape them. Like this:
```
spec:
  rules:
    - services: ['{{ template "fullname" . }}.namespace.svc.cluster.local']
      paths: ["*"]
      methods: ["*"]
```
