### ISSUE TITLE
proposal: allow import of child values via optional requirements field 'import-values'

### ISSUE THREAD

**Issue by jascott1** [kubernetes/helm#1995]
# Problem

When working on complicated nested charts developers would like to create 'library charts' that contain common values that need to be accessible from the parent chart but there is no mechanism to do this. Developers resort to workarounds such as build scripts that merge values files which add more steps and are not helm native.

# Proposed Solution

Allow the import of a child's values to parent values by adding a `imports-values:` field in requirements.yaml as in the example below

```
# requirements.yaml (simple list)
dependencies:
  - name: kolla-common
    repository: http://localhost:10191
    version: 0.1.0
    import-values:
      - foo.thing
```

The above would instruct helm to take the values found at path "foo.thing" in sub-chart "kolla-common" and place them at the root of the top parent's values. So that given a parent values of 

````
# parent values
mything: yay
````

and child values
````
# child values
foo:
  thing:
    bar: true
    baz: false
    other:
      - 1
      - 2
      - 3
````

The resulting parent values would be 

````
# result parent values
mything: yay
bar: true
baz: false
  other:
    - 1
    - 2
    - 3
````

## Advanced usage

Additionally the `import-values:` field would support a child/parent dictionary value that would allow reparenting the imported values into a specific path in the parent values as in the example below:

````
# requirements (child/parent)
...
import-values:
  - child: foo.thing
    parent: new.key
````

In the above example, the values from the child path are placed at the specified location 'new.key' in the parent values as below:

````
# result values
mything: yay
new:
  key:
    bar: true
    baz: false
    other:
      - 1
      - 2
      - 3
````

## Non-existent import values

If a `import-values` field contains child paths that do not exist, a warning will be issued.

## Mixed string and child/parent

Mixing the simple list of strings and child/parent dictionaries is supported and the below would be valid:

````
# requirements.yaml
...
import-values:
  - common
  - child: foo.thing
    parent: new.key
````

## Exports key convention

To facilitate the introspection of values intended to be consumed by a parent, it is suggested to follow a `exports:` key convention wherein those values are all contained in field named `exports:` as below:

````
# child/values.yaml

exports:
  foo: true
  bar: false
baz:
  pike: true
....
````

By following the above convention, tools will be able to better inspect and when necessary exclude the values intended for parent. Users that need the flexibility to ignore the convention are allowed to do so with the caveat that future analysis involving values intended for parent may be difficult or impossible.

## Importing from Child to Parent to GrandParent

By using the imports-values mechanism at each level in the hierarchy, values can be imported from a child chart to its parent and then imported into the grandparent (and so on). 

````
# parent requirements
imports-values:
  - child: data.foo
    parent: imported-from-child

# grandparent requirements
import-values:
  - child: imported-from-child
    parent: imported-from-child-via-parent


````

**Comment by kfox1111** [comment]
Also, this should suggest a convention that child charts place stuff under the "parent" section. The parent section can then be automatically excluded nicely when used by chart introspection tools.

**Comment by redbaron** [comment]
what would be example of data passed this way in real-life?

**Comment by kfox1111** [comment]
ok. so maybe a more concrete example would help. in kolla kubernetes, we would use this feature like so I think:

in kolla-common/values.yaml, we would have something like:
```yaml
parent:
    common:
        global:
            kolla:
                all:
                    docker_registry: docker.io
                    docker_namespace: kolla
                    base_distro: centos
                    install_type: binary
                    container_config_directory: /var/lib/kolla/config_files
                    image_tag: 2.0.2
                    fluentd_image_tag: 3.0.2
                    kolla_toolbox_image_tag: 3.0.2
                    kubernetes_entrypoint_image_tag: 4.0.0
                    selector_key: kolla_controller
                    selector_value: "true"
                    image_pull_policy: IfNotPresent
                    container_config_directory: /var/lib/kolla/config_files
                    kubernetes_entrypoint: false
                    kube_logger: true
    mariadb-connection:
        global:
            kolla:
                all:
                    database_host: mariadb
                    database_port: 3306
    keystone-admin:
        global:
            kolla:
                all:
                    keystone_admin_protocol: http
                    keystone_admin_svcname: keystone-admin
                    keystone_admin_port: 35357
                    keystone_admin_project: admin
                    keystone_admin_username: admin
                    keystone_admin_domain_name: Default
                    region: RegionOne
```

Then in chart: neutron-create-db-job
its requirements.yaml would have:
```yaml
dependencies:
  - name: kolla-common
    repository: file://../../kolla-common
    version: 0.5.0-1
    include-values:
      - common
      - mariadb-connection
```

and then it sould behave the same way as if the following was in neutron-create-db-job values.yaml.
```yaml
global:
    kolla:
        all:
            docker_registry: docker.io
            docker_namespace: kolla
            base_distro: centos
            install_type: binary
            container_config_directory: /var/lib/kolla/config_files
            image_tag: 2.0.2
            fluentd_image_tag: 3.0.2
            kolla_toolbox_image_tag: 3.0.2
            kubernetes_entrypoint_image_tag: 4.0.0
            selector_key: kolla_controller
            selector_value: "true"
            image_pull_policy: IfNotPresent
            container_config_directory: /var/lib/kolla/config_files
            kube_logger: true
            database_host: mariadb
            database_port: 3306
```
