### ISSUE TITLE
requirements.lock is out of sync with requirements.yaml

### ISSUE THREAD

**Issue by jayme-github** [kubernetes/helm#2033]
Starting with v2.2.0 `helm dependency build <CHART>`  returns `requirements.lock is out of sync with requirements.yaml` for the following combination:

requirements.yaml
```yaml
dependencies:
  - name: redis
    version: 0.1.2
    repository: http://helm-charts.repo:8800/
```

requirements.lock
```yaml
dependencies:
- name: redis
  repository: http://helm-charts.repo:8800/
  version: 0.1.2
digest: sha256:9368f83e1905e68711021f8e3ef2190cb4b039d8a084fff67e8fc6948fa669f9
generated: 2016-12-06T12:10:39.373863968+01:00
```

helm v2.1.3 is okay with those files. `--debug` does not print any details.
