### ISSUE TITLE
inconsistent template rendering when overriding blocks

### ISSUE THREAD

**Issue by shamil** [kubernetes/helm#2052]
Hi,

I'm not sure if that a limitation of `helm`/`gotemplate` or I'm doing something wrong.

When I have a named template (`_config.tpl`)

```yaml
{{/* Config template */}}
{{- define "config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  key1: {{ block "key1" . }}default{{ end }}
  key2: {{ block "key2" . }}default{{ end }}
{{- end }}
```

and I want to create 2 resource templates based on the **named** template

`config1.yaml`

```yaml
{{- include "config" . }}
```

`config2.yaml`

```yaml
{{- define "key1" }}overridden{{ end }}
{{- define "key2" }}overridden{{ end }}
{{- include "config" . }}
```

I would expect that the first template will have the `block` defaults and the second will contain values from overridden `block`s. But instead I get the values from overridden `block`s in both templates, here is the result

```
Created tunnel using local port: '35787'
SERVER: "localhost:35787"
CHART PATH: /tmp/charts/test
NAME:   plinking-jaguar
REVISION: 1
RELEASED: Thu Mar  2 13:40:24 2017
CHART: test-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
{}

HOOKS:
MANIFEST:

---
# Source: test/templates/config1.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  key1: overridden <=== [THIS SHOULD BE "default"]
  key2: overridden <=== [THIS SHOULD BE "default"]

---
# Source: test/templates/config2.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  key1: overridden
  key2: overridden
```

What I'm doing wrong, is this even a proper way doing such overrides?
