### ISSUE TITLE
Allow to override global variables per-subchart

### ISSUE THREAD

**Issue by sheerun** [kubernetes/helm#2076]
In my usecase I'd like to enable persistence for all subcharts, except redis. Ideally I'd be able to write:

```yaml
title: "My Awesome App"

global:
  persistence: true # received by all subcharts

redis:
  global:
    persistence: false # override global.persistence of redis subchart
  port: 9090
```

what do you think? sorry if it's already possible, I cannot find documentation..
