### ISSUE TITLE
PROPOSAL: pluggable downloader and manager package for non-http chart repository plugins

### ISSUE THREAD

**Issue by libesz** [kubernetes/helm#2093]
# Proposal: pluggable downloader and manager package for non-http chart repository plugins
The background of this proposal can be found [here](https://github.com/kubernetes/helm/issues/1038#issuecomment-268068410).

### Use-case
Open up helm core packages to be reusable in plugins and 3rd party client implementations which uses non-http backends to store charts.

To not expand the repositories.yaml file schema further, the alternative clients would have special non-http url-s in the repositories.yaml, which would be ignored (if used) by the default helm commands (e.g. helm repo update).

For example if someone wants to store the charts in some relational DB to have a silly example, he could implement it behind an interface and set a repository in the repositories.yaml like: mydbtype://user:pass@example.com/charts. Naturally the plugin may get credentials on another way to not store them in plaintext (from its own commandline, interactively from the user, from keyring, etc.).

### Description of the PoC code:
To be able to support this, a new package, called getter would be introduced. It defines an interface with the new Get function (based on the original repo.Getter.Get() function) which all the getters must implement. The repo.NewChartRepository() has been extracted and the original construction of the http(s) based client is now became the only-one built-in getter implementation. When calling it from now, you have to provide the set of your getter constructors with the list of url schemes which they can handle.
There is a default collection of getters (with the only-one http getter in it for now) to use in the core helm commands to pass to the repo.NewChartRepository().
This interface enables alternative clients to implement further backend protocols and use their getters with the Manager and ChartDownloader packages in a flexible way.

Later on even the core helm code may get further common getters as default if desired.

### PR and usage
I have the PoC code in PR to let you review it and a sample code [here](https://gist.github.com/libesz/7b0e88f5798e832ba119e163b6cf5444) which can handle OpenStack Swift Object Store kind of repositories based on the proposed solution.

**Comment by technosophos** [comment]
This is a good idea.

I was trying to come up with a way of doing it that would make it easier to write this sort of plugin in any language, not just Go. I'll dump my half-baked idea here and see if it sparks any additional insights.

So I was wondering if we could extend the `plugin.yaml` file to be able to declare a downloader. The current plugin looks like this:

```yaml
name: "hello"
version: "0.1.0"
usage: "Say hello"
description: |-
  This is a demonstration plugin that prints Hello and then exists.
command: "$HELM_PLUGIN_DIR/helm-hello"
```

What if we added a section that did something like this?

```
name: "hello"
#...
command: "$HELM_PLUGIN_DIR/helm-hello"
# New part:
downloaders:
  - protocol: "mydbtype"
    command: "$HELM_PLUGIN_DIR/some-command"
  - protocol: swift
    command: "$HELM_PLUGIN_DIR/some-other-command"
```

(We might need new fields, too... I haven't thought about this too much)

During a regular Helm startup, we read all the plugin definitions. So we could just take basically the approach you were taking, but have Helm drop to shell to execute the plugin for the matching protocol.

Advantages:

- Easy to write downloaders in other programs (or even just wrap existing clients)
- If we implemented this well, it could serve as the basis for other interceptor-style plugins (like adding custom linting rules!)

Disadvantages:

- Dropping to shell mid-program is always a fun experience.

Anyway... just a rough thought. I'm excited to make progress on plugins.

Thanks!

**Comment by libesz** [comment]
I think I got it. So the downloader plugin would be invoked whenever it is needed by any helm logic? It means basically all the places where the getter.Get() method is called in the current PoC code. This way all the helm commands would work with any downloader ootb.

What do you mean by dropping to shell? Isn't it so that the downloader plugins would need only to follow a command line arg semantics and they would be called with exec.Command() and Run()?

**Comment by libesz** [comment]
I implemented the change in a way that when built-in getters are requested, it reads all the plugin downloaders' as well.
Currently the content is expected to the plugin's stdout. Dumb example for swift [here](https://gist.github.com/libesz/6d8b35114df768b4c104ea161f39837d).
It works with a plugin configuration like this:
```
name: "downloader"
[...]
downloaders:
  - protocols:
    - "swift"
    command: "[...]/.helm/plugins/swift/main"
```
Hope that it is something similar what you described :)
