### ISSUE TITLE
Orphan replica set after upgrade with a different app selector value

### ISSUE THREAD

**Issue by gerardo8a** [kubernetes/helm#2096]
Don't know if this is a helm bug, kubernetes, please advice

This happens when upgrading an existing deployment with the "same REALEASE name" but the app selector used by the deployment is not the same.

My application gets deployed using an existing chart and I passing the -f option to override some fields, one of these fields is the app selector on the deployment.yaml template

```
ex.
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applabel }}
```

If for any reason I decide to change the app selector when upgrading an existing release I will end up with two replica sets of the same deployment but one of them being a left over from previous deployment. Looks like there is not proper clean up when the selector changes.
