### ISSUE TITLE
Proposal: Should tiller proceed with an install/upgrade if a hook fails?

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#2130]
## Current Problem
If you have a `pre-install/pre-upgrade` hook that fails the installation will continue. This could cause issues for an application that expected a database migration to happen before the code was deployed.

## Proposal
When you provide a `pre hook` as part of a chart you can specify whether that hook is required to succeed before proceeding with the `install/upgrade`

**Comment by philipbjorge** [comment]
For our usecase (database migrations), simply waiting for the JobComplete *and* Succeeded==Completions would be sufficient.

**Comment by philipbjorge** [comment]
@technosophos and @jchauncey --
We are attempting to use a pre-install/pre-upgrade hook to perform a database migration. 
We would like the release to fail if the job cannot complete successfully.

When I attempt to upgrade an installation with a failing hook, I get a timeout from Helm and see in the tiller logs the following:
```
2017/06/23 00:24:03 client.go:699: old-helm-success-nginx: Jobs active: 1, jobs failed: 10, jobs succeeded: 0
2017/06/23 00:24:05 release_server.go:959: warning: Release "old-helm-success" pre-upgrade nginx/templates/pre-upgrade-job.yaml could not complete: timed out waiting for the condition
```

So it *seems* like the problem described in the issue does not exist today.
Am I wrong? What am I missing?

Example Successful Job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{template "fullname" . }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    metadata:
      name: "{{template "fullname" . }}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade-job
        image: "alpine:3.3"
        command: ["ls", "/"]
```

Example Failing Job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{template "fullname" . }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    metadata:
      name: "{{template "fullname" . }}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade-job
        image: "alpine:3.3"
        command: ["ls", "/FAILFAILFAIL"]
```
