### ISSUE TITLE
tiller crashes on 'helm test' run when there's blank line in test pod yaml

### ISSUE THREAD

**Issue by robertchoi8099** [kubernetes/helm#2158]
When there's a blank line at the top of the test pod yaml template, tiller crashes on 'helm test' run.

Here's the problomatic (and rendered) yaml file:
```
(blank line)
---
apiVersion: v1
kind: Pod
metadata:
  name: "keystone-tempest-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
...
```
If I run 'helm test' command, the following error is shown.
```
root@att-helm:~/workspace/openstack-helm# helm test keystone
Error: transport is closing
root@att-helm:~/workspace/openstack-helm# helm test keystone
Error: could not find a ready tiller pod
```
The tiller pod log says:
```
root@att-helm:~# kubectl logs tiller-deploy-3210613906-djz5c -n kube-system
Starting Tiller v2.2.3
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
2017/03/22 07:22:15 storage.go:133: Getting release history for 'keystone'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd44c8a]

goroutine 46 [running]:
panic(0x156c840, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/releasetesting.newTest(0xc42044b400, 0x0, 0x4110f8, 0x40, 0x161d1e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:174 +0x11a
k8s.io/helm/pkg/releasetesting.(*TestSuite).Run(0xc4203f9f40, 0xc420587b90, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:72 +0x9a
k8s.io/helm/pkg/tiller.(*ReleaseServer).RunReleaseTest(0xc42021ad00, 0xc42040b8a0, 0x1ff05c0, 0xc4204082e0, 0x0, 0x18)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:1100 +0x244
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_RunReleaseTest_Handler(0x16c8d20, 0xc42021ad00, 0x1fefcc0, 0xc420089440, 0xc4202becb8, 0x4110f8)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:928 +0x117
k8s.io/helm/pkg/tiller.newStreamInterceptor.func1(0x16c8d20, 0xc42021ad00, 0x1fefcc0, 0xc420089440, 0xc42040b840, 0x17e0aa0, 0xc4202d5400, 0x4111d8)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/server.go:63 +0x112
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0, 0xc42043a720, 0x2035960, 0xc42029ff20, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:723 +0x2b6
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0, 0xc42029ff20)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:800 +0xc36
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420408140, 0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

This issue only takes place with 'helm test' command. 
If I remove the '"helm.sh/hook": test-success' from the above yaml file so that the pod can be launched by 'helm install' command, it just worked fine without any error.

Test Environment
- Helm version: 2.2.3
- OS: Ubuntu 16.04

**Comment by thomastaylor312** [comment]
The PR that closed this shouldn't have. Reopening

**Comment by ahawkins** [comment]
I can confirm a similar issue on 2.3.1. My template does not have a blank line, but the result is still the same:

```
kviberg $ kubectl logs tiller-deploy-3299538222-pwsb6  -n kube-system
Starting Tiller v2.3.1 (tls=false)
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
2017/04/21 06:21:54 storage.go:133: Getting release history for 'test-efritin'
2017/04/21 06:21:54 client.go:748: Watching pod test-efritin-kviberg-efr-smoke-test for completion with timeout of 5m0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe6911a]

goroutine 36 [running]:
panic(0x1582f00, 0xc42000a030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/releasetesting.newTest(0xc420202000, 0x0, 0x0, 0x0, 0x1)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:174 +0x11a
k8s.io/helm/pkg/releasetesting.(*TestSuite).Run(0xc420210280, 0xc420ca9b90, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:72 +0x9a
k8s.io/helm/pkg/tiller.(*ReleaseServer).RunReleaseTest(0xc4202c0fa0, 0xc42027c520, 0x20106e0, 0xc4203cd670, 0x0, 0x18)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:1128 +0x244
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_RunReleaseTest_Handler(0x16e0640, 0xc4202c0fa0, 0x200fde0, 0xc420339ef0, 0xc4204644b8, 0x411d48)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:931 +0x117
k8s.io/helm/pkg/tiller.newStreamInterceptor.func1(0x16e0640, 0xc4202c0fa0, 0x200fde0, 0xc420339ef0, 0xc42027c4c0, 0x17f95d8, 0xc420025c00, 0x411e28)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/server.go:68 +0x112
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc42010b200, 0x2010860, 0xc420339e60, 0xc4200c9c20, 0xc420334d50, 0x2055ae0, 0xc4202cb920, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:723 +0x2b6
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42010b200, 0x2010860, 0xc420339e60, 0xc4200c9c20, 0xc4202cb920)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:800 +0xc36
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4203cd4a0, 0xc42010b200, 0x2010860, 0xc420339e60, 0xc4200c9c20)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

Output from `helm get`:

```
HOOKS:
---
# test-efritin-kviberg-efr-smoke-test
---
apiVersion: v1
kind: Pod
metadata:
  name: 'test-efritin-kviberg-efr-smoke-test'
  labels:
    chart: 'kviberg-efritin-0.1.0-beta.0-refactor-git-crypt.g245719c'
    app: smoke-test
    source: kviberg
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: "test-efritin-kviberg-efr-image-pull"
  containers:
    - name: "smoke-test"
      image: saltside/kviberg-smoke-test:245719c
      imagePullPolicy: IfNotPresent
      env:
        - name: CORE_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-core-service-thrift:9090
        - name: SEARCH_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-search-service-thrift:9090
        - name: REVIEW_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-review-service-thrift:9090
        - name: PAYMENT_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-payment-service-thrift:9090
        - name: INVENTORY_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-inventory-service-thrift:9090
        - name: SMS_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-sms-service-thrift:9090
        - name: OFFER_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-offer-service-thrift:9090
        - name: ADMIN_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-admin-service-thrift:9090
        - name: EMPLOYEE_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-auth-service-thrift:9090
        - name: AUTH_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-auth-service-thrift:9090
        - name: NOTIFICATION_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-notification-service-thrift:9090
        - name: EMAIL_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-email-service-thrift:9090
        - name: IMAGE_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-image-service-thrift:9090
        - name: SMS_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-sms-service-thrift:9090
        - name: CHAT_THRIFT_URL
          value: tcp://test-efritin-kviberg-efr-chat-service-thrift:9090
```
