### ISSUE TITLE
YAML parser quote handling

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes/helm#2164]
The Slack thread can be seen [here](https://kubernetes.slack.com/conversation/C0NH30761/p1490051533505404).

When using this in my `values.yaml`

```
labels:
  host_external_dns_enable: "true"
  cool_id: "test123"
  better_id: "test123"
  deploy_time: "2017-03-20T17:13:01Z"
  image: "herp:01234567"
```

And using the spiffy `{{ toYaml .Values.labels | indent 8 }}` function, I sadly get this back whilst doing a `--debug --dry-run`

```
      labels:
        deploy_time: 2017-03-20T17:13:01Z
        host_external_dns_enable: "true"
        image: herp:01234567
        cool_id: test123
        better_id: test123
```

In this case, I get an error about both the `deploy_time` and `image` values and the chart in unsuccessfully deployed.

```
Error: release herp failed: Deployment.extensions "derp" is invalid: [spec.selector.matchLabels: Invalid value: "2017-03-20T17:13:01Z": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'), spec.selector.matchLabels: Invalid value: "herp:01234567": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'),spec.selector: Invalid value: {"matchLabels":{"app":"derp","deploy_time":"2017-03-20T17:13:01Z","host_external_dns_enable":"true","image":"herp:01234567","better_id":"test123","cool_id":"test123"}}: invalid label selector.]

```

From @technosophos

>the YAML parser will try to simplify the data to its most basic format. So it will remove quotes around any >strings it thinks it can get away with.

My ask here is that we either make this handling configurable or just double quote everything (probably the better option).
