### ISSUE TITLE
Very weird occasionally `helm test` failure, when metadata.labels are provided

### ISSUE THREAD

**Issue by alonl** [kubernetes/helm#2227]
Hey,

I'm sorry in advance, but I have no way to explain it. 

We recently started using `helm test` functionality for some integration tests. Some of the tests were occasionally failed - from time to time. After isolating all the parameters, whether they're related or not, we finally discovered that a cause for that is including `metadata.labels` in the test Pod.

Example:

When I'm running `helm test` with the configuration below, around 10 out of 100 `helm test` runs fail.

`test.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Chart.Name }}-test"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: "{{ .Chart.Name }}-test"
      image: "{{ .Values.imageRegistry }}/{{ .Values.imageNamespace }}/{{ .Chart.Name }}-test:{{ .Values.imageTag }}"
      env:
      - name: TEST_SERVICE_URL
        value: "{{ .Values.test.testServiceUrl }}"
  restartPolicy: Never
```

When I remove this part
```
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
```
100% of the `helm test` runs succeed. 

By the way, the tests fail with `ECONNREFUSED`, using mocha in NodeJS.

I have no clue, but maybe someone else has encountered that?

**Comment by thomastaylor312** [comment]
@michelleN any ideas here?

**Comment by sstarcher** [comment]
@alonl What are the selectors on your service?

**Comment by alonl** [comment]
@sstarcher 
```
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: "{{ .Chart.Name }}"
```
You're right! The selector matches the deployment's pod as well as this test pod.

I'll change the `app` label to:
```
  labels:
    app: "{{ .Chart.Name }}-test"
```

 Wow, nice catch! Thanks a lot, @sstarcher. Many thanks guys. Closing...
