### ISSUE TITLE
templates with leading YAML separator cause "object not found" errors on deletion

### ISSUE THREAD

**Issue by seanknox** [kubernetes/helm#2256]
## STR
- on helm v2.3.0
- install a release that has a template file starting with `---`, e.g.
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ template "fullname" . }}-tcp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ default "gogs" .Values.service.nameOverride }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: tcp-{{ template "gogs.fullname" . }}-ssh
data:
  2222: default/{{ template "fullname" . }}:ssh
```
- delete the release 

## Expected
- a happy helm deletion occurs

## Actual
- the release is deleted and helm returns an error:
```
$ helm delete wiggly-ibis
Error: deletion completed with 2 error(s): object not found, skipping delete; object not found, skipping delete
```
YAML separators in templates appear to be fine as long as they're not on the first line.
