### ISSUE TITLE
helm install fails when using --wait flag

### ISSUE THREAD

**Issue by JoeTalbot** [kubernetes/helm#2288]
When running:
`/usr/local/bin/helm --kube-context context-name upgrade test-release workspace/hello-world-chart --install --namespace context-namespace --values /workspace/hello-world-chart/values/hello-dev.yaml --set image_tag=latest --wait`

we get consistent failures with the error: 
`Error: UPGRADE FAILED: transport is closing
exit status 1`
And it appears to deploy correctly to kubernetes. By removing `--wait` it deploys correctly and doesn't report any errors to stdout. 

I am using 2.3.1 of helm client and server. 
and kubernetes is version 1.5.1 `Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean"}`

**Comment by technosophos** [comment]
Can you tell me what resource kinds are in that chart? Are they `deployment` objects?

**Comment by ahawkins** [comment]
I get the same error. I read somewhere that kube-proxy has some internal TTL, so if nothing comes back across the proxy then the connection closes. Could this be the case? If so, then perhaps the `--timeout` should apply to connections across `kube-proxy`.

Here's my command:

```
helm install --wait --timeout 1200 \
        --kube-context np.k8s.saltside.io \
        --namespace development \
        -f secrets.yaml \
        --name test-efritin \
        tmp/charts/sandbox/kviberg-efritin
E0420 11:03:55.954664   17070 portforward.go:175] lost connection to pod
Error: transport is closing
```

**Comment by JoeTalbot** [comment]
@technosophos 
We are deploying an autoscaler, deployment, ingress, and service. Here are the examples:
Autoscaler: 
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-playground-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api-playground-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
```

Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-playground-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  template:
    metadata:
      labels:
        app: api-playground-deployment
    spec:
      containers:
      - name: api-playground
        image: dojo.docker.target.com/api-playground:{{.Values.image_tag}}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        ports:
        - containerPort: 3030
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3030
          initialDelaySeconds: 30
          periodSeconds: 4
          timeoutSeconds: 2
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3030
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 1
```

Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-playground-service
  name: api-playground-service
spec:
  ports:
    - port: 80
      targetPort: 3030
  selector:
     app: api-playground-deployment
```

Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-playground-ingress
  labels:
    name: api-playground-ingress
spec:
  rules:
  - host: {{.Values.ingress_host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: api-playground-service
          servicePort: 80
```
