### ISSUE TITLE
Persistent repository using Kubernetes labels

### ISSUE THREAD

**Issue by remohammadi** [kubernetes/helm#232]
Hi!

I've noticed that you're going to [use a database](https://github.com/kubernetes/deployment-manager/pull/170/) to store the state. Is it possible to use the built-in labeling system of Kubernetes to store the state? For example to store the state of a `Deployment`, we can add/update these tags to the object on every kubectl deployment call:
```yaml
metadata:
  labels:
    app: nginx
    createdAt: 2016-02-01T14:33:33.50
    modifiedAt: 2016-02-07T14:33:33.50
    deployedAt: 2016-02-07T14:33:33.50
```
And for `State`, we can query through kubectl, and maybe cache it in memory for a few minutes.

I believe this usage is compatible with [the motivation behind the labels](http://kubernetes.io/v1.1/docs/user-guide/labels.html#motivation).

Are you ok with a PR to provide persistent through this mechanism? Or are there some states which you believe are incompatible with this mechanism?
