### ISSUE TITLE
Parent's values overwrite child's values

### ISSUE THREAD

**Issue by xtimon** [kubernetes/helm#2331]
Parent's values overwrite child's values when I use `--set` syntax, or load values from a values-file. This happens when the child chart has own child chart and exist requirements.yml file.

How to catch the bug:
1. Create three charts:
```
helm create chart1
helm create chart2
helm create chart3
```
2. Add requirements to the chart1:
```
cat << EOF > chart1/requirements.yaml
dependencies:
- name: chart2
  version: 0.1.0
  repository: "file://../chart2"
EOF
```
3. Add requirements to the chart2:
```
cat << EOF > chart2/requirements.yaml
dependencies:
- name: chart3
  version: 0.1.0
  repository: "file://../chart3"
EOF
```
4. Build requirements in charts:
```
helm dependency build chart2/
helm dependency build chart1/
```
5. Install:
```
helm install --dry-run --debug chart1/ --set=image.tag=ERROR | grep ERROR -B 3
```
Output:
```
CHART: chart1-0.1.0
USER-SUPPLIED VALUES:
image:
  tag: ERROR
--
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: ERROR
--
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: ERROR
--
    spec:
      containers:
      - name: chart2
        image: "nginx:ERROR"
--
    spec:
      containers:
      - name: chart1
        image: "nginx:ERROR"
```
Helm version: 
```
Client: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}
```
Repo with bug: https://github.com/xtimon/helm-bug
