### ISSUE TITLE
Helm is converting my git tag to exponential form

### ISSUE THREAD

**Issue by owenmorgan** [kubernetes/helm#2357]
Using the git hash in my charts, and passing it as a cli argument, its messing up my tag in the rendered template.

Helm v2.3.0

Deployment.yml
```
..
containers:
        - name: "{{.Values.image.name}}"
          image: "{{.Values.image.registry}}/{{.Values.image.name}}:{{.Values.image.tag}}"
```

CLI
`helm upgrade --dry-run --debug --install --wait test --values values-UAT.yaml --set image.tag=9765483 .`

USER-SUPPLIED VALUES:
```
image:
     tag: 9765483
```

COMPUTED VALUES:
```
image:
  tag: 9.765483e+06
```
