### ISSUE TITLE
Helm doesn't update secrets?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/helm#2433]
I have an `infra` chart with following `requirements.yaml`:

*infra/requirements.yaml*
```yaml
dependencies:
  - name: global-secrets
    version: 0.0.2
    repository: file://../global-secrets/
```

`global-secrets` contains a bunch of secrets, for example:

*global-secrets/templates/secrets.yaml*
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  host: {{ .Values.postgres.host | b64enc | quote }}
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-replica
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  host: {{ .Values.postgres.read_replica_host | b64enc | quote }}
```

When I initially installed the chart, the secrets were correctly created. However, after changing the values of some of my secret and upgrading, the old secrets aren't replaced and aren't listed under `==> v1/Secret`. With `--debug` I am however able to see the computed secrets.yaml file.

I'm guessing I misunderstood how `"helm.sh/hook": pre-install` works?
