### ISSUE TITLE
 wrong type for value expected string; got float64

### ISSUE THREAD

**Issue by olalonde** [kubernetes/helm#2434]
I'm using `--set` to set `facebook.appId` when installing/upgrading:

```
     --set "facebook.appId=1333333337"
```

I am getting this error:

```
Error: UPGRADE FAILED: render error in "app/templates/secrets.yaml": template: app/templates/secrets.yaml:69:37: executing "app/templates/secrets.yaml" at <b64enc>: wrong typefor value; expected string; got float64
```

Here's the template code that uses the value:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-facebook
type: Opaque
data:
  appID: {{ .Values.facebook.appId | b64enc | quote }}
  appSecret: {{ .Values.facebook.appSecret | b64enc | quote }}
````

I'm guessing that Helm guesses that `1333333337` in `facebook.appId=1333333337` is a float64 whereas I need a way to coerce it to a string so that it's accepted by base64. Is that possible? I tried `--set "facebook.appId=\"1333333337\""` and `--set "facebook.appId='1333333337'"` but it didn't work as expected.
