### ISSUE TITLE
Where's the debugging output?

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/helm#2436]
What should anybody be doing with this output?

```
$ helm install --debug -n myname -f values_file.yaml .
[debug] Created tunnel using local port: '42711'

[debug] SERVER: "localhost:42711"

[debug] CHART PATH: /my/local/path

Error: error validating "": error validating data: found invalid field type for v1.ServicePort
```

Which file is it parsing? There are like 8 services in this chart. What exactly is he missing from his ports definition? Where's the f'n stacktrace? What should anybody do with this output?

**Comment by technosophos** [comment]
Did you run `helm lint` or try the `helm template` plugin?

**Comment by erikbgithub** [comment]
The funny thing is I already found one problem (a `type: NodePort` was indented 3 instead of 2 spaces), but before and after `helm lint` is totally happy, despite `install` being unhappy.

But seriously, can we agree that `install --debug` should be more detailed? You also don't know what's the problem from reading this, right?

**Comment by munnerz** [comment]
FWIW @erikbgithub - the issue you're running into is with one of the Services as part of your deployment I think - you've set a `type` field under the ports section eg:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: something
spec:
  type: LoadBalancer
  ports:
  - name: my-port
     type: invalid # this field shouldn't be here!
     protocol: TCP
```

or something similar :) but yep, it'd be nice if the output included a filename to look at perhaps. For reference, I deduced the above from `found invalid field **type** for **v1.ServicePort**`
