### ISSUE TITLE
dependencies plugin not working with requirements.yaml

### ISSUE THREAD

**Issue by ant31** [kubernetes/helm#2447]
Hi,

I'm trying to use the dependencies plugin  implemented here:
https://github.com/kubernetes/helm/pull/2094

The `helm fetch test://path`  command is working as expected. 
but not when it's used in the requirements.yaml. 

```
$ cat requirements.yaml 
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "test://example.com/charts/app"%  

$ helm dep build
Error: no repository definition for test://example.com/charts. Try 'helm repo add'
```

The plugin is a only a test one: 
```
name: "registry"
version: "0.3.8"
usage: "Appr client to HELM"
description: |-
  This plugin provides Appr client to Helm.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/appr.sh"
downloaders:
  - command: "dummy.sh"  # 'echo $@ > /tmp/helm-download.tar.gz'
    protocols:
      - "test"  
```
