### ISSUE TITLE
Helm caches/searches only part of my repository on GCS

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/helm#2453]
Somehow, Helm only finds some package versions in my repository, but not all:

```shell
$ rm -rf ~/.helm

$ helm init -c
# Creating /Users/jean/.helm 
# Creating /Users/jean/.helm/repository 
# Creating /Users/jean/.helm/repository/cache 
# Creating /Users/jean/.helm/repository/local 
# Creating /Users/jean/.helm/plugins 
# Creating /Users/jean/.helm/starters 
# Creating /Users/jean/.helm/repository/repositories.yaml 
# $HELM_HOME has been configured at /Users/jean/.helm.
# Not installing tiller due to 'client-only' flag having been set
# Happy Helming!

$ helm repo add blendle https://blendle-charts.storage.googleapis.com
# "blendle" has been added to your repositories

$ helm repo update
# Hang tight while we grab the latest from your chart repositories...
# ...Skip local chart repository
# ...Successfully got an update from the "blendle" chart repository
# ...Successfully got an update from the "stable" chart repository
# Update Complete. ⎈ Happy Helming!⎈ 

$ helm search blendle/web --versions
# NAME            VERSION DESCRIPTION                                       
# blendle/web     0.2.1   Run your application or service on Kubernetes, ...
# blendle/web     0.2.0   Run your application or service on Kubernetes, ...

$ cat ~/.helm/repository/cache/blendle-index.yaml 
```

```yaml
apiVersion: v1
entries:
  web:
  - apiVersion: v1
    created: 2017-05-10T13:06:44.806291362+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 836cc1c00034b0c4c175fe2f2bdb210234ef6b01efbb60f04777f5395091f210
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    created: 2017-05-10T13:06:44.805984278+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 422bca17364161a469e49807fc114b41f151c8a26d022f99d85e960b936f9cdb
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.0.tgz
    version: 0.2.0
generated: 2017-05-10T13:06:44.805106543+02:00
```

However, this is _actually_ available:

```shell
$ gsutil ls gs://blendle-charts/
# gs://blendle-charts/.keep
# gs://blendle-charts/index.yaml
# gs://blendle-charts/web-0.1.0.tgz
# gs://blendle-charts/web-0.2.0.tgz
# gs://blendle-charts/web-0.2.1.tgz
# gs://blendle-charts/web-0.2.2.tgz

$ gsutil cat gs://blendle-charts/index.yaml
```

```yaml
apiVersion: v1
entries:
  web:
  - apiVersion: v1
    created: 2017-05-16T22:03:23.858730744+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: f9bb349484732491ded743a169dc9be6225258b146200a17d6d8348a3fee2fab
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v1
    created: 2017-05-16T22:03:23.858522206+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 836cc1c00034b0c4c175fe2f2bdb210234ef6b01efbb60f04777f5395091f210
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    created: 2017-05-16T22:03:23.858286184+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 422bca17364161a469e49807fc114b41f151c8a26d022f99d85e960b936f9cdb
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-05-16T22:03:23.85682617+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 3bd01844afef90b2a1f7082369fa374251218378f6a67ac42dd402feb3a3e8c5
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.1.0.tgz
    version: 0.1.0
generated: 2017-05-16T22:03:23.855849232+02:00
```

**Comment by JeanMertz** [comment]
Ah, I found the issue, it seems `gsutil cat` shows the file content, but `curl` indeed shows an older version:

```shell
$ curl https://blendle-charts.storage.googleapis.com/index.yaml
```

```yaml
apiVersion: v1
entries:
  web:
  - apiVersion: v1
    created: 2017-05-10T13:06:44.806291362+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 836cc1c00034b0c4c175fe2f2bdb210234ef6b01efbb60f04777f5395091f210
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    created: 2017-05-10T13:06:44.805984278+02:00
    description: |
      Run your application or service on Kubernetes, and optionally expose it to the public world.
    digest: 422bca17364161a469e49807fc114b41f151c8a26d022f99d85e960b936f9cdb
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Blendle_logo.svg/1000px-Blendle_logo.svg.png
    name: web
    urls:
    - https://blendle-charts.storage.googleapis.com/web-0.2.0.tgz
    version: 0.2.0
generated: 2017-05-10T13:06:44.805106543+02:00
```
