### ISSUE TITLE
toToml filter converts int to float

### ISSUE THREAD

**Issue by mattsch** [kubernetes/helm#2474]
Given the following data structure in values.yaml:
```yaml
config:
  bar: 9
```
And this in my configmap template:
```yaml
data:
  telegraf-local.conf: |-
{{ .Values.config | toToml | indent 4 }}
```

I get this:
```
data:
  telegraf-local.conf: |-
    foo = 9.0
```

Even casting the variable via `bar: !!int 9` doesn't change the behavior, can't reproduce using the toJson filter either.
