### ISSUE TITLE
AsConfig doesn't dereference variables

### ISSUE THREAD

**Issue by prat0318** [kubernetes/helm#2489]
My sample configmap is:
```
      mySQLConfiguration:
        hostName: "{{ .Values.mysql.host }}"
        schemaName: "{{ .Values.mysql.schema }}"
        username: "{{ .Values.mysql.user }}"
        password: "{{ .Values.mysql.password }}"
```

These get dereferenced if pasted directly in `templates/configmap.yaml`.

But, if i store this yaml separately in a `data/mysql.yaml` directory and then in `templates/configmap.yaml` i use:
```
{{ (.Files.Glob "data/*.yaml").AsConfig | indent 2}} 
```
It creates data without dereferencing the variables from `values.yaml`.
