### ISSUE TITLE
Output from "helm init --dry-run --debug" uses title case for "Spec" and "Status" field names

### ISSUE THREAD

**Issue by seh** [kubernetes/helm#2509]
Related to the root cause of #2181, running _helm init --dry-run --debug_ with Helm version 2.4.2 yields YAML manifests where the "Spec" and "Status" mapping keys are mistakenly in title case (as well as all of the keys contained within those objects).

I suspect that we mistakenly reverted to [using the "internal" Kubernetes types instead of the "external" versioned types](https://github.com/kubernetes/helm/issues/2181#issuecomment-290810996). Looking at the latest version of the pertinent code, [in `installer.generateDeployment`](https://github.com/kubernetes/helm/blob/206035442e034c1c9e84c8e8c8d85096de3943b5/cmd/helm/installer/install.go#L128), we create a `k8s.io/kubernetes/pkg/apis/extensions.DeploymentSpec`, but we should instead be creating a [`k8s.io/client-go/pkg/apis/extensions/v1beta1/DeploymentSpec`](https://github.com/kubernetes/kubernetes/blob/26d7ee04479d0429a8b95c58d1bc8bd9cfafece1/staging/src/k8s.io/client-go/pkg/apis/extensions/v1beta1/types.go#L170-L216). Similar type relationships apply for the other "Spec" and "Status" types.

Sample output (long, yes, but it helps to see which fields are impacted):
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
Spec:
  MinReadySeconds: 0
  Paused: false
  ProgressDeadlineSeconds: null
  Replicas: 1
  RevisionHistoryLimit: null
  RollbackTo: null
  Selector: null
  Strategy:
    RollingUpdate: null
    Type: ""
  Template:
    Spec:
      ActiveDeadlineSeconds: null
      Affinity: null
      AutomountServiceAccountToken: null
      Containers:
      - Args: null
        Command: null
        Env:
        - Name: TILLER_NAMESPACE
          Value: kube-system
          ValueFrom: null
        EnvFrom: null
        Image: gcr.io/kubernetes-helm/tiller:v2.4.2
        ImagePullPolicy: IfNotPresent
        Lifecycle: null
        LivenessProbe:
          Exec: null
          FailureThreshold: 0
          HTTPGet:
            HTTPHeaders: null
            Host: ""
            Path: /liveness
            Port: 44135
            Scheme: ""
          InitialDelaySeconds: 1
          PeriodSeconds: 0
          SuccessThreshold: 0
          TCPSocket: null
          TimeoutSeconds: 1
        Name: tiller
        Ports:
        - ContainerPort: 44134
          HostIP: ""
          HostPort: 0
          Name: tiller
          Protocol: ""
        ReadinessProbe:
          Exec: null
          FailureThreshold: 0
          HTTPGet:
            HTTPHeaders: null
            Host: ""
            Path: /readiness
            Port: 44135
            Scheme: ""
          InitialDelaySeconds: 1
          PeriodSeconds: 0
          SuccessThreshold: 0
          TCPSocket: null
          TimeoutSeconds: 1
        Resources:
          Limits: null
          Requests: null
        SecurityContext: null
        Stdin: false
        StdinOnce: false
        TTY: false
        TerminationMessagePath: ""
        TerminationMessagePolicy: ""
        VolumeMounts: null
        WorkingDir: ""
      DNSPolicy: ""
      Hostname: ""
      ImagePullSecrets: null
      InitContainers: null
      NodeName: ""
      NodeSelector: null
      RestartPolicy: ""
      SchedulerName: ""
      SecurityContext:
        FSGroup: null
        HostIPC: false
        HostNetwork: false
        HostPID: false
        RunAsNonRoot: null
        RunAsUser: null
        SELinuxOptions: null
        SupplementalGroups: null
      ServiceAccountName: ""
      Subdomain: ""
      TerminationGracePeriodSeconds: null
      Tolerations: null
      Volumes: null
    creationTimestamp: null
    labels:
      app: helm
      name: tiller
Status:
  AvailableReplicas: 0
  Conditions: null
  ObservedGeneration: 0
  ReadyReplicas: 0
  Replicas: 0
  UnavailableReplicas: 0
  UpdatedReplicas: 0
creationTimestamp: null
labels:
  app: helm
  name: tiller
name: tiller-deploy
namespace: kube-system
---
apiVersion: v1
kind: Service
Spec:
  ClusterIP: ""
  ExternalIPs: null
  ExternalName: ""
  LoadBalancerIP: ""
  LoadBalancerSourceRanges: null
  Ports:
  - Name: tiller
    NodePort: 0
    Port: 44134
    Protocol: ""
    TargetPort: tiller
  Selector:
    app: helm
    name: tiller
  SessionAffinity: ""
  Type: ClusterIP
Status:
  LoadBalancer:
    Ingress: null
creationTimestamp: null
labels:
  app: helm
  name: tiller
name: tiller-deploy
namespace: kube-system
...
```
