### ISSUE TITLE
(bug): {{ .Chart.AppVersion }} doesn't get template only works when installing from local filesystem

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#2514]
```
$ helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```

Source template - See image name and tag for {{ .Chart.AppVersion }}
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-manager
spec:
  replicas: {{ .Values.manager.deployment.replicas }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.manager.deployment.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        istio: {{ template "fullname" . }}-manager
    spec:
      serviceAccountName: {{ template "fullname" . }}-manager-service-account
      containers:
      - name: discovery
        image: "{{ .Values.manager.deployment.discovery.image }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.manager.deployment.discovery.imagePullPolicy }}
        args: ["discovery", "-v", "2"]
        ports:
        - containerPort: {{ .Values.manager.service.externalHttpDiscovery }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.manager.deployment.discovery.resources | indent 10 }}
      - name: apiserver
        image: "{{ .Values.manager.deployment.apiserver.image }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.manager.deployment.apiserver.imagePullPolicy }}
        args: ["apiserver", "-v", "2"]
        ports:
        - containerPort: {{ .Values.manager.service.externalHttpApiServer }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.manager.deployment.apiserver.resources | indent 10 }}
```

Install from remote repo - see image and with tag truncated (broken)
```
$ helm install incubator/istio --dry-run --debug
# Source: istio/templates/ca-deployment.yaml
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: eloping-leopard-istio-ca
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        istio: eloping-leopard-istio-ca
    spec:
      serviceAccountName: eloping-leopard-istio-ca-service-account
      containers:
      - name: istio-ca
        image: "docker.io/istio/istio-ca:"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

```
Install from local fs - see image and tag
```
laevenso at rue in ~/gocode/src/github.com/kubernetes/charts/incubator/istio on master [?]
$ helm install . --dry-run --debug
<snip>
# Source: istio/templates/ca-deployment.yaml
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: alternating-seal-istio-ca
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        istio: alternating-seal-istio-ca
    spec:
      serviceAccountName: alternating-seal-istio-ca-service-account
      containers:
      - name: istio-ca
        image: "docker.io/istio/istio-ca:0.1.5"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
```
