### ISSUE TITLE
after upgrading from 2.4.x to 2.5.0, subcharts of umbrella charts are no longer installed if you have dependencies in your umbrella chart's requirements

### ISSUE THREAD

**Issue by chancez** [kubernetes/helm#2599]
If an "umbrella" chart contains subcharts within `charts/` and the umbrella chart has a `requirements.{yaml,lock}` then only the umbrella chart's templates, and dependencies will be installed.

If the requirements files do not exist, then helm correctly installs subcharts and the umbrella chart's templates.

Note: it doesn't matter if requirements.yaml/lock have an empty dependencies list (ie: `dependencies: []` or `dependencies: null` the files must not exist to get the behavior of installing subcharts.

As an example, this is my directory structure:

```
.
├── Chart.yaml
├── charts
│   ├── soy-deploy
│   │   ├── Chart.yaml
│   │   ├── charts
│   │   │   ├── soy-server
│   │   ├── requirements.lock
│   │   ├── requirements.yaml
│   │   ├── templates
│   │   │   ├── _helpers.tpl
│   │   │   └── dockerconfig.yaml
│   │   ├── values.yaml
│   │   └── vendored_charts
│   │       └── nginx-ingress
```

requirements.yaml:
```
dependencies:
- name: nginx-ingress
  version: 0.3.1
  repository: file://./vendored_charts/nginx-ingress
  condition: nginx-ingress.enabled
```

In this setup, only the `nginx-ingress` chart and my `dockerconfig` template are installed.

CC @sushilkm @jascott1
