### ISSUE TITLE
Configmaps changes don't trigger a rolling-update

### ISSUE THREAD

**Issue by Smana** [kubernetes/helm#2610]
Hi!

I tried to use the tip as described [here](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md) but unfortunately it doesn't work.
I mean the sha256sum is changed in the annotations but the rolling-update is not triggered.

Did i miss something ?

Kubernetes version : 1.6.4

Regards,
Smana

**Comment by thomastaylor312** [comment]
@Smana Can you post the chart snippet here?

**Comment by Smana** [comment]
Sure,
Here is an excerpt of my deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "myapp"
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
...
            - name: FOO
              valueFrom:
                configMapKeyRef:
                  name: myapp-config
                  key: foo
...
```

Note that the configmap is not mounted as a volume but it is used to configure some environment variables.

Thank you @thomastaylor312
