### ISSUE TITLE
Proposal: Make kube-config values available to templates

### ISSUE THREAD

**Issue by rodcloutier** [kubernetes/helm#2613]
In our daily usage, we often target minikube and cloud hosted clusters. 
Each have separate contraints that need to be adressed in the chart and have selectors to activate or deactivate the features needed which are controlled by the values file. Something along the lines of

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-name
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    project/app: api-gateway
    project/exposure: external
  annotations:
    {{- if eq .Values.clusterType "gke" }}
    company.com/dns-prefix: "{{ .Values.gke.dnsPrefix }}"
    company.com/dns-zone: "{{ .Values.gke.dnsZone }}"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  tls:
    - secretName: api-gateway-secret
  rules:
  - http:
      paths:
        {{- if eq $.Values.clusterType "gke" }}
        - path: /*
        {{- else }}
        - path: /
        {{- end }}
          backend:
            serviceName: kong-proxy
            servicePort: kong-proxy

````

``` 
# values.yaml
# The type of cluster we deploy to.
clusterType: gke
```
Since we favor security, we have the default to be configuration for the cloud cluster. This leads to having helm command that look like:

`helm install --set clusterType=minikube repo/chart`

If were to have access to the kubeconfig values, we could use the information to avoid  asking the developers to remember the proper flag. Maybe something like

```
{{- if eq $.Kubeconfig.current-context "minikube" }}
- path: /
{{- else }}
- path: /*
{{- end }}
```
Further extension could be to actually properly query the config to avoid relying on the name of the context that can be changed:

```
 {{- if eq $.Kubeconfig.clusters[$.Kubeconfig.contexts[$..Kubeconfig.current-context].cluster].name "minikube" }}
```
> The syntax might not be possible but it is to present the objective
