### ISSUE TITLE
Helm should be aware of APIServices

### ISSUE THREAD

**Issue by arschles** [kubernetes/helm#2641]
If a chart contains a template like this (will only work on Kubernetes v1.7.0 and above):

```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.servicecatalog.k8s.io
spec:
  group: servicecatalog.k8s.io
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "fullname" . }}-apiserver
  caBundle: {{ (.Files.Get .Values.apiserver.tls.caFileName) | b64enc }}
  priority: 100
  groupPriorityMinimum: 10000
  versionPriority: 20
```

... the output of `kubectl get apiservice` will include `v1alpha1.servicecatalog.k8s.io`. When a user runs a `helm delete ...` command, the `APIService` will still exist in this list, which means that a subsequent `helm install` command will fail. Personally, I think it makes sense to delete the `APIService` on a `helm delete` command.

I'd be interested to hear others' thoughts as well!
