### ISSUE TITLE
Bug: `dependency update` deletes required charts, when used in with new `alias` feature

### ISSUE THREAD

**Issue by alonl** [kubernetes/helm#2643]
Reproduction steps:
1. Create a `requirements.yaml` file with 2 dependencies that have the same chart name, with different alias, and **with different version**. For example:
```
dependencies:
- name: some-chart
  version: 0.1.0
  repository: http://127.0.0.1:8879/charts
- name: some-chart
  version: 0.1.1
  repository: http://127.0.0.1:8879/charts
  alias: some-chart-alias
```
2. Run: `helm dependency update`

Expected result:
`charts/` dir contains both versions of the chart.

Actual result:
`charts/` dir contains only the latter.

I debugged it a little bit and found the cause. A PR is coming in a minute...
