### ISSUE TITLE
Proposal: Change 'type' to 'chart' in the config YAML file

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#267]
Moving forward, could we make a minor change to the config YAML file? I'd like to propose replacing `type:` with `chart:`, since I think those are now what we'll be referencing.

```
resources:
- name: frontend
  type: github.com/kubernetes/application-dm-templates/common/replicatedservice:v1
  properties:
    service_port: 80
    container_port: 80
    external_service: true
    replicas: 3
    image: gcr.io/google_containers/example-guestbook-php-redis:v3
- name: redis
  type: github.com/kubernetes/application-dm-templates/storage/redis:v1
  properties: null
```
