### ISSUE TITLE
usage of repository in requirements.yaml is unclear

### ISSUE THREAD

**Issue by jeff-knurek** [kubernetes/helm#2672]
As per the documentation on using requirements.yaml, one can do something along the lines of:
```
# parentchart/requirements.yaml
dependencies:
  - name: subchart
    repository: http://localhost:10191
    version: 0.1.0
```
----
When adding a subchart from the official repository: https://github.com/kubernetes/charts
> This is the default repository for Helm and is installed by default. 

There should be no need for `repository: http://localhost:10191` in this case, since the default repository should be searched. However, not including it leads to an (unhelpful) error: 
```
Error: no repository definition for . Try 'helm repo add'
```
----
Using the repository name however:
```
# parentchart/requirements.yaml
dependencies:
  - name: subchart
    repository: stable
    version: 0.1.0
```
also fails:
```Error: no repository definition for stable. Try 'helm repo add'```

----

The only option then is to try `helm repo list` and include the URL provided for stable. 
```
NAME  	URL
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts
```

----

In summary, I think this amounts to 2 Feature Requests, and maybe some better documentation/error messaging.
Feature requests:

1. Install from `default`/`stable` repository if a repository is not provided
1. Use `Name` of repo instead of URL (easier to make one change to update all charts)
