### ISSUE TITLE
Misleading example of the b64enc function to encrypt secrets

### ISSUE THREAD

**Issue by namsral** [kubernetes/helm#2679]
The following passage from the Helm docs suggests to base-64 encode a secret. I think the example might mislead some users of Helm into thinking secrets like a token can be encrypted with the `b64enc` function.

```
## Secrets

When working with a Secret resource, you can import a file and have the template base-64 encode it for you:

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  token: |-
    {{ .Files.Get "config1.toml" | b64enc }}

The above will take the same `config1.toml` file we used before and encode it:

# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lucky-turkey-secret
type: Opaque
data:
  token: |-
    bWVzc2FnZSA9IEhlbGxvIGZyb20gY29uZmlnIDEK
```

https://github.com/kubernetes/helm/edit/master/docs/chart_template_guide/accessing_files.md#L167
