### ISSUE TITLE
Need official name for the config YAML files

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#268]
We use files like this to relate a set of values to a chart:
```
resources:
- name: redis
  type: github.com/kubernetes/application-dm-templates/storage/redis:v1
  properties: null
```
I think we've called these files "config YAML files", "resource files" and "values files" -- all three of which sound generic. @jackgr proposed giving them a more meaningful name. I think that's a good idea. So what would we call them?
