### ISSUE TITLE
Init containers not updated on upgrade

### ISSUE THREAD

**Issue by Draiken** [kubernetes/helm#2702]
Hi there!

I am using `spec.initContainers` on a deployment and during the first upgrade to add the initContainers, everything worked fine.
Second upgrade, I only changed things on the initContainers and the deployment didn't even get upgraded.

I tested changing something else and the deployment got updated but upon inspection, there were two annotations: `pod.alpha.kubernetes.io/init-containers` and `pod.beta.kubernetes.io/init-containers`, no `spec.initContainers` and the values on the annotations were still the ones from the first upgrade.

After that I attempted to use the annotations directly instead of the new spec field, and got the same results: the annotations never got updated

After several tests I've come to the conclusion that something is excluding initContainers from the upgrade diffs.

Am I doing something wrong here or is this a bug?
I have used initContainers on annotations before and they worked, but this was a few versions ago.

My helm is:
```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```
And Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:54:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jurgenweber** [comment]
This was posted in #helm-users and I made the comment that I have run into my initContainer details not updating before. I changed my templating to update the initspec and the annotations and it works after that.

```
...
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"code-copy","image":"example_image:latest","command":["cp","-r","/var/www/html/","/html"],"resources":{},"volumeMounts":[{"name":"app-volume","mountPath":"/html"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"code-copy","image":"example_image:latest","command":["cp","-r","/var/www/html/","/html"],"resources":{},"volumeMounts":[{"name":"app-volume","mountPath":"/html"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
      labels:
        app: hip-new
        hip-new: www-{{ $k }}
      name: www-{{ $k }}
      namespace: engineering
    spec:
      initContainers:
        - name: code-copy
          image: example_image:latest
          command: ["cp", "-r", "/var/www/html/", "/html"]
          volumeMounts:
            - name: app-volume
              mountPath: /html
      containers:
        - name: fpm
...
```

sort of idea, so if you want to update the image, since you have a later version.. change the latest in all 3 places to what you need.

Then it works, I did note you saying you knew about this and it is still not working. I dunno.

**Comment by Draiken** [comment]
I use a variable `{{ .Values.image.tag }}` matching on the init container and regular containers for the docker image tag. When upgrading, the regular containers get updated and the initContainers do not.

```
...
spec:
  template:
    spec:
      initContainers:
        - name: assets
          image: "{{ .Values.assets.repository }}:{{ .Values.image.tag }}"
      containers
        - name: other-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
...
```

I will try to replicate the init container on both annotations and the spec to see what happens...

**Comment by Draiken** [comment]
Just to clarify what I tried so far:
- Using only alpha init container annotation
- Using only `spec.initContainers`
I have yet to try:
- Use only the beta annotation
- Use both the beta and alpha annotations
- Use both the beta and alpha annotations and the `spec.initContainers`

**Comment by Draiken** [comment]
I managed to replicate the issue on a new chart:
```
helm create init-bug
echo '      initContainers: [ { name: "sleeper", image: "alpine:{{ .Values.alpineVersion }}", args: ["/bin/ash", "-c", "sleep 10"] } ]'
helm install init-bug --name buggy --set alpineVersion=3.5
helm upgrade buggy init-bug --set alpineVersion=3.6
kubectl get deployment buggy-init-bug -o jsonpath="{.spec.template.spec.initContainers[0].image}"
```
Running this will output
```
alpine:3.5
```
If I run the upgrade on `--dry-run` and `--debug` the init container looks correct, but when actually running the code, the deployment is not even changed.

**Comment by miadabrin** [comment]
Same here. Init containers are not changed on `kubectl apply -f` to the same resource file

**Comment by Draiken** [comment]
This is probably related to kubernetes/kubernetes#47264
I'll try changing the beta annotation. Hopefully it'll work

**Comment by jstriebel** [comment]
Same here when using `spec.initContainers` in an CronJob. Changes are not reflected in Kubernetes when upgrading. Requesting to change the label of this issue to __Bug__.

Example:
```
apiVersion: batch/v2alpha1
kind: CronJob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          …
```
