### ISSUE TITLE
Template generation oddity

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#2723]
Warning this issue is odd.
1. A chart is installed from a helm repo at a specific version
2. Chart is upgraded with `helm upgrade --version` using the exact same version
3. This is done 100+ times over a week

I have the following deployment snippet
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

The following helper
```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if ne .Chart.Name .Release.Name -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s" $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

Which 99.9% of the time if .Chart.Name is equal to .Release.Name the resulting value is `.Chart.Name`. 

The resultant deployment in the very odd edge case is
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: NAME-NAME
  labels:
    component: NAME
    release: NAME
    heritage: Tiller
```

component is .Chart.Name and release is .Release.Name.  So I'm dumbfounded how the fullname template I specified above is returning `NAME-NAME` 

This chart has a single _helpers.tpl file and no subcharts or dependent charts.
