### ISSUE TITLE
Environment variable ordering not properly updated

### ISSUE THREAD

**Issue by kujenga** [kubernetes/helm#2736]
I recently updated a helm chart to use an environment variable derived from other environment variables [1]. The helm chart talks to an external RabbitMQ instance, and the latest version has the following block in the environment variables:

```yaml
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.amqp.secretName }}
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.amqp.secretName }}
              key: rabbitmq-password
        - name: AMQP_URL
          value: amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ .Values.amqp.host }}:{{ .Values.amqp.port }}/
```

The previous configuration had just the `RABBITMQ_PASSWORD` defined in the environment variables, and what is now the `AMQP_URL` was defined in a custom command line flag within the `args` block, with the username hardcoded.

```yaml
        args:
        - --amqp=amqp://someusername:$(RABBITMQ_PASSWORD)@external-rabbitmq:5672/
        env:
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: engine-rabbitmq
              key: rabbitmq-password
```

After the upgrade was executed through Helm, the environment variables were not in the order specified in the chart, and thus the `AMQP_URL` was not properly evaluating. It appears as though the new environment variables were put in alphabetical order and then appended to the existing ones, resulting in the following ordering:

```yaml
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.amqp.secretName }}
              key: rabbitmq-password
        - name: AMQP_URL
          value: amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ .Values.amqp.host }}:{{ .Values.amqp.port }}/
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.amqp.secretName }}
              key: rabbitmq-username
```

The way I initially resolved this was by manually editing the deployment after the helm upgrade had completed for all the components of the chart that had this configuration, but that's not an ideal solution. Is this an issue with Helm, Kubernetes itself?

[1] https://kubernetes.io/docs/api-reference/v1.7/#envvar-v1-core
