### ISSUE TITLE
import-values expects a table and not an individual value

### ISSUE THREAD

**Issue by escardin** [kubernetes/helm#2746]
Or alternately, you can't import all the values of a child chart.

Example (altered from docs)
```
# parent's requirements.yaml file
dependencies:
  - name: subchart1
    repository: http://localhost:10191
    version: 0.1.0
    ...
    import-values:
      - child: myint
        parent: myimports.myint
     - child: ''
        parent: childvals

# parent's values.yaml file

myimports:
  myint: 0
  mybool: false
  mystring: "helm rocks!"
  
# subchart1's values.yaml file

myint: 999
mybool: true

# parent's expected final values

myimports:
  myint: 999
  mybool: false
  mystring: "helm rocks!"
childvals:
  myint: 999
  mybool: true
```
What actually happens is you get errors.
