### ISSUE TITLE
Simplify environment variables

### ISSUE THREAD

**Issue by vpetersson** [kubernetes/helm#2780]
First off, great job with Helm, folks.

It's fairly common that you need to expose a lot of env variables to a pod, like this:

```
            env:
              - name: FOO1
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.coreSecret }}
                    key: foo1
              - name: FOO2
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.coreSecret }}
                    key: foo2
              - name: FOO3
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.coreSecret }}
                    key: foo3
```

I literally have containers with 40 of these, which means a lot of boilerplate repeating the stanza over and over. It would be clean (and DRY) to be write the snippet above something like this:

```
            env:
              - helm.getSecretFrom: {{ .Values.coreSecret }}
                 - name: FOO1
                    key: foo1
                 - name: FOO2
                    key: foo2
                 - name: FOO3
                    key: foo3
```

I realize that this is a pretty big step away from how the native YAML/JSON looks like in native Kubernetes, but it would significantly clean up Helm templates.

I'm still new to Helm (and Kubernetes), so perhaps I'm overlooking something basic that would prevent such templating.

**Comment by bacongobbler** [comment]
@vpetersson have you looked into writing a [helper function](https://docs.helm.sh/developing_charts/#using-partials-and-template-includes) for your chart? That feature was designed specifically with this use case in mind.

**Comment by vpetersson** [comment]
Good call, @bacongobbler. Will have to take a look at it.

**Comment by PhilippeDupont** [comment]
@vpetersson You could use `range` function in your template to do what you want : 
in values.yaml : 
``` 
env:
  fromSecret:
    name: codeSecret
    data:
      FOO1: foo1
      FOO2: foo2
      FOO3: foo3
```
in the template file: 
```
        env:
        {{- range $key, $value := .Values.env.fromSecret.data }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
                name: {{ .Values.env.fromSecret.name  }}
                key: {{ $value | quote }}
        {{- end }}
```

**Comment by bacongobbler** [comment]
This is being used fairly commonly across several charts. We should doc this in the best practices guide as an action item to close this out.

**Comment by vpetersson** [comment]
@bacongobbler Yes, that should be possible to simplify things using that. Still just dipping my toes in the water with Helm so haven't familiarized myself with that yet.

@PhilippeDupont Unfortunately that was just a sloppy example. It wouldn't be a `range()` style function in my case.

**Comment by subk** [comment]
Here is how we do it for the exact same purpose :
In a `Deployment` base chart : 
```yaml
....
    env:
{{- range $secret := .Values.secrets }}
  {{- if eq $secret.type "env" }}
    {{- range $key := $secret.keys }}
      {{- $envPrefix := $secret.prefix | default "" | upper }}
      {{- $envKey := $key | upper | replace "." "_" | replace "-" "_" }}
      - name: {{ $envPrefix }}{{ $envKey }}
         valueFrom:
           secretKeyRef:
             name: {{ $secret.name }}
             key: {{ $key }}
    {{- end }}
  {{- end }}
{{- end }}
...
```
`values.yaml` file from another chart depending on previous `Deployment` chart : 
```yaml
deployment:
  secrets:
  - type: env                
    name: my-secret     # secret name
    prefix: MY_         # optional prefix
    keys:               # secret key ref list
    - foo               # my-secret.foo => MY_FOO
    - x.y.z             # my-secret.x.y.z => MY_X_Y_Z
```
 
Hope this helps

**Comment by oesah** [comment]
This works, but has the downside that you have to hardcode sensitive information into the code. Wasn't the idea behind environment variables that you don't have to do that or am I missing something here? Also, what if you have different env vars for different stages? This looks very messy to me..

**Comment by PhilippeDupont** [comment]
You're right, sensitive informations shouldn't be hardcoded. That's why we use [kubernetes secrets](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
Currently, k8s secrets are not much secure(base64 encoded), but there are (a bit complex) solutions out there, like [vault](https://github.com/Boostport/kubernetes-vault)

**Comment by helgi** [comment]
Should be able to use `fromEnv` (and the secrets eqv) in newer Kubernetes for this to achieve the same without needing helm functions

**Comment by colinhoglund** [comment]
I've gone through a few iterations of how to handle setting sensitive environment variables. Something like the following is the simplest solution I've come up with so far:

template:
```
{{- if or $.Values.env $.Values.envSecrets }}
env:
  {{- range $key, $value := $.Values.env }}
  - name: {{ $key }}
    value: {{ $value | quote }}
  {{- end }}
  {{- range $key, $secret := $.Values.envSecrets }}
  - name: {{ $key }}
    valueFrom:
      secretKeyRef:
        name: {{ $secret }}
        key: {{ $key | quote }}
  {{- end }}
{{- end }}
```

values:
```
env:
  ENV_VAR: value
envSecrets:
  SECRET_VAR: k8s-secret-name
```

Pros:
- syntax is pretty straightforward
- keys are easily mergeable. This came in useful when creating CronJobs with shared secrets. I was able to easily override "global" values using the following:

        {{- range $key, $secret := merge (default dict .envSecrets) $.Values.globalEnvSecrets }}

Cons:
- This only works for secret keys that exactly match the name of the environment variable, but it seems like that is the typical use case.
