### ISSUE TITLE
Dependency aliases not working with semver logic

### ISSUE THREAD

**Issue by apeschel** [kubernetes/helm#2794]
Issue found on v2.5.1

The alias functionality only works when a hardcoded version is used. Any use of semver logic causes unexpected behavior.

* All aliased dependencies with semver logic are ignored.
* If all aliased dependencies for a chart are ignored, then the base chart name is used

Expected behavior:

* Aliased dependencies should handle semver logic identically to non-aliased dependencies.

Example 1
---
All aliased dependencies use semver logic.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: baz
```

Produces

```
# Source: requirement-test/charts/mariadb/templates/secrets.yaml
# Source: requirement-test/charts/mariadb/templates/configmap.yaml
# Source: requirement-test/charts/mariadb/templates/pvc.yaml
# Source: requirement-test/charts/mariadb/templates/svc.yaml
# Source: requirement-test/charts/mariadb/templates/deployment.yaml
```
Example 2
---
Only one aliased dependency uses hardcoded version logic.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: baz
```

Produces:

```
# Source: requirement-test/charts/baz/templates/secrets.yaml
# Source: requirement-test/charts/baz/templates/configmap.yaml
# Source: requirement-test/charts/baz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/svc.yaml
# Source: requirement-test/charts/baz/templates/deployment.yaml
```
Example 3
---
Mix of semver logic and hard coded versions.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: baz
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: fizz
```

Produces:

```
# Source: requirement-test/charts/fizz/templates/secrets.yaml
# Source: requirement-test/charts/baz/templates/secrets.yaml
# Source: requirement-test/charts/fizz/templates/configmap.yaml
# Source: requirement-test/charts/baz/templates/configmap.yaml
# Source: requirement-test/charts/fizz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/svc.yaml
# Source: requirement-test/charts/fizz/templates/svc.yaml
# Source: requirement-test/charts/fizz/templates/deployment.yaml
# Source: requirement-test/charts/baz/templates/deployment.yaml
```
