### ISSUE TITLE
Can Helm support to ignore {{expr}} which is just for configuration but not render?

### ISSUE THREAD

**Issue by thxCode** [kubernetes/helm#2798]
There is a use case: deploy Prometheus as StatefulSet and config alerting-rules as **ConfigMap**.

_alerting-rules_ can take more detail on here: https://prometheus.io/docs/alerting/rules/#alerting-rules

it looks like:
```ALERT InstanceMemoryOverload
  IF node_memory_Active >= 1
  FOR 1m
  LABELS { 
    service = "k8s_metrics", 
    alertname = "InstanceMemoryOverload" 
  }
  ANNOTATIONS {
    summary = "Instance {{ $labels.instance }} memory overload",
    description = "{{ $labels.instance }} memory overload for more than 1 minutes, now is {{ $value }}."
  }
```
**Can Helm support to ignore {{expr}} which is just for configuration but not render?**

**Comment by phillydogg28** [comment]
I have a similar use case to have a go style template in a config map. Right now helm is trying to evaluate the template and causing errors in the config map.

**Comment by ntfrnzn** [comment]
I ran into this same/similar problem awhile ago and solved it by embedding including the alerting rules as separate files, as
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-rules
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    role: {{ template "fullname" . }}-rulefiles
    prometheus: {{ template "fullname" . }}
data:
  {{ (.Files.Glob "files/kubernetes.rules").AsConfig }}
  {{ (.Files.Glob "files/etcd2.rules").AsConfig }}
  {{ (.Files.Glob "files/custom_alert.rules").AsConfig }}
```
AFAIK it is extremely difficult to escape `{{ }}` in a go template, and slurping the files in from elsewhere is much simpler.

**Comment by bacongobbler** [comment]
The way to escape double curly brackets in Go templates is to use `{{ "{{" }}`. It's not extremely difficult, just ugly.

**Comment by bacongobbler** [comment]
I'm going to close this issue as we have two separate solutions to the problem, but please re-open if this hasn't been resolved.

**Comment by Rivic** [comment]
@bacongobbler Hello Matthew, I've been fighting with how to escape curly braces in a Helm template in markdown.  Maybe I'm not understanding your solution.  How would I render this correctly?
(just a snippet).  I've tried raw/endraw, pre, single backslash, double backslash - No success!
thanks for any suggestion...I'm trying to put this in code block with either indents or backticks.

```
  apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: {{ template "fullname" . }}
```

**Comment by Rivic** [comment]
@bacongobbler  I found the solution.  I need to use both  <pre> and &123; &125;

**Comment by jonasscherer** [comment]
> @bacongobbler I found the solution. I need to use both pre and `&123; &125;`

Could you please show an example?
Is there a way to exclude one yaml from the template engine?

**Comment by jorgenkg** [comment]
A viable hack is to let Helm render the template as a raw string. Note the opening and closing curly bracket with a backtick:

```yaml
# Extract from a Prometheus Alertmanager yaml
receivers:
- name: slack-receiver
  slack_configs:
  - text: |-
      {{`{{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
      {{ end }}`}}
```

**Comment by weihxa** [comment]
> 一个可行的黑客是让Helm将模板渲染为原始字符串。注意带有反引号的开合花括号：
> 
> ```yaml
> ＃摘自Prometheus Alertmanager yaml 
> 接收器：
> - name：slack-receiver 
>   slack_configs：
>   - text：|  - 
>       {{`{{range .Alerts}} 
>         *提醒：* {{。注释um}} 
>       {{end}}`}}
> ```

Thank you very much. That solved the big problem

**Comment by weihxa** [comment]
> A viable hack is to let Helm render the template as a raw string. Note the opening and closing curly bracket with a backtick:
> 
> ```yaml
> # Excerpt from a Prometheus Alertmanager yaml
> receivers:
> - name: slack-receiver
>   slack_configs:
>   - text: |-
>       {{`{{ range .Alerts }}
>         *Alert:* {{ .Annotations.summary }}
>       {{ end }}`}}
> ```

Thank you very much. That solved the big problem

**Comment by yarinm** [comment]
you can also use printf for that:

`{{ printf "{{ some value }}" }}`

**Comment by bluebeach** [comment]
> A viable hack is to let Helm render the template as a raw string. Note the opening and closing curly bracket with a backtick:
> 
> ```yaml
> # Excerpt from a Prometheus Alertmanager yaml
> receivers:
> - name: slack-receiver
>   slack_configs:
>   - text: |-
>       {{`{{ range .Alerts }}
>         *Alert:* {{ .Annotations.summary }}
>       {{ end }}`}}
> ```

it works, thx

**Comment by swapnildahiphale** [comment]
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: {{ template "fullname" . }}-rules
>   labels:
>     chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
>     role: {{ template "fullname" . }}-rulefiles
>     prometheus: {{ template "fullname" . }}
> data:
>   {{ (.Files.Glob "files/kubernetes.rules").AsConfig }}
>   {{ (.Files.Glob "files/etcd2.rules").AsConfig }}
>   {{ (.Files.Glob "files/custom_alert.rules").AsConfig }}

This didn't work for me.
After banging my head for 2 days was able to make following work!

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-rules
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    role: {{ template "fullname" . }}-rulefiles
    prometheus: {{ template "fullname" . }}
data:
  {{- (.Files.Glob "files/kubernetes.rules").AsConfig | nindent 2}}
`

**Comment by v6** [comment]
> A viable hack is to let Helm render the template as a raw string. Note the opening and closing curly bracket with a backtick:
> 
> ```yaml
> # Excerpt from a Prometheus Alertmanager yaml
> receivers:
> - name: slack-receiver
>   slack_configs:
>   - text: |-
>       {{`{{ range .Alerts }}
>         *Alert:* {{ .Annotations.summary }}
>       {{ end }}`}}
> ```

I can add to the chorus of confirmations that this still works.

And you may need it to get this to work: 

https://www.vaultproject.io/docs/platform/k8s/injector/examples/

```
cat <<EOF >> ./patch.yaml
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/db-app"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/db-app" -}}
          postgres://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/appdb?sslmode=disable
          {{- end }}
        vault.hashicorp.com/role: "db-app"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/client-cert: "/vault/tls/client.crt"
        vault.hashicorp.com/client-key: "/vault/tls/client.key"
        vault.hashicorp.com/tls-secret: "vault-tls-client"
EOF
```

**Comment by rjshrjndrn** [comment]
```
spec:
  groups:
  - name: alertrules.kafkalag
    rules:
    - alert: AssessmentAggregator lag
      expr: sum(samza_pipeline_metrics_consumer_lag{job_name= "AssessmentAggregator"}) > {{ .Values.assessment_aggregator_threshold }}
      for: 5m
      labels:
        severity: critical
      annotations:
        message: {{`"AssessmentAggregator lag is {{$value}}"`}}
        summary: AssessmentAggregator lag is Critical
````
You can add 
```
{{` ....... `}}
```
and will template properly

**Comment by NargiT** [comment]
> 
> 
> A viable hack is to let Helm render the template as a raw string. Note the opening and closing curly bracket with a backtick:
> 
> ```yaml
> # Excerpt from a Prometheus Alertmanager yaml
> receivers:
> - name: slack-receiver
>   slack_configs:
>   - text: |-
>       {{`{{ range .Alerts }}
>         *Alert:* {{ .Annotations.summary }}
>       {{ end }}`}}
> ```

Unfortunately this does not work using `promtool`.

**Comment by Kaali09** [comment]
> ```
> spec:
>   groups:
>   - name: alertrules.kafkalag
>     rules:
>     - alert: AssessmentAggregator lag
>       expr: sum(samza_pipeline_metrics_consumer_lag{job_name= "AssessmentAggregator"}) > {{ .Values.assessment_aggregator_threshold }}
>       for: 5m
>       labels:
>         severity: critical
>       annotations:
>         message: {{`"AssessmentAggregator lag is {{$value}}"`}}
>         summary: AssessmentAggregator lag is Critical
> ```
> 
> You can add
> 
> ```
> {{` ....... `}}
> ```
> 
> and will template properly

Awesome!!!. It worked. Thanks.

**Comment by Sudharma** [comment]
That works but how can we make it run for prometheus unit test? Any clues?

**Comment by pjamenaja** [comment]
Hi,

Just for the persons how reach here and finding the way to use literal like "{{ xxxxx }}" in your helm value file. The snippet below solved my issue.
 
```yaml
      labels:
        sink_name: loki_syslog
        #Below key useed printf() to escape Helm interprets {{ }}
        message: >-
          {{ printf "{{ message }}" }}
        hostname: >-
          {{ printf "{{ hostname }}" }}
```

The helm rendered output look like this

```yaml
        labels:
          hostname: '{{ hostname }}'
          message: '{{ message }}'
          sink_name: loki_syslog
```

**Comment by withernet** [comment]
So, I want to add my two cents here on how to get the backtick in the raw string. It is possible, and I have found a way to do it.

For example:
```
{{`Environment: {{ .CommonLabels.environment }}
Cluster: {{ .CommonLabels.cluster }}`}}
```

I want the label content in backticks, so:

```
{{`Environment: {{ printf "\x60" }}{{ .CommonLabels.environment }}{{ printf "\x60" }}
Cluster: {{ printf "\x60" }}{{ .CommonLabels.cluster }}{{ printf "\x60" }}`}}
```

Basically, where you want backticks just add `{{ printf "\x60" }}`

**Comment by dmanser92** [comment]
The printf approach worked fine for me, I just wanted to add that if you need to print curly braces it's not gonna be valid yaml if not quoted.
There are certain use cases where for example a k8s-operator performs templating and you don't want to render it with helm already. That's how I did it (I want the stuff in quotes not to be rendered by helm):
`.dockerconfigjson: {{ printf "{{ .pullsecret | toString }}" | quote }}`

**Comment by YevheniiPokhvalii** [comment]
> The way to escape double curly brackets in Go templates is to use `{{ "{{" }}`. It's not extremely difficult, just ugly.

It does not work for me:
```
            description: >-
               Pod {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.pod {{ "}}" }} ({{ "{{" }} $labels.container {{ "}}" }}) is restarting {{ "{{" }} printf "%.2f" $value {{ "}}" }} times / 2 minutes.

```
error
```
: undefined variable "$labels"
```

**Comment by wenjinsitu** [comment]
Anyone know how to escape a ` sign? example `kubeflow`

**Comment by rufreakde** [comment]
IMHO this thread was closed to early. Just because a workaround was found for something that should be enabled in helm itself via some metadata like
```yaml
{{ignoreTemplateStart}}
...
{{ignoreTemplateEnd}}
```
Where both of this evaluate to "" ofc.

Yes - there are workarounds but the original creator of this thread asked for a configuration for helm not a workaround for strings to trick helm. And I think it would be a great addition.

Its a feature request and should also be considered as such.

**Comment by joejulian** [comment]
@rufreakde Since this is actually just how the go template engine works, perhaps file an issue there. The solutions offered in this thread are the only ways to do it with go templates.

**Comment by nicokowe** [comment]
> @rufreakde Since this is actually just how the go template engine works, perhaps file an issue there. The solutions offered in this thread are the only ways to do it with go templates.

helm could disable the go templating when it find a flag "ignoreTemplateStart" It should be not too difficult and it will sove lots of problems for any jinja configmap

**Comment by zakkg3** [comment]
there is a better workaround and is using  **toJson**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  compute.json:
{{ .Files.Get "dashboards/compute.json" | toJson | indent 4 }}
```

this avoids Go rendering the content of compute.json and puts the content there with the "{{variables}}" and everything.

be aware. Confimaps have a limitation of 1 MB. So do not abuse this. Otherwise, consider putting them on a repo and use something like this for GitLab (you can do it for any external URL / repo):

```yaml
    dashboards:
      default:
        your-dashboard-at-gitlab:
          url: "https://gitlab.yourdomain.com/api/v4/projects/9999/repository/files/yourfolder%2Fcompute.json/raw?ref=main"
```
