### ISSUE TITLE
helm get manifest after install of release that FAILED comes back as not found

### ISSUE THREAD

**Issue by kiich** [kubernetes/helm#2820]
When a helm install fails, doing a helm get manifest to check manifest fails with message "release note found" even though helm list shows a release is there.

Sequence of event is like this:
Using this deployment.yaml:
```
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        test: abcd
    spec:
      containers:
      - name: nginx
        image: thisfailsnginx:1.7.9
        ports:
        - containerPort: 80
```
and do:
```
helm install --namespace temp --name temp /tmp/charts
```
to install the chart which fails due to image pull backoff and pod never going into ready state.

I then do:
```
helm list
```
to see if release got created, which it has.
```
[storage] 2017/08/16 23:48:39 Listing all releases with filter
NAME 	REVISION	UPDATED                 	STATUS	CHART      	NAMESPACE
temp	1       	Wed Aug 16 23:42:17 2017	FAILED	nginx-0.1.0	default
```

however, doing a get manifest fails with:
```
helm get manifest temp
```
which fails with:
```
[storage] 2017/08/16 23:54:17 Getting deployed release from "temp" history
Error: release: "temp" not found
```
However, explicitly specifying revision works.
```
helm get manifest temp --revision 1
```
shows me the manifest correctly.

Is this expected behaviour? i.e. only look for non-failed release.
If so, was a bit surprised as the release itself was created.
