### ISSUE TITLE
Conditions for equal dependencies with alias

### ISSUE THREAD

**Issue by bcanyelles** [kubernetes/helm#2821]
Hi,

I have a problem traying to deploy the next structure:

```
# main chart requirements
dependencies:
  - name: app
    version: 0.1.0
    repository: http://127.0.0.1:8879/charts
  - name: app
    version: 0.1.0
    repository: http://127.0.0.1:8879/charts
    alias: reducedApp
```
```
# main chart values
app:
  redis:
    enabled: true
reducedApp:
  redis:
    enabled: false
```

```
# app chart requirements
dependencies:
  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled
```
```
# app chart values
  redis:
    enabled: true
```

It generates two redis deployment and two redis services, one for each main chart dependency (app and reducedApp), but the conditions and the parent defined values should skip the generation of the redis deployment and service for `reducedApp`.

How can I solve this problem? It's a bug?

Thanks.
