### ISSUE TITLE
`helm repo index` doesn't sort entries using SemVer

### ISSUE THREAD

**Issue by djhaskin987** [kubernetes/helm#2863]
So, here's the broken thing:

1. I run `helm repo index`.

2. The index is calculated based on the charts I put in the directory.

3. I have two charts, one called e.g. a-0.9.0.tgz and one called e.g. a-0.19.0.tgz . 

4. When I run `helm install <myrepo>/a`, It installs a-0.9.0.tgz, *every time*, even though 0.19.0.tgz is newer.

This is because `helm repo index` sorts entries [lexicographically](https://github.com/kubernetes/helm/blob/master/pkg/repo/index.go#L143), and `0.9.0` happens to sort by that measure before `0.19.0` does:

```
// SortEntries sorts the entries by version in descending order.
//
// In canonical form, the individual version records should be sorted so that
// the most recent release for every version is in the 0th slot in the
// Entries.ChartVersions array. That way, tooling can predict the newest
// version without needing to parse SemVers.
func (i IndexFile) SortEntries() {
	for _, versions := range i.Entries {
		sort.Sort(sort.Reverse(versions))
	}
}
```
Please, please help. This is making me very sad, and if it isn't fixed I don't know what I'll do. My whole system was designed around the idea that `helm install` would give me the latest version of some package, as is specified [in the docs](https://docs.helm.sh/helm/#helm-install):

> When you use a chart reference (‘stable/mariadb’), Helm will look in the local configuration for a chart repository named ‘stable’, and will then look for a chart in that repository whose name is ‘mariadb’. **It will install the latest version of that chart** unless you also supply a version number with the ‘–version’ flag.

Thank you for your help.

**Comment by jascott1** [comment]
@djhaskin987 I have not been able to reproduce this with 2.6.0. I packaged 2 charts with versions 0.9.0 and 0.19.0. The index file was sorted correctly and the install command gave me the latest.

```
apiVersion: v1
entries:
  foo:
  - apiVersion: v1
    created: 2017-08-29T00:21:34.111248175Z
    description: A Helm chart for Kubernetes
    digest: c38096e20520388cee5d491659e0d13646ba411914b4060fe49cd974215ae3ce
    name: foo
    urls:
    - foo-0.19.0.tgz
    version: 0.19.0
  - apiVersion: v1
    created: 2017-08-29T00:21:34.111555415Z
    description: A Helm chart for Kubernetes
    digest: 05bff0860d4c05d57c5bb8258ed35bff094d5488059dd50bbfc1006f9571a85b
    name: foo
    urls:
    - foo-0.9.0.tgz
    version: 0.9.0
generated: 2017-08-29T00:21:34.110749692Z
```

Is there any chance the index.html is corrupt or you have two repos with same address?
