### ISSUE TITLE
[feature] have section in `Chart.yaml` for chart's requirements

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#2869]
where you can specify required nodes spec, and other necessary requirements chart needs to function properly after install:
```
requirements:
  node:
    cpu: 2
    ram: 2GB
  extra:
    k8sVersion: 1.7
    rbac: true
```
Use cases:
CI/CD can check that `requirements` section and bootstrap/update the cluster to match it.
Installing via UI as Monocular could show the message to the user with chart's `requirements`

**Comment by rimusz** [comment]
cc @prydonius @technosophos

**Comment by jascott1** [comment]
@rimusz How is this different from labels/taints etc in k8s?

**Comment by rimusz** [comment]
it is just a spec chart needs to have, and is more more for CI/CD and humans

**Comment by prydonius** [comment]
Should Helm fail or warn if requirements are not met?

This would be a great place to indicate the versions of kubernetes a chart supports as well. This is something that was discussed in #1001 but not implemented.

**Comment by rimusz** [comment]
+1 for `to indicate the versions of kubernetes a chart supports`
In most of cases Helm should not fail, but warning would be good to have.
In case of RBAC, k8s version helm should fail.

**Comment by rimusz** [comment]
```
requirements:
  kubernetesVersion: ">1.2.1"     # SemVer range that must be satisfied. Default is '*' (any)
  requires:
    - v1                          # this will be implicit, and default.
    - batch/v1                    # A few built-ins
    - extensions/v1beta1
    - foo.example.com/v1 
    
  node: # {} if nothing set
    count: 2
    cpu: 2
    ram: 2GB
  
  app: # {} if nothing set
    rbac: true
    namespace: gitlab
    storage: true
    loadbalancer: true

    valuesEditRequired: 
      gitlabUrl: true
      runnerRegistrationToken: true
```
@prydonius what do think ^^?
