### ISSUE TITLE
Upgrading statefulset affinity from annotation to spec.affinity fails from k8s 1.5 -> 1.6

### ISSUE THREAD

**Issue by PhilippeDupont** [kubernetes/helm#2945]
# Problem
I just migrated my cluster from k8s 1.5 to 1.6 and I have to upgrade my zookeeper chart to use spec.affinity instead of 1.5 annotations.

`Error: UPGRADE FAILED: StatefulSet.apps "zk" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' and 'containers' are forbidden.`

# Question
How can I proceed to upgrade the chart without deleting existing zookeeper cluster? 
from 
```
annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "podAntiAffinity": {
          "requiredDuringSchedulingIgnoredDuringExecution": [
            {
              "labelSelector": {
                "matchExpressions": [
                  {
                    "key": "app",
                    "operator": "In",
                     "values": ["zk-headless"]
                  }
                ]
              },
              "topologyKey": "kubernetes.io/hostname"
            }
          ]
        }
}
```
to
```
affinity:
  podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values: 
                  - zk-headless
  topologyKey: "kubernetes.io/hostname"
```
