### ISSUE TITLE
incomplete/incorrect reference resolution in values.yaml

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/helm#2963]
given a `values.yaml`:

```

site-name: &fqdn arbitrary-value

Env:
  -
    name: SITE_FQDN
    value: *fqdn

```

Using an unadulterated  deployment (`helm install --name=deployment-name path/to/chart` or `helm upgrade deployment-name path/to/chart` the reference is properly dereferenced.

Unfortunately the following does not work:

```
helm upgrade deployment-name --set=site-name=some-other-arbitrary-value /path/to/chart
```

results in `site-name` being properly set to `some-other-arbitrary-value`; however, `*fqdn` is still dereferenced to `arbitrary-value`.

versions:
```
:# helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

:# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by bacongobbler** [comment]
`--set` overwrites existing fields in a chart's values *after* it has already been parsed by the YAML parser, so how this behaviour occurs makes sense.

There have been several questions around how users can reference fields elsewhere in values.yaml using the go template engine, but I think it'd be better if we can support native YAML syntax. Perhaps we can fix this in core, but one way to test the behaviour and test a fix would be to make a PR against [`helm template`](https://github.com/kubernetes/helm/blob/master/cmd/helm/template.go) to merge in the values into the chart's values before loading it. If you're willing to fix this, go for it!

**Comment by gladiatr72** [comment]
Hrm... well, according to the [YAML 1.2 spec](http://www.yaml.org/spec/1.2/spec.html) under Section 2.2 (Structures):

> repeated nodes (objects) are first identified by an anchor (marked with the ampersand - “&”), and are then aliased (referenced with an asterisk - “*”) thereafter.

given example:
```yaml
Example 2.10.  Node for “Sammy Sosa”
appears twice in this document

---
hr:
  - Mark McGwire
  # Following node labeled SS
  - &SS Sammy Sosa
rbi:
  - *SS # Subsequent occurrence
  - Ken Griffey
```

Meh.  Definitely not a solution, per-se.  I'm sure there is some quite valid reasons for patterning kubernete's config schemas after XML (c'mon... lists of single-element dictionaries for environment variables?)  

**actual question**


With `values.yaml` containing:

```yaml

Env:
  -
    name: KUBECONFIG
    value: /path/to/config
  -
    name: DB_HOST
    value: postgres

```
...is there a way to reference nodes in a list of single element dicts by name for the purposes of setting deployment-specific variables? ("No" is better than jsonpath (< makes me want to cut myself))

When I remembered about the whole YAML reference thing, I thought surely that would be a solution, but I understand why it is not.

I've considered expressing environment variable stacks in `values.yaml` as:

```yaml

Env:
   KUBECONFIG: /path/to/config
   DB_HOST: postgres
   ETC: and soforth

```

...and then unwinding them using gotpl, but part of the reason for replicating the container environment structure is so this will work for expressing init-containers:

```
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "migrate",
            "image": "{{ .Values.Image }}:{{ .Values.ImageTag }}",
            "command": ["sh", "-c", "/usr/local/bin/python /code/manage.py migrate || sleep 1000"],
            "env": {{ toJson .Values.Env }},
            "volumeMounts": {{ toJson .Values.DjangoVolumeMounts }}
          },
          {
            "name": "collectstatic",
            "image": "{{ .Values.Image }}:{{ .Values.ImageTag }}",
            "command": ["sh", "-c", "/usr/local/bin/python /code/manage.py collectstatic --noinput || sleep 1000"],
            "env": {{ toJson .Values.Env }},
            "volumeMounts": {{ toJson .Values.DjangoVolumeMounts }}
          }
      ]'

```

Granted, after upgrading to 1.8 this will be **less** of an issue with init-containers (expressing them in their non-beta/alpha form pre-1.8 is almost completely broken) but it will still require horrid gotpl shenanigans to transform `{k:v, k2: v, k3: v}` into `[{name: k, value: v}, {name: k2, value: v}, etc]`.
