### ISSUE TITLE
error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by rguthriemsft** [kubernetes/helm#2979]
I was going through the getting started and in the section on flow control and if a value is commented out in my values.yaml (in this case the drink attribute), adding flow control eq operator throws an error like below when I run:

`helm install --debug --dry-run <My Chart>`

Output:
`Error: render error in "mychart/templates/configmap.yaml": template: mychart/templates/configmap.yaml:9:8: executing "mychart/templates/configmap.yaml" at <eq .Values.favorite....>: **error calling eq: invalid type for comparison**`

**configmap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{ if eq .Values.favorite.drink "coffee" }}mug: true{{ end }}
```

**values.yaml**

```
favorite:
  #drink: coffees
  food: pizza
```
                           
Is this a bug or am I missing something?

**HELM VERSION INFO:**
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
This is a side effect of Go's text/template package. If a value is unset, it is returned as a nil value. So really what you want to do in this case is

```
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{ if .Values.favorite.drink and eq .Values.favorite.drink "coffee" }}mug: true{{ end }}
```

If values are considered "optional", the chart should check and determine if the value is unset first.

Hope this helps!
