### ISSUE TITLE
helm search error with prelease versions that contains upper case characters

### ISSUE THREAD

**Issue by bbaribeau** [kubernetes/helm#3088]
running ```helm search local/foo --versions``` fails when any of the versions contains upper case characters in the prerelease identifier.

To reproduce, use the following index.yaml:
```yaml
apiVersion: v1
entries:
  foo:
  - created: 2017-10-05T14:09:16.836314814-04:00
    description: Sample
    digest: cc33d14057547854591b210b920dd67647690b6ee731a89f36d135fcc99f490f
    name: foo
    urls:
    - http://localhost:8879/foo-16.0.0-Alpha.tgz
    version: 16.0.0-Alpha    
  - created: 2017-10-05T14:09:16.836314814-04:00
    description: Sample
    digest: cc33d14057547854591b210b920dd67647690b6ee731a89f36d135fcc99f490f
    name: foo
    urls:
    - http://localhost:8879/foo-16.0.0-Beta.tgz
    version: 16.0.0-Beta       
generated: 2017-11-02T10:25:46.654821464-04:00
```

Running ```helm search local/foo --versions``` gives the following:
```
$ helm search local/foo --versions
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1340ebf]

goroutine 1 [running]:
k8s.io/helm/cmd/helm/search.scoreSorter.Less(0xc0427709c0, 0x2, 0x2, 0x1, 0x0, 0x20)
        /go/src/k8s.io/helm/cmd/helm/search/search.go:217 +0xff
k8s.io/helm/cmd/helm/search.(*scoreSorter).Less(0xc04308dea0, 0x1, 0x0, 0x18)
        <autogenerated>:3 +0x7a
sort.insertionSort(0x205aa60, 0xc04308dea0, 0x0, 0x2)
        /usr/local/go/src/sort/sort.go:29 +0x78
sort.quickSort(0x205aa60, 0xc04308dea0, 0x0, 0x2, 0x4)
        /usr/local/go/src/sort/sort.go:211 +0x1f2
sort.Sort(0x205aa60, 0xc04308dea0)
        /usr/local/go/src/sort/sort.go:220 +0x80
k8s.io/helm/cmd/helm/search.SortScore(0xc0427709c0, 0x2, 0x2)
        /go/src/k8s.io/helm/cmd/helm/search/search.go:193 +0x74
main.(*searchCmd).run(0xc042494280, 0xc042335400, 0x1, 0x2, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/search.go:90 +0xaf
main.newSearchCmd.func1(0xc0422ea480, 0xc042335400, 0x1, 0x2, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/search.go:61 +0x7c
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc0422ea480, 0xc042335080, 0x2, 0x2, 0xc0422ea480, 0xc042335080)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3f0
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04244a240, 0xc04203bb00, 0xc042202000, 0xc042202240)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x340
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04244a240, 0x3, 0x3)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x32
main.main()
        /go/src/k8s.io/helm/cmd/helm/helm.go:155 +0x7e
```
According to [SemVer](http://semver.org/) rules the prerelease identifier is allowed to contain upper case characters.
