### ISSUE TITLE
Proposal: Create helm/tiller operator

### ISSUE THREAD

**Issue by burdiyan** [kubernetes/helm#3089]
Right now there is no easy and blessed way for configuring a set of Helm releases to be deployed in Kubernetes cluster. There is no way to express the desired state of a release.

Although there are tools like https://github.com/roboll/helmfile and https://github.com/eneco/landscaper that allow to achieve something similar, these are not ideal.

I propose to create an Operator for Helm/Tiller that runs in the cluster and can manage custom resources that would describe Helm releases.

This would allow to describe the desired state (the thing we used to so much with Kubernetes) for Helm releases.

Users could submit these resources with plain `kubectl create/apply` and Operator would rollout the desired release across the cluster.

I can see a structure similar to something like:

```
apiVersion: helm.sh/v1
kind: Release
metadata:
  name: nginx-ingress
  namespace: kube-public
spec:
  chart: stable/nginx-ingress
  reuseValues: true
  values:
    rbac:
      create: true
...
```

There are a lot of things to take into account, but I guess this will be helpful for many people.
