### ISSUE TITLE
Helm YAML parser ignores quotes

### ISSUE THREAD

**Issue by kedare** [kubernetes/helm#3137]
When trying to set for example this values.yaml file :

```
replicaCount: 2
image:
  repository: gcr.io/xxx/templates-ssr
  tag: latest
  pullPolicy: Always
service:
  name: templates-ssr
  type: ClusterIP
  externalPort: 80
  internalPort: 5050
ingress:
  enabled: yes
  hosts: ["*-npreview.xxx.com"]
  annotations:
    kubernetes.io/ingress.class: traefik
resources:
  limits:
   cpu: 0.5
   memory: 256Mi
  requests:
   cpu: 0.2
   memory: 128Mi
```

```helm lint``` fail with 
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/ingress.yaml: unable to parse YAML
        error converting YAML to JSON: yaml: line 13: did not find expected alphabetic or numeric character

Error: 1 chart(s) linted, 1 chart(s) failed
```

It looks like helm completely strip quotes, making impossible to use wildcards or regexes with escaping (\. for example) instead of yaml files

```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
this might be solved when someone implements `helm lint` to use the kubernetes spec parser instead in #2575. Some more background context can also be found in #1741.

**Comment by lcostea** [comment]
I found a workaround for this: I moved the value with wildcard in the values.yaml, created a helper and applied the quote function to it, something like:
{{- printf "%s" .Values.ingress.hosts | quote -}}
And I see the ingress host is applied correctly.

**Comment by RiceBowlJr** [comment]
You can actualy put quotes around your call like so:
Template:
```
spec:
  concurrencyPolicy: "Allow"
  failedJobsHistoryLimit: {{ .Values.job.failedHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  schedule: "{{ .Values.job.schedule }}"
```

`values.yaml`:
```
job:
  failedHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  schedule: "* * * * *"
```

It's dirty but it works and still better than printf a variable I think ^^
