### ISSUE TITLE
Installing charts with --repo option from a repo with relative paths fails

### ISSUE THREAD

**Issue by hoesler** [kubernetes/helm#3168]
I have a repository index with relative paths:
```
  spark:
  - apiVersion: v1
    created: 2017-11-20T08:24:41.035796831Z
    description: A Helm chart for Kubernetes
    digest: 7d9c80037b56ef684dd0805d0c1f9a7ac36139a8aa331035844e82a7c229e3a1
    name: spark
    urls:
    - spark-0.1.1.tgz
    version: 0.1.1
```

When I run `helm install spark --repo http://my-helm-repo` I get 
```
Error: Non-absolute URLs should be in form of repo_name/path_to_chart, got: spark-0.1.1.tgz
``` 

I expected that the chart would be resolved relative to the repo url, but they apparently it did not.

Tested with helm 2.6.2, 2.7.0 and 2.7.2.
