### ISSUE TITLE
Overwrite names of dependecies of subcharts

### ISSUE THREAD

**Issue by cgebe** [kubernetes/helm#3186]
I am encountering the following problem:

I want to deploy an umbrella chart which holds two subcharts, each subchart is a microservice which uses mysql as database. So mysql is a dependency in each subchart. Now i do want to deploy two seperate mysql charts in my system. When i try to install the umbrella chart, i get the message that {Release}-mysql templates are already deployed. `Error: release test failed: secrets "test-mysql" already exists`

```
./
└── charts
    ├── microservice-1
    │   ├── charts
    │   │  └── mysql
    │   └── templates
    └── microservice-2
        ├── charts
        │   └── mysql
        └── templates
```

Therefore, i need a way to deploy both mysql charts of the subcharts with a different name, only when deployed via umbrella chart. Overwriting the name of the mysql charts of the subcharts is not possible via values.yaml of the umbrella chart:

```
## Overwrite
microservice-1:
    mysql:
        name: microservice-1-mysql
microservice-2:
    mysql:
        name: microservice-2-mysql
```

Stating aliases in requirements.yaml files of the subcharts does not take effect in this scope.
What can i do?
