### ISSUE TITLE
Possible to pass multiple objects to a named template?

### ISSUE THREAD

**Issue by ninadpage** [kubernetes/helm#3215]
For a named template, is there any way to pass multiple parameters/scopes, or a struct $variable composed from multiple values?
The problem I'm trying to solve is this:

1. My values.yaml (effective):
```
# ...
hostWorkspacePath: /path/to/workspace

serviceName:
  image: image-url
  dirName: service-name
  appMountFromHost: true
# there are multiple such definitions for different services with same structure
```

2. I have a named template as follows:
```
{{- define "service_app_volume_excl_header" }}
{{-   if .appMountFromHost }}
{{-     $workspaceRoot := required "Values.hostWorkspacePath is required!" $.Values.hostWorkspacePath }}
- name: app-vol
  hostPath:
    path: {{ $workspaceRoot }}/.dirName
    type: Directory
{{-     end }}
{{- end -}}
```

3. I include it in a Deployment manifest as follows:
```
# ...
      volumes:
      {{- include "service_app_mount_excl_header" .Values.serviceName | indent 6 -}}
      # I intend to reuse this in manifests of multiple services, substituting .Values.serviceName
# ...
```

However, `$.Values.hostWorkspacePath` cannot be resolved, since the root context inside the named template is set to `.Values.serviceName`.
https://stackoverflow.com/a/38536512 says that a Go template can accept struct, but I couldn't find a way to assign a struct to a $variable in Helm.
What are my options?
