### ISSUE TITLE
Templating advice

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3292]
Hey, I'm trying to use a dynamic key in my template to access a subset of data depending on my target environment.  This is being used to generate ConfigMaps which differ depending on the `--set targetEnviroment=<thing>` that is passed.

Imagine in my values.yaml I have:
```
targetEnvironment: dev

environment:
  dev:
    - name: some-key
      value: some-value

  test:
    - name: some-key
      value: some-other-value

  prod:
    - name: some-key
      value: a different value
```

And in my template I want to access just the key of `environment` that matches `targetEnvironment`, I'd imagine I'd need to do something like this (but this doesn't work)
```
{{ toYaml .Values.environment[.Values.targetEnvironment] | indent 8 }}
```

Can anyone point me in the right direction?
