### ISSUE TITLE
Proposal: RBAC best-practices changes

### ISSUE THREAD

**Issue by omkensey** [kubernetes/helm#3320]
(Ref: RBAC comments in jetstack/cert-manager#229, Helm issue #3098)

In discussion of a Jetstack PR, I have come to believe we need to at least update the best practices doc for RBAC in charts, and possibly refactor those practices.

The bit that needs updating is the current assertion that "serviceAccountName is effectively a required value".  It should be optional, but generated to a unique name if not specified.

However, additional cases not handled by the current practice are:
* a service account already exists, and a new release should create RBAC or other resources that use it
* a service account should be created for an RBAC-enabled chart even when RBAC is not being used

In the Jetstack PR discussion, it was proposed that service account values should be split out from RBAC (since they are used by RBAC but exist independently of it) and created or not independently, e.g.:

```
rbac:
  create: true

serviceAccount:
  create: false
  serviceAccountName: "foo"
```

This adds a bit of complexity, but resolves the issue described above, and additionally allows charts to specify and use multiple service accounts if we add a layer under `serviceAccount` like so:

```
serviceAccounts:
  client:
    serviceAccountName: client-account
    create: false
  server:
    serviceAccountName: server-account
    create: true
```

My personal feeling is that the additional functionality, especially of the second form, is worth the small added complexity.

**Comment by technosophos** [comment]
I agree with this. I think we should actually alter the Tiller installer to do this. I don't _think_ this introduces any compatibility breakers. And we do this same thing with Brigade (add svc account by default, even if no RBAC), which seems to work for all users.

**Comment by unguiculus** [comment]
@omkensey I thought it through again and think the proposal makes sense. I updated the PR accordingly. Please have a look at this commit: https://github.com/jetstack/cert-manager/pull/229/commits/52f2c90b33a8857d2358ff99e75919e888ca9405

**Comment by unguiculus** [comment]
I went for a slightly shorter version:

```yaml
rbac:
  create: true

serviceAccount:
  create: false
  name: "foo"
```
