### ISSUE TITLE
helm install with multiple --set parameters (maybe missing documentation)

### ISSUE THREAD

**Issue by chucky2305** [kubernetes/helm#3351]
```
#values.yml
namespace: defaultnamespace
secrets:
   database: defaultdatabase
   password: defaultpassword
```

`helm install mychart --set secrets.database=mydatabase --set secrets.password=mypassword`
This will only change the value for password. database will still remain with "defaultdatabase"

This is the correct way to pass two values that lie under the same node in values.yaml
`helm install chartsendis --set secrets.database=mydatabase,secrets.password=mypassword`

What i found out later. Calling
`helm install chartsendis --set secrets.database=mydatabase,secrets.password=mypassword --set namespace=anothernamespace`

doesn't work either. In this case only "namespace" is set to "anothernamespace". both values from "secrets" remain in their default values.

If this happends by design, i maybe just did not find the documentation for this. If it is missing i could help you to make it more clear in the documentation.

Greetings,
Chucky
