### ISSUE TITLE
Template names are not namespaced by dependency

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3366]
Hi, 
I've noticed that if two dependencies use the same template names, then the latter of the two is used in both chart renders.

For example, I have the following requirements.yaml:

```
❯ cat requirements.yaml
dependencies:
- name: helm-infra-elasticsearch
  version: "0.1.0"
  repository: "@aws"
- name: helm-infra-nginx-ingress
  version: "0.1.0"
  repository: "@aws"
```

However, both of these repos by change define the same thing:
```
❯ grep -ir 'standard.container' .
./charts/helm-infra-elasticsearch/templates/deployments/_standardContainer.tpl:{{- define "standard.container" -}}
./charts/helm-infra-nginx-ingress/templates/_helpers.tpl:{{- define "standard.container" -}}
```

Therefore, when I render elasticsearch:
```
❯ helm template . --execute charts/helm-infra-elasticsearch/templates/deployments/data.warm.reserved.yaml
```

It actually uses "standard.container" from `helm-infra-nginx-ingress`.

I would suggest that templates of child dependencies cannot leak outside the scope of the dependency.  For now, I think we'll work around it with naming conventions, however that doesn't help us when consuming public charts.
