### ISSUE TITLE
Resource with `.Release.IsInstall` deleted on helm upgrade

### ISSUE THREAD

**Issue by komljen** [kubernetes/helm#3442]
Not sure if this expected, but I have a docker registry secret added like this:
```
{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "test.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
```

Then, if I run the upgrade this resource is deleted? Helm v2.8

**Comment by komljen** [comment]
This is expected, solved it with hook:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "test.fullname" . }}-registry
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
```
