### ISSUE TITLE
dnsPolicy ommited

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/helm#3466]
When I deploy an helm chart (or update) with a custon `dnsPolicy`, it is not applied to my deployment.
It stays: `dnsPolicy: ClusterFirst`

```
helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

**Comment by jascott1** [comment]
@pierreozoux The initial install should definitely be correct or something is wrong with your chart. Can you share you values and relevant template? Also you can test locally with `helm template`.

**Comment by pierreozoux** [comment]
I ran locally, I saw the `dnsPolicy: Default` but if I run this on the initial install on a real cluster, it is not there.
I think it is a bug.

**Comment by bacongobbler** [comment]
do you have a sample chart which we can test against to reproduce your issue?

**Comment by pierreozoux** [comment]
just deployed again, and can see again the issue.
The chart is simple. Nothing fancy, here the deploy for instance:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "50%"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "xxx:{{ .Values.image.tag }}"
          dnsPolicy: Default
          resources:
            requests:
              cpu: "{{.Values.cpuRequests}}"
              memory: "{{.Values.memoryRequests}}"
            limits:
              cpu: "{{.Values.cpuLimit}}"
              memory: "{{.Values.memoryLimit}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8020
          readinessProbe:
            httpGet:
              path: /health
              port: 8020
            initialDelaySeconds: 3
            timeoutSeconds: 3
          env:
            - name: K8S_ENV
              value: "true"
            - name: NODE_ENV
              value: {{ .Values.env.env }}
            - name: CACHE_REDIS_HOST
              value: {{ .Values.env.cache_redis_host  }}
            - name: CACHE_REDIS_PORT
              value: "{{ .Values.env.cache_redis_port }}"
```
If you want to see other resources, let me know, I can also put them here, or somewhere else that could be more convenient.
