### ISSUE TITLE
Document Tiller's default "allow everyone" policy better

### ISSUE THREAD

**Issue by xeor** [kubernetes/helm#3545]
There need to be better documentation and awareness around the fact that tiller allows everyone to talk to it as default, also from inside the cluster.
I first thought that there wasn't a way to talk to tiller from inside the cluster, but setting `HELM_HOST="tiller-deploy.kube-system:44134"`, then using the normal helm client proved me wrong.

This should be warned about! Else tiller might be an easy way to take over the cluster from a random container.

A NetworkPolicy that blocks all is helping:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tiller-deny-all
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: helm
      name: tiller
  policyTypes:
  - Ingress
```

It still allows me to run helm from my admin-pc.

I did also find some docs about setting up tls between helm and tiller. But I really don't think many are following them. Specially when it contains a lot of `openssl ...` commands.

Maybe a revisit on the authentication model for helm/tiller is in scope?
