### ISSUE TITLE
ConfigMap failed to deploy when using pre-install hook, but I can see it did deploy

### ISSUE THREAD

**Issue by meeech** [kubernetes/helm#3548]
I have a chart where I'm trying to deploy a configmap on pre-install. 
When I run `helm upgrade --install` the deploy fails with `"Error: Failed to deploy name-of-config-map"` but when I look at config maps, I can see that my map has properly deployed. 

helm version: 2.7.2 & 2.8.1 (tried upgrading to see if that would solve, same issue) Let me know what other details I can provide

**Comment by InAnimaTe** [comment]
can you `--debug --dryrun` to give us more details on whats going on? Could it be the configmap exists already because you aren't using template name (but instead a static name) etc..?

**Comment by meeech** [comment]
@InAnimaTe I'll try to make a small repro chart to share. This config map is largish (using it to mount some init sql) I know when I run the upgrade install command, i start with a 'clean slate' in my cluster - nothing deployed. 
Can you expand what you mean re: template name vs static name? 
the configmap metadata is this:
```
metadata:
  creationTimestamp: 2018-01-18T03:17:38Z
  name: base-schema
  namespace: {{.Release.Namespace}}
  resourceVersion: "152509"
  uid: 23388ea1-fbfe-11e7-9188-0800274db7fc
  annotations:
     "helm.sh/hook": pre-install
     "helm.sh/hook-weight": "-10"
```
and I mount it like so:

```      
      - name: schema-init-sql
        configMap:
          name: base-schema
          items:
          - key: schema_novalib.sql
            path: init.sql
```
