### ISSUE TITLE
Is it possible to access {{ .Release.Name }} from within a chart values.yaml ?

### ISSUE THREAD

**Issue by skalfyfan** [kubernetes/helm#3558]
I am trying to define something like the following in a parent chart:
```
# Parent Chart: values.yaml 
global:
  config:
    brokerUrl: "https://someone:something@{{ .Release .Name }}-rabbitmq:5632"
```

Am then trying to get this value thrown into a _ConfigMap_ defined in a sub chart of this parent chart.

In a sub chart _ConfigMap_ I have something like the following:
```
data:
  brokerUrl: "{{ .Values.global.config.brokerUrl | default .Values.config.brokerUrl }}"
```

The problem is that when deployed this is always the string literal:
`"https://someone:something@{{ .Release .Name }}-rabbitmq:5632`

`{{.Release.Name}}` was ignored. As `{{.Release.Name}}` is a pre-defined value I'm a little surprised this isn't supported?  Any suggestions?

**Comment by SlickNik** [comment]
Thanks for the response @eicnix! 👍 
@skalfyfan Let us know how that works for you, and if using the `tpl` function addresses your use case. Thanks!

**Comment by skalfyfan** [comment]
😞 

@SlickNik This actually did not work for me, but thanks for the suggestion @eicnix! Note that my question was specifically for the _values.yaml_ file.

The template helpers though are how I got around my issue. I ended up creating a definition in my template helpers, something like the following in my parent chart:
```
{{/*
Generate our broker URL for RabbitMQ.
*/}}
{{- define "message-broker.url" -}}
{{- printf "amqp://someone:something@%s-rabbitmq:5672" .Release.Name -}}
{{- end -}}
```

I then defined the exact same definition within my sub charts. As it turns out, the parent helper template definitions override the sub charts, but I can still easily extract a sub chart out and run it on it's own! Win win.

**Comment by kv0824** [comment]
I don't know why @eicnix eicnix is not taken. This question firstly misled me. Finally I figured out the tpl function should help. I copied the Helm Document: The tpl function allows developers to **evaluate strings as templates inside a template**.

Though we cannot get .Release.Name in value.yaml file. But the value in value.yaml will be consumed in  ConfigMap in this question. And then .Release.Name will be evaluated to strings in the ConfigMap template.

Let's go back to the original question:
ConfigMap
`data:
  brokerUrl: "{{ tpl (.Values.global.config.brokerUrl | default .Values.config.brokerUrl) . }}"
`
value.yaml
`
global:
  config:
    brokerUrl: "https://someone:something@{{ .Release .Name }}-rabbitmq:5632"
`

Finally, when Helm deploy the ConfigMap, the brokerUrl will be:
"https://someone:something@releasename-rabbitmq:5632"

**Comment by sc250024** [comment]
@eicnix  How would this work for `affinity` rules? For example, in the `nginx-ingress` chart, they have the following for the `affinity` block: https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L187-L190

I would like to populate a soft `podAntiAffinity` using the following in my `values.yaml` file:

**values.yaml**
```yaml
controller:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          topologyKey: failure-domain.beta.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app: {{ template "nginx-ingress.name" . }}
              release: {{ .Release.Name }}
```

However, this gives an error. Could the same trick be used here? And if so, how?
