### ISSUE TITLE
Passing an array to helm

### ISSUE THREAD

**Issue by r-divakaran** [kubernetes/helm#3570]
Hello,

As per https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set and also I checked through https://github.com/kubernetes/helm/issues/1987 I am trying to pass http headers using set to the helm command. 

`$ helm install chartname --name=testinstance --set image.name=test --set image.tag=latest --set headerRule={"a\ b,c\ d"}`

the  relevant part of template file is like 

```
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
            {{- if .Values.headerRule -}}
              headerRule:
              {{- range .Values.headerRule }}
              - {{ . }}
              {{- end }}
            {{- end }}
```

when I execute above helm command it results in

```
spec:
  rules:
    - host: test.kube.test.com
      http:
        paths:
          - path: /
            backend:headerRule
              - a b
              - c d
              serviceName: test-kube-test
            servicePort: 8888
```

But the one am desiring or trying to get is
```
spec:
  rules:
    - host: test.kube.test.com
      http:
        paths:
          - path: /
            backend:
             headerRule:
               - a b
               - c d
              serviceName: test-kube-test
              servicePort: 8888
```

Could someone please help !?

Thanks,
Raju.
