### ISSUE TITLE
Helm dep build : Error: chart metadata (Chart.yaml) missing

### ISSUE THREAD

**Issue by hmagph** [kubernetes/helm#3585]
Helm 2.8.1

Getting an error from **helm dep build** trying to build an umbrella chart using local charts repo within a CI engine. (Note the dependencies are located outside the umbrella chart repository according to https://github.com/kubernetes/helm/issues/2887).

Is this Helm misbehaving here ?

```
> helm dep build umbrella-chart/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Save error occurred:  chart metadata (Chart.yaml) missing
Deleting newly downloaded charts, restoring pre-update state
Error: chart metadata (Chart.yaml) missing
```

File structure is:
- charts/
  - index.yaml
  - catalog-api-1.0.3.tgz
  - orders-api-1.0.2.tgz
  - ui-1.0.2.tgz
- umbrella-chart/
  - Chart.yaml
  - requirements.yaml

charts/index.yaml
```
apiVersion: v1
entries:
  catalog-api:
  - apiVersion: v1
    created: 2018-03-01T10:00:20.883794+01:00
    description: A Helm chart for a Kubernetes app
    digest: 93081e18081b6cd1a19a77a48da6f71cf50a0bd08f3d1152af9112dfba78bc48
    name: catalog-api
    urls:
    - catalog-api-1.0.3.tgz
    version: 1.0.3
  orders-api:
  - apiVersion: v1
    created: 2018-03-01T10:00:20.884032+01:00
    description: A Helm chart for a Kubernetes app
    digest: 746851622a1cd48edf2c471a65e2d7ee09344d578819f83480d7a5afc177358c
    name: orders-api
    urls:
    - orders-api-1.0.2.tgz
    version: 1.0.2
  ui:
  - apiVersion: v1
    created: 2018-03-01T10:00:20.884288+01:00
    description: A Helm chart for a Kubernetes app
    digest: 9d1076c4750b756227d9f6265ad759540eb5c745c9353a9711abcb5a865500e8
    name: ui
    urls:
    - ui-1.0.2.tgz
    version: 1.0.2
generated: 2018-03-01T10:00:20.881161+01:00
```

umbrella-chart/Chart.yaml
```
apiVersion: v1
description: Umbrella chart for online-store microservices application
name: umbrella-chart
version: 1.0
```

umbrella-chart/requirements.yaml
```
dependencies:
  - name: catalog-api
    version: ">=1.0.0"
    repository: file://../charts
  - name: orders-api
    version: ">=1.0.0"
    repository: file://../charts
  - name: ui
    version: ">=1.0.0"
```

**Comment by hmagph** [comment]
Here is a zip of the files, in case it helps figuring: 
[solution-helm-microservices-20180228121049676.zip](https://github.com/kubernetes/helm/files/1770845/solution-helm-microservices-20180228121049676.zip)

**Comment by hmagph** [comment]
Trying things... tweaking the `charts/index.yaml` to leverage local file repo url doesn't help

Tried to have relative file path:
```
apiVersion: v1
entries:
  catalog-api:
  - apiVersion: v1
    created: 2018-03-01T12:02:09.339578+01:00
    description: A Helm chart for a Kubernetes app
    digest: 93081e18081b6cd1a19a77a48da6f71cf50a0bd08f3d1152af9112dfba78bc48
    name: catalog-api
    urls:
    - file://catalog-api-1.0.3.tgz
    version: 1.0.3
  orders-api:
  - apiVersion: v1
    created: 2018-03-01T12:02:09.339792+01:00
    description: A Helm chart for a Kubernetes app
    digest: 746851622a1cd48edf2c471a65e2d7ee09344d578819f83480d7a5afc177358c
    name: orders-api
    urls:
    - file://orders-api-1.0.2.tgz
    version: 1.0.2
  ui:
  - apiVersion: v1
    created: 2018-03-01T12:02:09.339978+01:00
    description: A Helm chart for a Kubernetes app
    digest: 9d1076c4750b756227d9f6265ad759540eb5c745c9353a9711abcb5a865500e8
    name: ui
    urls:
    - file://ui-1.0.2.tgz
    version: 1.0.2
```

or paths relative to umbrella chart
```
apiVersion: v1
entries:
  catalog-api:
  - apiVersion: v1
    created: 2018-03-01T12:04:13.487591+01:00
    description: A Helm chart for a Kubernetes app
    digest: 93081e18081b6cd1a19a77a48da6f71cf50a0bd08f3d1152af9112dfba78bc48
    name: catalog-api
    urls:
    - file://../charts/catalog-api-1.0.3.tgz
    version: 1.0.3
  orders-api:
  - apiVersion: v1
    created: 2018-03-01T12:04:13.487849+01:00
    description: A Helm chart for a Kubernetes app
    digest: 746851622a1cd48edf2c471a65e2d7ee09344d578819f83480d7a5afc177358c
    name: orders-api
    urls:
    - file://../charts/orders-api-1.0.2.tgz
    version: 1.0.2
  ui:
  - apiVersion: v1
    created: 2018-03-01T12:04:13.488127+01:00
    description: A Helm chart for a Kubernetes app
    digest: 9d1076c4750b756227d9f6265ad759540eb5c745c9353a9711abcb5a865500e8
    name: ui
    urls:
    - file://../charts/ui-1.0.2.tgz
    version: 1.0.2
generated: 2018-03-01T12:04:13.487104+01:00
```

still getting the same error...

```
helm dep build umbrella-chart/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Save error occurred:  chart metadata (Chart.yaml) missing
Deleting newly downloaded charts, restoring pre-update state
Error: chart metadata (Chart.yaml) missing
```

**Comment by hmagph** [comment]
`helm dep up` doesn't work any better... so is this a bug in Helm ? I see other issues that look a bit similar

**Comment by eicnix** [comment]
If you use a `file://...` url for a requirement repository you need to point the url to the requirement itself instead of the folder that contains the requirement chart.  
Helm tried to build your requirements from the charts folder but couldn't find a `Chart.yaml` file directly in your charts folder which resulting in the error message you received.

This example works for me: 
```
dependencies:
  - name: catalog-api
    version: ">=1.0.0"
    repository: file://../charts/catalog-api
  - name: orders-api
    version: ">=1.0.0"
    repository: file://../charts/orders-api
  - name: ui
    version: ">=1.0.0"
    repository: file://../charts/ui
```
