### ISSUE TITLE
Passing the command through values

### ISSUE THREAD

**Issue by blaketastic2** [kubernetes/helm#3656]
I'm trying to figure out the syntax for passing the command to my deployment as an array. Here's what I've got:

deployment.yaml
```yaml
template:
  spec:
    containers:
    - name: {{ .Values.service.name }}
      command: {{ .Values.command }}
```

values.yaml
```yaml
command: ["java", "-jar", "/app.jar"]
```

I've played around with a few iterations of this, but can't figure out the syntax.

Thanks for the help
