### ISSUE TITLE
Debug output differs from deployed YAML using --set

### ISSUE THREAD

**Issue by kevinohara80** [kubernetes/helm#3674]
I'm currently running helm v2.8.2

I have a service template defined like this...

**service.yaml**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "auth-service.fullname" . }}
  labels:
    app: {{ template "auth-service.name" . }}
    chart: {{ template "auth-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{ if .Values.ambassador.enabled -}}
  ambassador:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      config:
        auth_service: "{{ template "auth-service.fullname" . }}:{{ .Values.service.port }}"
        path_prefix: {{ .Values.ambassador.path_prefix }}
  {{- end }}
...
```

And a values file that looks like this...

**values.yaml**

```yaml
service:
  type: ClusterIP
  port: 80

ambassador:
  enabled: true
  path_prefix: /jwt/validate
```

I first installed the chart and explicitly set the `ambassador.enabled` to false. 

```bash
$ helm install --name auth-service --set ambassador.enabled=false .
```

I got the correct `service.yaml` file deployed to kubernetes which excluded the `ambassador` block within the metadata block.

Later, I upgraded the release and explicitly set the `ambassador.enabled` to true like so.

```bash
$ helm upgrade auth-service --set ambassador.enabled=true .
```

The resulting service yaml doesn't get updated in kubernetes. If I run the above command with `--dry-run --debug`, I see the `ambassador` block render as expected. In kubernetes, it's not there. I also ran `get values` and confirmed that `ambassador.enabled=true`.

Any ideas what might be happening?
