### ISSUE TITLE
Pass .Files.Get through templating

### ISSUE THREAD

**Issue by carlpett** [kubernetes/helm#3746]
I'm generating a Secret with a template like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-configuration
type: Opaque
data:
  config.yaml: {{ .Files.Get "config.yaml" | b64enc }}
```

This has worked nicely. Now, I need to have the content of config.yaml actually be templated. Is this possible somehow?
That is, I want to have something like this in that file:

```yaml
main:
    name: {{ .Values.name }}
    ...
```
