### ISSUE TITLE
helm dependency update hangs forever

### ISSUE THREAD

**Issue by nerumo** [kubernetes/helm#3778]
I have a simple requirements.yaml with one dependency. As soon as I try to update the dependencies with `helm dependency update`, I get the following message on the console and it never completes:
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
```

I tried versions (all windows): 
- 2.8.2
- 2.8.0
- 2.7.2

My requirements.yaml
```
dependencies:
  - name: rabbitmq
    version: "0.6.26"
    repository: "@stable"
```

helm repo list
```
stable  https://kubernetes-charts.storage.googleapis.com
local   http://127.0.0.1:8879/charts
```
