### ISSUE TITLE
Question about the usage of condition in requirements.yaml

### ISSUE THREAD

**Issue by zwtj** [kubernetes/helm#3796]
Hi, I read the [docs](https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml) about the usage of `condition` in `requirements.yaml`. 

I have a question about the example in the docs below: when `global.subchart1.enabled` is used to control if `subchart1` is installed or not? When I tried it in action, I was surprised that `subchart1` was installed when `subchart1.enabled` was not specified at all and `global.subchart1.enabled` was set to `false` in `values.yaml`.
```
# requirements.yaml
dependencies:
      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        condition: subchart1.enabled, global.subchart1.enabled
```

If I understand the docs correctly, since `subchart1.enabled` is not specified (and therefore not a valid path), `helm install` will continue to check the value of  `global.subchart1.enabled`, which is false, and thus not install `subchart1`. Am I missing something?

**Comment by zwtj** [comment]
Hi @jascott1 

I do see `global.subchart1.enabled` to be `false` after `--dry-run --debug`. You may download and run my code here: https://github.com/zwtj/helm-example.

Steps:
> cd helm-example
> helm dep up chart
> helm install --dry-run --debug chart

You may find the output below that sets `global.subchart1.enabled` to false and installs `subchart1`:
```
COMPUTED VALUES:
global:
  subchart1:
    enabled: false
subchart1:
  global:
    subchart1:
      enabled: false

HOOKS:
MANIFEST:

---
# Source: chart/charts/subchart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: needled-zebra-cfgmap
data:
  dessert: whatever
```

Helm version I'm using:
```
$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

Is this a bug?
