### ISSUE TITLE
Helm incorrectly parses three dashes in YAML files

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/helm#3866]
Helm incorrectly assumes that a triple-dash combination separates documents, so even if I put three dashes in an IDN domain, it incorrectly splits a document into separate manifests.

I can't use Punycode domain name in an Ingress manifest.

YAML:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-idn-1
  annotations:
    {{- include "auth_url" . | indent 4 }}
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/proxy-body-size: 128m
spec:
  rules:
  - host: xn-----flckrvpb3h5b.xn--p1ai
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
```

Helm output:
```
`unexpected yaml data 
>>> START YAML
--flckrvpb3h5b.xn--p1ai
>>> END YAML
`
```
