### ISSUE TITLE
Cannot upgrade with --reuse-values when nested default option added

### ISSUE THREAD

**Issue by rcorre** [kubernetes/helm#3884]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```
Output of `kubectl version`:
```

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

# What's happening

When a new version of a chart adds a nested value to values.yaml and references it in a template, you cannot upgrade to that version with `--reuse-values`, even if no options have been customized from the defaults.

### `values.yaml`
```yaml
foo: "bar"
```

### `templates/configmap.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  foo: {{ .Values.foo }}
```

### `values.yaml`
```yaml
foo: "bar"
config:
  a:
    b: "foo"
```

### `templates/configmap.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  foo: {{ .Values.foo }}
  b: {{ .Values.config.a.b }}
```

# Steps:

1. `git checkout 0.1.0 && helm install . --name rodencor`
2. `git checkout 0.1.1 && helm upgrade rodencor . --reuse-values`

```
Error: UPGRADE FAILED: render error in "foochart/templates/configmap.yaml": template: foochart/templates/configmap.yaml:9:15: executing "foochart/templates/configmap.yaml" at <.Values.config.a.b>: can't evaluate field a in type interface {}
```

May be related to #3495 and #1579, but those both seem to be about `helm lint` whereas this is blocking an actual release.
