### ISSUE TITLE
[Question] Best practice allowing third-parties to dynamically create secrets

### ISSUE THREAD

**Issue by migueleliasweb** [kubernetes/helm#3953]
First let me explain what I mean by "third-party":
- Someone using the helm chart without directly changing the source code.
- Basically a `helm install --set somevar=somevalue mychart`

I would like to allow these users to configure the chart by adding files directly to the container by creating secrets and mounting them as files. 

So far I can see I have these options:

**1st option:** The third-party creates the secret from outside helm (using kubectl for example) and them passes the name into the chart:
The user would run this:
```bash
$ kubectl create secret generic user-custom-named-secret --from-file user/whatever/path/you/want.yaml
```

Then the helm chart would expect something like this:

``` $ helm install --set secret-name-for-the-configs=user-custom-named-secret [...]```

```yaml
[...]
spec:
      containers:
      - name: foo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: {{ .Values.secret-name-for-the-configs }}
            mountPath: /my-default-mount-location/
[...]
```

**2nd option:** The file gets read by helm and injected to the chart. Sadly, I could not make this one work as I wanted. Apparently the files need to sit inside the repo itself 
 and as I would like to avoid people forking the repo just to add some configurations this was not really suitable... See: https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md#basic-example

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: something-very-secret
type: Generic
data:
  config.yaml: |-
    {{ .Files.Get "config.toml" }}
```

**3rd option:** The user passes a file to helm with `-f path/to/value.yaml` and this same file contains inline the other file. Like `stable/prometheus` does. If possible I would also like to avoid this as this is a bit tricky for longer files.

```yaml
## alertmanager ConfigMap entries
##
alertmanagerFiles:
  alertmanager.yml: |-
    receivers:
      - name: my_receiver
        opsgenie_configs:
          - api_key: some_very_secret_api_key
    route:
      group_wait: 10s
      group_interval: 11s
      receiver: opsgenie
      repeat_interval: 3h
```

I tend to choose the first option due to the lack of a better one. ¯\_(ツ)_/¯

Is there any other/better way to achieve this ?
