### ISSUE TITLE
[Question] Can I reach files outside of chart folder with .Files.Glob 

### ISSUE THREAD

**Issue by idelix** [kubernetes/helm#4026]
My current solution (Java Spring Boot) has this dir structure:
```

solution directory
├───charts
│   └───gs-spring-boot-docker
│       ├───charts
│       ├───resources
│       └───templates
└───src
    ├───main
    │   ├───java
    │   │   └───hello
    │   └───resources
    └───test
        └───java
            └───hello
```

So my charts folder is inside:
c:\solution directory\charts\gs-spring-boot-docker
while the properties file which I'm trying to add to configmap is in:
c:\solution directory\src\main\resources\application-dev.yml

I want to avoid copying application-dev.yml to c:\solution directory\charts\gs-spring-boot-docker and rather just reach this file where is seats currently.

My Configmap definition looks like this - but I cannot get this to go outside only when I create resources folder inside c:\solution directory\charts\gs-spring-boot-docker then it worked.

is there a way to do something like this with glob patterns to go up through parent dirs ?
{{ (.Files.Glob "../../../resources/application-dev.yml").AsConfig | indent 2 }}

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gs-spring-boot-docker.fullname" . }}
  labels:
    app: {{ template "gs-spring-boot-docker.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}    
data:
{{ (.Files.Glob "resources/application-dev.yml").AsConfig | indent 2 }}
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.0-rc1", GitCommit:"280863d2362345450125ce15c3db504471dde2cf", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc1", GitCommit:"280863d2362345450125ce15c3db504471dde2cf", GitTreeState:"clean"}

Output of `kubectl version`:
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

OS: 
Windows
