### ISSUE TITLE
Generic Helm Chart / Common Chart - Usage

### ISSUE THREAD

**Issue by whithajess** [kubernetes/helm#4125]
I want to get some Direction from the community around the usage of generic/common helm charts.

It seems the current ethos is that a helm chart should be created on a per application basis, I want to challenge this and also get direction around what people should do in the use-cases that I have. 

We run microservices, from a chart perspective these are almost exactly the same the main difference being the _repository/tag/name_, every time we want to make a change to the chart we also want it on the N other microservices so I write something to automate this change roll-out (incoming mass commits, PRs, reviews, chart repository pushes) 

I think we all know you should re-use code so why is this common practice for helm charts? A perfect example of this to me it would make sense to deploy `generic_service_chart` with a set of `values.yaml` that set things like the _repository/tag/name_. 

Now we do have some app specific parts like for example `migration-jobs` and `db-vauum-crons` but in my mind these are also quite generic and in most cases could be included/excluded like the default ingress generated template is, in extreme cases the service could get its own chart or we could have a set of more generic charts.

Is this something other people are having problems with?
Is helm just not meant to be used for your whole set of applications?
Are people just putting all there similar applications into a big chart that deploys all of them?

Please let me know if I am not getting a specific concept or if you are also having this problem.

**Comment by whithajess** [comment]
Seems this has been talked about already here: https://www.youtube.com/watch?v=HzJ9ycX1h0c

**Comment by asherlporetz** [comment]
It could be dual purpose. Use the generic chart as is (resulting in a clunky/verbose values.yaml) or make it the starting point for a new chart. The latter of course doesn't exist yet. It would be great if helm can have some basic inheritance. A specific service can inherit from a team chart and its `Chart.yaml` can look like this.
```yaml
apiVersion: v1
description: Special service chart derived from team parent chart
name: special-service
version: 1.0.0
base:
  name: the-team-chart
  version: 3.2.1
  repository: https://repo
  values:
    port: 8085
    metrics:
      enabled: true         
```
