### ISSUE TITLE
crd-install annotation doesn't work

### ISSUE THREAD

**Issue by yevhenvolchenko** [kubernetes/helm#4259]
#3982 
@technosophos 
## BUG
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

## Steps to reproduce

1. Download [https://github.com/kubernetes/charts/tree/master/stable/cert-manager](url)
2. Update _./cert-manager/templates/certificate-crd.yaml_'s, _./cert-manager/templates/clusterissuer-crd.yaml_'s, _./cert-manager/templates/issuer-crd.yaml_'s `matadata:` with:
```
  annotations:
    "helm.sh/hook": crd-install
```
3. Add _stage.yaml_ to _./cert-manager/templates_:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yvolchenko@luxoft.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    http01: {}
```
4. Run `helm install --name cert-manager --namespace kube-system ./cert-manager`

Output: 
Error: apiVersion "certmanager.k8s.io/v1alpha1" in cert-manager/templates/stage.yaml is not available

Output tiller:
[tiller] 2018/06/22 11:10:37 preparing install for cert-manager
[storage] 2018/06/22 11:10:37 getting release history for "cert-manager"
[tiller] 2018/06/22 11:10:37 rendering cert-manager chart using values
2018/06/22 11:10:37 info: skipping unknown hook: "crd-install"
2018/06/22 11:10:37 info: manifest "cert-manager/templates/00-namespace.yaml" is empty. Skipping.
2018/06/22 11:10:37 info: skipping unknown hook: "crd-install"
[tiller] 2018/06/22 11:10:37 failed install prepare step: apiVersion "certmanager.k8s.io/v1alpha1" in cert-manager/templates/cluster-issuer-stage.yaml is not available
