### ISSUE TITLE
Helm hooks not being processed in Kind order

### ISSUE THREAD

**Issue by sjvp** [kubernetes/helm#4302]
`helm create hooktest`, delete existing templates and add `test.yaml`:

```
apiVersion: v1
kind: Job
metadata:
  name: foo
  annotations:
      "helm.sh/hook": "pre-install"
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  annotations:
      "helm.sh/hook": "pre-install"
```
Running `helm install hooktest --debug --dry-run` many times shows the order changing, usually Job first.

I had expected the normal Kind ordering to apply such that Job is always after Service, but that does not appear to be the case. 

The [doc](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md#writing-a-hook) states "*When Tiller starts the execution cycle of hooks of a particular Kind...*" implying the Kind should be being used (and then hook-weight within in each Kind group).

My actual use-case is a Job in a subchart and a Service in parent chart, both pre-install hooks.  The Job depends on the Service being Running.   This fails in the same way as the minimal sample above - i.e. not just --dry-run.

Helm 2.9.1
