### ISSUE TITLE
Helm removes a namespace after upgrade command

### ISSUE THREAD

**Issue by sgrigorev** [kubernetes/helm#4315]
**Description:** I want to have a chart that installs workloads into specified namespace. Installation is going successful but when I try to do upgrade, helm deletes namespace and everything inside it.
In future I'm planning to have charts for each namespace in order to have able to package them into main one. For this reason, I don't use the `--namespace` key.

**Steps to reproduce:**
You can use files that I described below to reproduce issue.
1. Install chart
```
$ helm install testing/ --name testing --set shouldCreateNamespace=true
```
2. Make sure that mongo is installed into testing namespace
3. Upgrade chart
```
$ helm upgrade testing testing/ --set shouldCreateNamespace=false --set mongo.image.tag=3.6
```
**Result:** namespace is deleted
Is it a bug or I did something wrong?

**Possible workaround:**
If I use the `--namespace` key then namespace is not deleted after upgrade.
```
$ helm install testing/ --name testing --namespace testing
$ helm upgrade testing testing/ --set mongo.image.tag=3.6
```

**My directories structure:**
```
helm-charts/
    mongo/
        templates/
            deployment.yaml
        Chart.yaml
        values.yaml
    testing/
        templates/
            namespace.yaml
        Chart.yaml
        values.yaml
        requirements.yaml
```
`mongo/templates/deployment.yaml` :
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ default .Values.namespace .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP

```
`mongo/values.yaml`:
```
namespace: default

image:
  repository: mongo
  tag: 3.4
```
`testing/templates/namespace.yaml`:
```
{{- if .Values.shouldCreateNamespace -}}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.global.namespace }}
{{- end -}}
```
`testing/values.yaml`:
```
shouldCreateNamespace: false

global:
  namespace: testing
```
`testing/requirements.yaml`:
```
dependencies:
  - name: mongo
    repository: "file://../mongo"
    version: 0.1.0
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE
