### ISSUE TITLE
Inheritance of values of dependency charts

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/helm#630]
According to the [charts docs](https://github.com/kubernetes/helm/blob/master/docs/charts.md#values-files), values for dependent charts can be specified in the `values.toml` file using TOML tables.

It would be great if there was a way to inherit chart values in manifest files. For example, for a wordpress deployment the database setup would need to be specified in the wordpress and the mysql charts like so:

```toml
wordpressUser = "admin"
...
mysqlUser = "root"
mysqlPassword = "secret-password"
mysqlDatabase = "wordpressdb"
...

[mysql]
mysqlUser = "root"
mysqlPassword = "secret-password"
mysqlDatabase = "wordpressdb"
...
```

The database parameters specified here are redundant and could lead to deployment errors if the values are not updated for all instances or if there are typo(s). 

This could be resolved if the values of charts specified as dependencies could be referenced in the top-level chart. I suggest referencing values using `.<chartname>.<field>` in the sprig functions. e.g. `.mysql.mysqlUser` would reference value of the `.mysqlUser` of the `mysql` chart.

Example,

```toml
wordpressUser = "admin"
...

[mysql]
mysqlUser = "root"
mysqlPassword = "secret-password"
mysqlDatabase = "wordpressdb"
...
```

and in the wordpress template
 
```yaml
apiVersion: v1
kind: ReplicationController
...
    spec:
      containers:
        - name: wordpress
          ...
          env:
            - name: WORDPRESS_USER
              value: {{default "admin" .wordpressUser}}
              ...
            - name: MYSQL_USER
              value: {{default "root" .mysql.mysqlUser}}
            - name: MYSQL_PASSWORD
              value: {{default "password" .mysql.mysqlPassword}}
            - name: MYSQL_DATABASE
              value: {{default "wordpressdb" .mysql.mysqlDatabase}}
```

thoughts?

/cc @prydonius

**Comment by technosophos** [comment]
Great idea. The implementation that I committed can handle this case:

Say I have a `foo` chart with this `values.toml` file:

```toml
hello = "world"

[bar]
goodbye = "world"

[bar.baz]
password = "secret"
```

Here's how the current resolution rules (should, if there are no bugs) work:

1. Templates in `foo/templates` will have access to `.hello`, `.bar.goodbye`, and `.bar.baz.password`.
2. Templates in `foo/charts/bar/templates` will have access to `.goodbye` and `.baz.password`
3. Templates in `foo/charts/bar/charts/baz/templates` will have access to `.password`

Does that make sense? I believe that fully accomplishes what you had asked for above.

/cc @fibonacci1729

**Comment by sameersbn** [comment]
thanks @technosophos that would work perfectly.

I was wondering if it made sense to use a TOML table for the top-level chart as well and allow specifying global values that would be accessible from all charts.

```toml
namespace = "production"
group = "foo"
appid = "app-341"

[foo]
hello = "world"

[bar]
goodbye = "world"

[bar.baz]
password = "secret"
```

where all charts will have access to `.namespace`, `.group` and `.appid` which should also work for the case described in helm/helm#80

What do you think?

**Comment by technosophos** [comment]
I am thinking about this. There are a few things that cause me to pause:

I am worried that doing this could have some surprising and negative consequences.

Say Chart A imports Chart B, which imports Chart C.

Now say the creator of Chart A has a template that uses `max` and has a values file like this:

```
max = 100
```

Unbeknownst to that creator, Chart C uses a variable named `max`. It has been accidentally overridden by the top chart.

I am also worried that the naming scheme above would impose the arbitrary limitation that a chart could not depend on a chart with the same name. So if I created a chart named `foo`, it could not have `charts/foo` as a dependency. I don't know if this use case really matters...

**Comment by sameersbn** [comment]
> Unbeknownst to that creator, Chart C uses a variable named max. It has been accidentally overridden by the top chart.

I agree this could be a problem. We could create a list of standard fields that can be used for specific uses so that the chart developers are well aware that they cannot create the same fields for some other use.

Or maybe we could skip this until we have some actual use cases.

> I am also worried that the naming scheme above would impose the arbitrary limitation that a chart could not depend on a chart with the same name. So if I created a chart named foo, it could not have charts/foo as a dependency. I don't know if this use case really matters...

IMHO such a dependency hierarchy is very unlikely.

Typically a chart developer would name the charts Kubernetes components (RC, Service, etc.) the same as the chart name. As such if two (or more) charts are created with the same name their components would have to be named differently since Kubernetes does not allow having duplicate names (in the same namespace). A better way to deal with this sort of thing from a chart developers perspective may be to give it a unique name to start with.

**Comment by technosophos** [comment]
I think we have two options. Tell me what you think of these:

Option 1: Top level is global, _everything_ else is namespaced.

```toml
scope = "global"

[mychart]
scope = "mychart"

[mychart.mysql]
scope = "mychart/charts/mysql"
```

Option 2: Add an explicit global namespace:
```toml
scope = "mychart"

[global]
scope = "everywhere"

[mysql]
scope = "mychart/charts/mysql"
```

Option 2 might be better protection against accidental overriding. But in the code it's a little bit of a hack.

Also, @sameersbn, I added several default values for charts. These would be perfect for putting into a global space:
https://github.com/kubernetes/helm/blob/master/cmd/tiller/release_server.go#L128

**Comment by sameersbn** [comment]
Option 2 looks a little messy to me in the sense that one could easily get confused with the `[global]` section. Maybe we should namespace everything?

```toml
# fallback, use should not be encouraged?
scope = "everywhere"

[global]
scope = "everywhere"

[mychart]
scope = "mychart"

[mysql]
scope = "mychart/charts/mysql"
```

> Also, @sameersbn, I added several default values for charts. These would be perfect for putting into a global space:

Sweet!

**Comment by technosophos** [comment]
I think I like that config, @sameersbn, though I think that would make `[mysql]` into `[mychart.mysql]`, since mysql there is a dependency of `mychart`.

What do we do if Chart A imports Chart B, and Chart B sets a `[global]` namespace?

**Comment by sameersbn** [comment]
> I think I like that config, @sameersbn, though I think that would make [mysql] into [mychart.mysql], since mysql there is a dependency of mychart.

I was of the opinion that the `[mysql]` block would be applied to any chart named `mysql` (assuming the chart names are unique). But as you pointed out earlier this could be a problem if more than one chart bears the same name. In which case `[mychart.mysql]` is clearer and its intent is explicit.

> What do we do if Chart A imports Chart B, and Chart B sets a [global] namespace?

I think top-level namespace values should override a lower levels namespace. Additionally a global namespace should not override chart specific values that have been defined. eg. in

```toml
[global]
password = "secret password"
foo = "bar"

[wordpress]
username = "admin"

[wordpress.mysql]
username = "wordpress"
password = "wordpress-password"
database = "wordpressdb"
```

The value of `.password` in the `wordpress.mysql` manifests should be `wordpress-password` and the value of `.password` in the `wordpress` manifests should be `secret-password`. And assuming that `.foo` is not defined in any other chart or namespace, its value will be `bar` everywhere

**Comment by technosophos** [comment]
After today's community stand-up meeting, we decided to try @sameersbn's proposal:

```toml
foo = "I'm a global"

[global]
bar = "I'm global too, because I'm in the global section"

[wordpress]
name = "I'm scoped to the wordpress chart"

[wordpress.mysql]
password = "I'm accessible to the wordpress chart (because I'm defined above it) as 'mysql.password' and to the mysql chart as 'password'"
```

The first implementation will be _experimental_ so that we can see how it feel to the chart developer and end user.

**Comment by technosophos** [comment]
I think it was @migmartri who mentioned that having `foo` as a global _and_ having a `global` section was confusing.

**Comment by migmartri** [comment]
Hi

 I can see here to features:

1 - Parent/Children settings scope

I agree with the current approach and I like it. It seems easy to understand and there is not extra boilerplate that the user needs to add in case that it does not want to use this feature.

2 - Shared global namespace.

Regarding option #1 I do not like the fact that we will force users to add a namespace for the current chart, if the chart name changes the user will need to change it also here. For me the root scope should be the current chart and there should not be any need for namespacing.

```
[mychart]
scope = "mychart"
``` 

Regarding option 2, I like the fact that it is explicit, (I am not convinced about the `global` keyword though) and use the notation that @technosophos mentioned `{{.global.password}}`

There might be another option, which would be to add a flag (now that we have yaml) to indicates that the value can be exposed, in any case I think that it might be a overkill at this stage of the project.

i.e

```
poet: 
  value: "Coleridge",
  exported: true

title: "Rime of the Ancient Mariner"
stanza: ["at", "length", "did", "cross", "an", "Albatross"]
```

My take would be to implement option 2, enforcing [global] namespace

**Comment by technosophos** [comment]
Okay, the PR that just got merged basically provides these features:

- The top-level name/val pairs are for the current chart.
- Every subchart is namespaced as described before.
- A special `global` namespace is passed from the top to every subchart.

So if I have a chart called `mychart`

```yaml
name: foo    # This is the name for mychart, and is available to it as {{.name}}. It is not available to mysql.

mysql:
  name: db    # This is the name for mychart/charts/mysql, it is available to `mysql` as {{.name}} and to 
                     # mychart as {{.mychart.name}} 

global:
  app: mychart   # This is available in ALL templates as {{.global.mychart}}
```

Globals are coalesced from the top down:

mychart/values.yaml
```yaml
global:
  app: mychart
```

mychart/charts/mysql/values.yaml
```
global:
  size: 4
```

The above basically evaluates to something like this:

```yaml
global:
  app: mychart

mysql:
  global:
    app: mychart
    size: 4
```
