### ISSUE TITLE
`helm package <chart>` modifies the `Chart.yaml` files

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/helm#749]
I created a chart with the following `Chart.yaml` spec

```yaml
name: redmine
description: A flexible project management web application.
version: 0.1.0
keywords:
- redmine, project management
home: http://www.redmine.org/
sources:
- https://github.com/bitnami/bitnami-docker-redmine
maintainers:
- name: Bitnami
  email: containers@bitnami.com
```

Upon doing `helm package <chart>`, the `Chart.yaml` is modified both in the chart directory as well as in the release package. Here are the modified contents:

```yaml
name: redmine
description: A flexible project management web application.
version: 0.1.0
keywords:
- redmine, project management
maintainers:
- name: Bitnami
  email: containers@bitnami.com
home: http://www.redmine.org/
```

Here the `sources` field is removed.
