### ISSUE TITLE
Malformed URL in index.yaml

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#784]
Hi

It seems that the url contained in the index.yaml after calling `helm repo index` is malformed (only one slash on http://)

Having a repository local directory:

```
$ ls
redmine-0.1.0.tgz
```

```
$ helm repo index . http://bitnami.com
```
As you can see in the generated index.yaml, the URL is incorrect.
```
cat index.yaml 
redmine-0.1.0:
  name: redmine
  url: http:/bitnami.com/redmine-0.1.0.tgz
  created: 2016-06-02 00:11:28.132205428 +0000 UTC
  checksum: 245b3995e477edf1c98e8b0fb497f9775888dfc2
  chartfile:
    name: redmine
    description: A flexible project management web application.
    version: 0.1.0
    keywords:
    - redmine, project management
    maintainers:
    - name: Bitnami
      email: containers@bitnami.com
    home: http://www.redmine.org/

```
It seems that the problem affects to [your index as well](http://storage.googleapis.com/kubernetes-charts/index.yaml)
 
Looking into the issue it seems that the problem is related to the use of filepath.join on the url [here](https://github.com/kubernetes/helm/blob/master/pkg/repo/repo.go#L134)

Changing that line to use url.Parse plus adding path + tar.gz should fix the problem and respect local paths as well. I will send a patch.

Regards,
Miguel
