### ISSUE TITLE
protoc-gen-go version inconsistency.

### ISSUE THREAD

**Issue by fibonacci1729** [kubernetes/helm#845]
Helm developer doc instructs developers to:
```
Install the protoc Go plugin: go get -u github.com/golang/protobuf/protoc-gen-go
```

However, protoc-gen-go needs to be built against the version of go/protobuf we are using (V1).

The Helm protobuf dependencies in glide.yaml:
```
- name: github.com/golang/protobuf
  version: f0a097ddac24fb00e07d2ac17f8671423f3ea47c
  subpackages:
  - proto
  - ptypes/any
  - ptypes/timestamp
```

Adding protoc-gen-go as a subpackage seems to work but is untested.
